### ISSUE TITLE
ZONE_NOT_FOUND error

### ISSUE THREAD

**Issue by mheidenstecker** [icloud-photos-downloader/icloud_photos_downloader#107]
Running icloudpd under Linux on raspberry pi after entering two-factor authentication i get the following error.

`2018-10-01 22:42:55 DEBUG    Authenticating...
iCloud Password: 
2018-10-01 22:43:01 DEBUG    Looking up all photos and videos...
Traceback (most recent call last):
  File "/usr/local/bin/icloudpd", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/icloudpd/base.py", line 249, in main
    photos = icloud.photos.all
  File "/home/pi/.local/lib/python2.7/site-packages/pyicloud_ipd/base.py", line 332, in photos
    self.params
  File "/home/pi/.local/lib/python2.7/site-packages/pyicloud_ipd/services/photos.py", line 158, in __init__
    headers={'Content-type': 'text/plain'}
  File "/home/pi/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/home/pi/.local/lib/python2.7/site-packages/pyicloud_ipd/base.py", line 114, in _raise_error
    raise(api_error)
pyicloud_ipd.exceptions.PyiCloudServiceNotActivatedErrror: Please log into https://icloud.com/ to manually finish setting up your iCloud service (ZONE_NOT_FOUND)`

I already logged on to iCloud.com and set time zone but no effect on the command line tool.

Could anybody help me please?

**Comment by ndbroadbent** [comment]
Hello, sorry I've actually never seen that error before. I found [ZONE_NOT_FOUND in a list of error codes](https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitWebServicesReference/ErrorCodes.html), but doesn't help too much. 

They're saying that you need to log into https://icloud.com and continue setting something up, but if you've already done that then I'm not too sure what to suggest.

**Comment by JeddyWong** [comment]
Hello, I've solve this problem just a moment ago. this problem is because you icloud photo auto-upload.
用中文再来一次，造成这个问题的原因是：你关闭了照片自动上传，导致云端没打开这项功能。只需要把手机上的照片上传iCloud功能就行了。

**Comment by pyToshka** [comment]
> Hello, sorry I've actually never seen that error before. I found [ZONE_NOT_FOUND in a list of error codes](https://developer.apple.com/library/archive/documentation/DataManagement/Conceptual/CloudKitWebServicesReference/ErrorCodes.html), but doesn't help too much.
> 
> They're saying that you need to log into https://icloud.com and continue setting something up, but if you've already done that then I'm not too sure what to suggest.

You will get this error ZONE_NOT_FOUND(404) because synchronization for photos did not enable yet. If you want to have photos in Icloud need to switch on synchronization in device settings, after switch on icloud_photos_downloader will work as expected

**Comment by menkej** [comment]
This should be closed as I can follow @pyToshka's argument. Maybe this is something we could add to some FAQ/documentation and throw a better error message?

**Comment by menkej** [comment]
I started an FAQ in the wiki-section on GitHub to document this situation. Feel free to contribute. As this is something we can't fix in icloudpd I'll close this issue.

**Comment by dmd** [comment]
I get this error, I see it in the FAQ, but still have no idea what to do. How do you actually fix it?  It says "If you want to have photos in iCloud need to switch on synchronisation in device settings", but ... what device settings, where?  My photos are all synced, via icloud, between my phone, ipad, and computer (and have been for years), so I don't know what else to turn on.

**Comment by menkej** [comment]
@dmd , can you view your photos when you log into iCloud.com with your browser?

**Comment by dmd** [comment]
@menkej yes, I can see all my photos in the web version of Photos on icloud.com.

**Comment by menkej** [comment]
What is the exact command you're running @dmd ? What is the output? Which OS/python version are you running on?

**Comment by dmd** [comment]
Any use of it does this, e.g.:

```
$ icloudpd -l
iCloud username/email: dmd@3e.org
2021-07-31 19:24:16 DEBUG    Authenticating...
iCloud Password:
Please log into https://icloud.com/ to manually finish setting up your iCloud service (ZONE_NOT_FOUND)
```

```
$ python -V
Python 3.9.5

$ sw_vers
ProductName:	macOS
ProductVersion:	11.5
BuildVersion:	20G71
```

**Comment by dmd** [comment]
@menkej I've tried this on macOS, Linux, and even FreeBSD (a TrueNAS box) - same results on all. And yes, if I take a photo on my phone, it shows up a few seconds later on the icloud.com website, so sync is definitely on!
