### ISSUE TITLE
401 Gone Error

### ISSUE THREAD

**Issue by thechild** [icloud-photos-downloader/icloud_photos_downloader#111]
I know there were some previous threads about this, but I'm hitting this error usually after hours of successful downloading.  I have 40k photos in my library, I can usually run this for hours but then all of a sudden every single photo will fail the 5 retries until I kill and restart the process.  The error that comes back from pyicloud is a 401 Gone.  I don't really know how to debug that any further - maybe icloud recycles the URLs after a few hours or something?  It's frustrating to have to restart the whole process manually and then wait while it checks to see that all the initial photos have already been downloaded...

It's also tricky to debug since it takes hours of running to hit.

**Comment by ndbroadbent** [comment]
Hi sorry about that! I don't know what might be causing that. We try to handle authentication errors and reauthenticate, but maybe this 401 Gone response is actually an authentication error in disguise. If restarting the script fixes it then I could add a case for this.

**Comment by menkej** [comment]
Hi @thechild ,
are you still having this issue with the current version? Some things have changed in the download handling during the last year...

cheers
Jörg

**Comment by menkej** [comment]
As there was no response after almost 30 days I assume this issue is not relevant any more or solved with some other change. So I'l close this now. If this is still relevant/reproducible feel free to reopen.
