### ISSUE TITLE
Created date of picture lost

### ISSUE THREAD

**Issue by anthonyschn** [icloud-photos-downloader/icloud_photos_downloader#115]
The created date of the picture is lost when we download the picture. Is there a way to have this information kept?

**Comment by ndbroadbent** [comment]
Hi @anthonyschn, thanks for opening this issue, I agree that that this a good idea. It was quite easy to update the modified time, so I've just pushed that change and released this in version `1.4.0`. Note that this will only apply to newly downloaded files - I haven't added any code to go back and fix the times for files that were already downloaded (these are just skipped.)

Unfortunately it's a bit harder to modify the creation time in a cross-platform way. See [this StackOverflow answer](https://stackoverflow.com/questions/237079/how-to-get-file-creation-modification-date-times-in-python) for more details.

I found [this solution for Windows](https://stackoverflow.com/questions/4996405/how-do-i-change-the-file-creation-date-of-a-windows-file-from-python). I also found [this blog post](https://bastibe.de/2015-10-03-changing-file-creation-dates.html) about changing the file creation time on Mac.

Unfortunately I don't have the time to add support for cross-platform creation times. But I'll leave this issue open and might get around to it in the future. In the meantime I would be happy to accept a PR. (But I'm not sure how tests would work. It would be hard to write tests that need to run on Windows, Mac, and Linux. Maybe we can delegate this to a different Python library that provides an abstraction.)

**Comment by anthonyschn** [comment]
OMG you saved my life ! That's awesome ! I just tested it, it's working fine ! :) 
I've around 50 000 elements on my cloud and using the icloud for Windows software was not working properly.

Thanks a lot ! I will start the download again :)

**Comment by menkej** [comment]
Is this something that should lead to a change in the program, or is this issue just solved for good? So maybe we could ask for help or work on this ourselves... What do you think @AndreyNikiforov @ndbroadbent ?

**Comment by isharky** [comment]
Hi @menkej this has been solved for linux.

**Comment by menkej** [comment]
Thanks for the info @isharky ! So I'll close this PR for now. Feel free to reopen if you (or someone else) experiences issues on a different platform.
