### ISSUE TITLE
No option to delete all photos or downloaded photos?

### ISSUE THREAD

**Issue by grokit** [icloud-photos-downloader/icloud_photos_downloader#124]
Title says all... once I downloaded the photos, want to wipe them from iCloud.
auto-delete does not delete the photos in library, only applies to bin.

**Comment by Suncatcher** [comment]
Support this! Can donate the development

**Comment by kooyeed** [comment]
+1

**Comment by maxexcloo** [comment]
Would love a feature to delete all photos! +1

**Comment by HilmiEgemenCiritoglu** [comment]
+1

**Comment by menkej** [comment]
> Support this! Can donate the development

Hi @Suncatcher, are you saying you want to add this feature? You're more than welcome to submit a pull request!

**Comment by AndreyNikiforov** [comment]
The tool synchronizes photos from iCloud to local drive (==one way). Modifying icloud assets should be a separate and explicit action or even a separate utility.

**Comment by menkej** [comment]
> even a separate utility.

I agree with that! Fokus of icloudpd is more or less "backup". Wiping iCloud should be a different tool.

**Comment by deucalion** [comment]
Would you be ok with it using a different tool name (e.g. icloudrm) but the same repository/project?

I think it's a great idea, btw!
