### ISSUE TITLE
How to use the folder structure option?

### ISSUE THREAD

**Issue by Tharayman** [icloud-photos-downloader/icloud_photos_downloader#131]
By default pictures are orgnaized into folder for year -> month -> day
This makes up a whole lot of folders, making it rather time-consuming should one want to load all pictures up to an alternative cloud service.

**Comment by agittins** [comment]
(Necro, I know, but I just worked this out...)

I just tried using `--folder-structure {:%Y/%Y-%m-%d}` and it worked well for me.

If you're not used to these types of substitutions, what's going on there is %Y gets replaced with the full year, %m with the month number, zero padded (eg, Jan is 01, Jul is 07 etc) and %d with the date, also zero-padded to two places (eg, 05, 11, 31 etc).

So with the above, my folder layout becomes:

```
path/to/photos/
              2019/
                 2019-12-23/
              2020/
                 2020-02-03/
                 2020-02-09/
```

As for the braces and colon, I've no idea what's going on there! Not sure if it's shell escaping or a python thing.... but it works.

**Comment by menkej** [comment]
Hi @Tharayman !
Did the example @agittins provide help you? Is there anything else you need?

**Comment by menkej** [comment]
I started a wiki entry in the FAQs for giving examples how to use it. Feel free to contribute!

**Comment by Xiaotian0726** [comment]
I tried using `--folder-structure {:0}` and all photos were downloaded into the folder `Photos\0`
