### ISSUE TITLE
 crontab: must be suid to work properly  

### ISSUE THREAD

**Issue by kbouse** [icloud-photos-downloader/icloud_photos_downloader#136]
Many thanks
      I used this and it's pretty cool,But there is a problem.
      I use docker to run ndbroadbent/icloudpd. When Crontab creates timed task, out"must be suid to work properly".
    Cant't use Chmod alter BusyBox  permission.

thanks you

**Comment by menkej** [comment]
Maybe this ist just a permission issue, @kbouse? Are you sure that you have write-access to to download-folder? What is the exact error-message (or log file) you're getting?

**Comment by menkej** [comment]
As there was no response for a month I close this issue. Feel free to reopen with additional information if the issue still exists.
