### ISSUE TITLE
Something wrong with the folders

### ISSUE THREAD

**Issue by fishmanxp** [icloud-photos-downloader/icloud_photos_downloader#137]
I have some problems with your code in Github icloud_photos_downloader.
I use docker of my NAS (synology) to create a container of icloudpd, but I can't use it to download photos in icloud. I know maybe some reason in folders, but I don't know how to solve it, so I contact you for help. Thanks very much.
![1](https://user-images.githubusercontent.com/15833327/58217455-728b9600-7d35-11e9-984d-8232c57cfb6d.jpg)
![2](https://user-images.githubusercontent.com/15833327/58217456-728b9600-7d35-11e9-8490-832dbbb7450e.jpg)
![3](https://user-images.githubusercontent.com/15833327/58218061-1ece7c00-7d38-11e9-9648-5307855ef1ef.jpg)
![Uploading 3.jpg…]()

**Comment by fooololo** [comment]
me too

**Comment by gqbre** [comment]
@fishmanxp @fooololo 求教 username, password 等参数在群晖 docker 里是要在哪里添加... ?

**Comment by gqbre** [comment]
@fishmanxp @fooololo 两步验证码拿到了.. 但是从哪里输入进去？终端机那边都是空白

**Comment by gqbre** [comment]
same problem

**Comment by gqbre** [comment]
@fishmanxp @fooololo 权限问题，本地的文件夹给 everyone 读写权限就行了

**Comment by AndreyNikiforov** [comment]
@fishmanxp @fooololo has the issue been solved?

**Comment by menkej** [comment]
No reaction after almost 30 days. I assume this issue is no longer there/has been solved, so I lcose this now. Feel free to reopen with additional info if this issue is still there. Thanks.
