### ISSUE TITLE
Help creating an EXE

### ISSUE THREAD

**Issue by wes1993** [icloud-photos-downloader/icloud_photos_downloader#146]
Hello!!
I love this project and i want to save in my pc.
can you explain to me how can i build and EXE so i don't need to install everytime python etc?
Thanks a lot
Stefano

**Comment by metahnetoutage** [comment]
Hello,

To save you time, it is cheaper for you to learn how to connect to iCloud
via JavaScript api provided by Apple.

You can do authentication and not waste time on this project. You will
still be Abel to do so much directly with Apple stuff. Why? Because this
project does bad hack job.

It is not supported anymore, it is for older versions of iPhone until
around 5/6 maybe 7.

Spend quality 40 hours learning how to connect via JavaScript and do
authentication and spend day $100 on Apple license if you want to do more.

That is time and money well spent.

You expectations for this project are at 9, when it is at 5 level at best.

I am a developer.

Dima

**Comment by wes1993** [comment]
Thanks a lot for your reply.
I’m not a developer so I don’t know how to use Apple api... also is for personal use so I 100€ day is so much expensive for me... :(
Do you know different software for downloading photos from iCloud?
The Apple iCloud software and iCloud.com won’t work very well... :(

**Comment by metahnetoutage** [comment]
I was going to do my own...This is the closest I found.

To help you out your comment should be:
Open up a terminal and navigate to directory where you’d aced this python
file.
Name of program -d /pathtoDirectoryWhereyousave

The system will prompt you for user name
And password. Enter both

So suppose you saved the file at mycooldir.

You would cd there. Then type name of application -d ./pathtodestination

If you check docs you will see this, now, make sure you have -d before your
directory. I replied once in a threat you can see my answer.

Let me know if you need any extra help.
Session is 5 mins so do not download a lot.

Dima

**Comment by Quentame** [comment]
@metahnetoutage

Do you have a link to the iCloud JS API ?

I found this.

Thanks.

**Comment by metahnetoutage** [comment]
I can give you yes.
https://developer.apple.com/documentation/cloudkitjs

Take your Time and do not rush. It’s is not a one two three.

**Comment by RhetTbull** [comment]
This might help: [auto-py-to-exe](https://github.com/brentvollebregt/auto-py-to-exe)  It can convert the python script into a stand-alone .exe

**Comment by wes1993** [comment]
Thanks a lot to everyone for the help!!! :-D
sorry for my late reply but i'm in Italy...
@RhetTbull I have used auto-py-to-exe but won't work... after building just black window....
@metahnetoutage i'm using windows.. i have do the command you have told to me but it will just download the photos not make an exe... probably I do not understand.. :-(
Thanks a lot
Stefano

**Comment by metahnetoutage** [comment]
You have prevailed where many have failed congrats! For more, you need to
make your own app or read more than Readme and again experiment!

**Comment by wes1993** [comment]
@metahnetoutage 
Thanks a lot
i will do a search

**Comment by metahnetoutage** [comment]
You utmost welcome! I will start such project in May! You are welcome to
work and submit code upon reviewing.

**Comment by wes1993** [comment]
Thanks a lot!! this is a good news!!
i have solved part of the problem for now... i have tis error now...
![image](https://user-images.githubusercontent.com/52070589/78242800-f6301a80-74e2-11ea-8287-82ba14ac4254.png)

**Comment by metahnetoutage** [comment]
I had same issue. Solution, get rid of both username and password. And
press Enter.

At each prompt for email or password supply them.

Let me know if it works!

**Comment by metahnetoutage** [comment]
After you succeed, do not bother fixing it! Why? It is honestly not worth
it! That is why I am working on JS api!

I can make it work. Via JavaScript and will dis o in May.

**Comment by wes1993** [comment]
Thanks a lot i will try!!
And perfect for may!!
Stefano

**Comment by metahnetoutage** [comment]
Although I origins was going to work on this, I decided not to.

**Comment by wes1993** [comment]
Ok no problem thanks a lot :)

**Comment by metahnetoutage** [comment]
You need to work on connection speed!

**Comment by wes1993** [comment]
What do you mean for connection speed?

**Comment by metahnetoutage** [comment]
I mean the speed of your download and upload of individual files depends on
your connectivity speed. You can get a better modem and router yet what is
your package with your internet provider? How far are you away from them?

You can easily google JS Api which is faster than Python and work first on
a authentication.
Just log onto iCloud and get access to Photos and Videos.

If you want to do the same with python, try.
Do not use the code here, write your own.

I guarantee you will implement a better version.

Dima

**Comment by AndreyNikiforov** [comment]
@wes1993 have you found a way to create one EXE for windows? Would be very valuable for many Windows users without an appetite for installing Python.

**Comment by wes1993** [comment]
Yes, but now I have lost everything because my HDD is dead... :(
Anyway if I found some email and other stuff I will write you.
Now I’m using a different software

**Comment by menkej** [comment]
> Now I’m using a different software

Ok, so this ticket is obsolete now?  Are you willing to share how you created the exe?

**Comment by AndreyNikiforov** [comment]
Found comparison of different approaches: https://pyoxidizer.readthedocs.io/en/latest/comparisons.html

**Comment by wes1993** [comment]
Hello to everyone!!! 
I have found some Telegram message and i have some information:
1. For creating the EXE i have used cx_freeze
2. I have used this requirements.txt (Thanks to rdidyk)
[requirements.txt](https://github.com/icloud-photos-downloader/icloud_photos_downloader/files/5729397/requirements.txt)
3. For reference use this fork:
https://github.com/rdidyk/pyicloud/tree/refactoring/remove-inspect-usage

Again wee need to tell thanks at rdidyk

Best Regards
Stefano
