### ISSUE TITLE
Suggestion : SMTP notification / only errors

### ISSUE THREAD

**Issue by Zazou89** [icloud-photos-downloader/icloud_photos_downloader#166]
Hello,

Thank you again for your amazing works ! I have one suggestion, I set Telegram as notification, is it possible to enable notifications only when there are error ? 

Other thing, for SMTP notirfcation I need to put in arguments with for example "--folder-structure={:%Y/%m}", right ?

Thank you

**Comment by boredazfcuk** [comment]
> 
> 
> Hello,
> 
> Thank you again for your amazing works ! I have one suggestion, **I set Telegram as notification, is it possible to enable notifications only when there are error ?**
> 
> Other thing, for SMTP notirfcation I need to put in arguments with for example "--folder-structure={:%Y/%m}", right ?
> 
> Thank you

Did you mean to raise this as an issue against my Docker container?

This is the repository for the application I package in Docker and doesn't have Telegram notifications.

**Comment by menkej** [comment]
@Galiwyx I don't really get your issue. Could you please provide more details or elaborate on it?

**Comment by menkej** [comment]
As there was no response for a month I close this issue. Feel free to reopen with additional information if the issue still exists.
