### ISSUE TITLE
Support for multiple languages.

### ISSUE THREAD

**Issue by wclebb** [icloud-photos-downloader/icloud_photos_downloader#175]
Please allow me to use Google Translate to describe my needs.
Some time ago, I learned that icloudpd can help me back up iCloud photos to NAS, which is what I want.

Later, when executing the command icloudpd, errors were often reported;
such as
INFO     Great, you're all set up. The script can now be run without user interaction until 2SA expires.
You can set up email notifications for when the two-step authentication expires.
(Use --help to view information about SMTP options.)
Traceback (most recent call last):
  File "/home/wclebb/.local/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/home/wclebb/.local/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/wclebb/.local/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/wclebb/.local/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wclebb/.local/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/wclebb/.local/lib/python3.8/site-packages/icloudpd/base.py", line 292, in main
    directory = os.path.normpath(directory)
  File "/usr/lib/python3.8/posixpath.py", line 336, in normpath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

I consulted V2ex（https://www.v2ex.com/t/716199） and got answers from netizens. This is due to an error in Chinese compatibility. I need to try to delete all related Chinese albums in iCloud. After I tried to delete all Chinese albums, I finally executed it correctly and downloaded the first photo. This is good news for me having been lingering on this error for three days.

But the bad news is that icloudpd has an error due to Chinese compatibility.
Therefore, I hope to be able to obtain compatibility support for multiple languages, because if I use Chinese or other languages, there will definitely be such a demand;

Therefore, thanks for providing icloudpd.

**Comment by AndreyNikiforov** [comment]
@wclebb I suspect the issue is related to environment and/or python setup.

I added test in #176 to validate and it works on my windows and in docker. To check your setup, you can 1) run `docker build .` 
 to validate that dockerized python works with your files and 2) `py.test --cov=icloudpd --timeout=3 --cov-report term-missing` 
 (after installing all requirements) that python setup on your machine works with Chinese chars.

**Comment by AndreyNikiforov** [comment]
@wclebb The errors indicate that python does not like base folder you are passing to the program (with `--directory` parameter). Can you please try base path without Chinese chars before doing any other tests? That may be even a workaround for you.

**Comment by wclebb** [comment]
> @wclebb The errors indicate that python does not like base folder you are passing to the program (with `--directory` parameter). Can you please try base path without Chinese chars before doing any other tests? That may be even a workaround for you.

Last night, I wanted to try to create a Chinese album again in order to test whether icloudpd can work normally. It can be run.

Today I took my family’s iCloud account to back it up, and it ran without obstacles. When I learned that it was running normally, I was confused, it seemed that it had nothing to do with Chinese compatibility.

I carefully recalled what I did at the time, and it seemed that when I first tried icloudpd, it was difficult to move on to the next step. When I think about it, I may have found its problem, even though I tried many different commands.

But just write

icloudpd \
--folder-structure {:%Y-%m-%d} \
--directory /Home/iCloud-ZWM \
--username username@name.com \
--password yourpassword

It can run normally, including Chinese albums.

I re-entered the account of another family member. At first, icloudpd asked me to enter the Apple ID account. After I entered the password, the same error was reported. But as long as I enter the above command, I need to accurately include --directory to point to any directory, and it can run normally.

As for the Chinese directory, Docker where I am cannot enter any Chinese directories, and naturally I cannot use the directories with Chinese in the command.

I apologize for the error in this issue and hope to close this issue.

**Comment by AndreyNikiforov** [comment]
> As for the Chinese directory, Docker where I am cannot enter any Chinese directories, and naturally I cannot use the directories with Chinese in the command.

@wclebb thanks for explanation and re-testing. Docker is expected to work with Unicode as well. Please provide details on how you run it.
