### ISSUE TITLE
Empty directory structure being created

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#185]
If I run the following command:
```
/usr/bin/icloudpd --directory /test --cookie-directory /cookie --username fake@email.com --folder-structure {:%Y} --only-print-filenames
```
the script will create an empty directory structure under the download directory. Is this expected behaviour?

The name "only-print-filenames" suggest that no changes should be made to the filesystem, only a list of files should be displayed.

**Comment by AndreyNikiforov** [comment]
I interpret `--only-print-filename` flag as a dry run -- no changes are expected (except authentication).
