### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by AndreyNikiforov** [icloud-photos-downloader/icloud_photos_downloader#198]
Folks, I am proposing the following rules for releasing:
1. Release each Friday if there is at least one new change in CHANGELOG
1. Follow Semantic versioning, e.g.
    1. increment `patch` for bug fixes and minor features
    1. increment `minor` for larger feature adding new behavior
    1. increment `major` for breaking changes

The following steps must be completed manually today:
1. Update CHANGELOG and setup/py with new version (and commit to master)
1. build .whl (name with version number)
1. publish .whl to PyPI
1. create github release with notes from Changelog and .whl as asset; name of the release is version number
1. create and publish to dockerhub an image (latest, <version>-alpine, and <version> tags)

@ndbroadbent @menkej any comments?

**Comment by ndbroadbent** [comment]
Sure, this sounds good to me! I will push a new release now

**Comment by menkej** [comment]
1. check
2. sure!

Regarding the steps: I am working on GitHub-Actions. I already have an automation like: you create a Tag v1.2.3. Steps steps 2/3/4 are done (some little work for the ChangeLog left. Currently I have just the commits since last Tag). I was able to publish to pypi-test as well. If we'd put the correct credentials into the SECRECTS this could be done by magic. Automating step 5 should not be too difficult.

So in the End step 1 must be done + Creation of a tag, if it works out like planned. What do you think?

**Comment by AndreyNikiforov** [comment]
> Regarding the steps: I am working on GitHub-Actions. I already have an automation like: you create a Tag v1.2.3. Steps steps 2/3/4 are done (some little work for the ChangeLog left. Currently I have just the commits since last Tag). I was able to publish to pypi-test as well. If we'd put the correct credentials into the SECRECTS this could be done by magic. Automating step 5 should not be too difficult.
> 
> So in the End step 1 must be done + Creation of a tag, if it works out like planned. What do you think?

As I understood there is a GitHub Action for publishing release. I think we can execute 2-5 steps on that event. I think it may be not hard to update setup.py with version on publishing and never commit version in the repo. 

Updating CHANGELOG will require manual commit unless we switch to using GitHub Release for change log completely -- pros and cons with such such of course. May be we can revisit this topic after we automate the rest.

**Comment by menkej** [comment]
> As I understood there is a GitHub Action for publishing release. I think we can execute 2-5 steps on that event.

This is exactly what I'm using/working on. But testing Actions is a pain in the a**! And: perfect timing: handling of environment variables has been changed/deprecated just recently. I thought it would be easy, but requires some more fiddling around... When I have that working I have to reset my fork. All this stuff just works on master... :-(

**Comment by menkej** [comment]
Ok, finally... Actions can be quite a beast... I have created an action that works as follows:

- you edit CHANGELOG  and add a new RELEASE. (lets say 1.7.0 for now --> following SemVer of course.) The structure stays as
```
## Unreleased

## 1.7.0 (2020-11-1)

- fix: --log-leve...
```
- you edit setup.py to reflect the new RELEASE version 1.7.0
- you commit
- you add a tag "v1.7.0"
- you push --tag
- This triggers the action(s). Quality checks are run and the new action "Create Release". This covers steps 2,3,4 mentioned above.:
```
2. build .whl (name with version number)
3. publish .whl to PyPI
4. create github release with notes from Changelog and .whl as asset; name of the release is version number
```

- publishing is currently to testpypi-repository, as we need the correct secrets in GitHub-Secrets

**For review:**
1. You can check the action here: https://github.com/menkej/icloud_photos_downloader/blob/master/.github/workflows/createrelease.yml
1. You can find a run of that action here: https://github.com/menkej/icloud_photos_downloader/actions
1. You can find the generated release here: https://github.com/menkej/icloud_photos_downloader/releases/tag/v1.7.19 (Version numbers not matching as I needed several runs to make it work...). If the credentials for docker are added to The GitHub-Secrets as well it will be quite easy to add the docker steps, too.

Maybe it could be possible to automate setup.py-change

**Learnings and questions:**
- working with Actions requires working on `master`. Adding an action via a branch/pull request did not work for me. Is this possible?
- debugging Actions is "different" and works best via pushing/testing online. Setting `ACTIONS_RUNNER_DEBUG`and `ACTIONS_SETP_DEBUG` helps to get additional info (online).
- Local testing of actions, p.e. with `act` does not cover all the necessary things - at least I did not get this Workflow to run
- By working on `master` I messed up with my fork. What is the best practice to clean that up and get back in sync with upstream? 

What do you think, guys?

**Comment by AndreyNikiforov** [comment]
> ps: This discussion is overlapping with #181, isn't it?

I created this to agree on the schedule for the releases. Listing steps for release was for context/completeness and it derailed discussion IMO. I am closing this as we all agreed on weekly releases and we'll work on automating/improving release process in #181
