### ISSUE TITLE
Improving the Release-Process even more...

### ISSUE THREAD

**Issue by menkej** [icloud-photos-downloader/icloud_photos_downloader#225]
Follow-Up to the discussion in #181 .

After some hiccups (sorry for the check-ins on master...) the automatic release Action is working. Test release v1.7.1rc1 has been created successfully. Upload to pypi.org was successful (and it was marked as release candidate as well). Upload to dockerhub was successful, too (no special marker as pre-release).

It is not perfect yet. Things that come to my mind spontaneously:
- pypy-Repository should be configurable via secret to allow testing
- disabling fo this action via GitHub secret
- cleanup in dependency installation -> scripts vs. explicit commands -> running order/order of dependencies
- "local" script to automate releasing, maybe
- clarify pre-releases in dockerhub
- describe local process and what to do if something goes wrong
- maybe: feature to delete a release?

current process to publish a release
1. `git pull upstream && git merge upstream master`
1. Edit `setup.py` --> add new $version (p.e. 1.7.1rc1, following https://semver.org)--> `git add config.py && git commit` (keep in mind, that a rc-version needs to end with a number.)
1. Create a new version tag: p.e. `git tag v1.7.1rc1`
1. Push the new tag to upstream: `git push upstream && git push --tags upstream` (**it is important to push first as `--tags does not push changes**!)
1. now the magic should happen -> Check if Action runs properly.

**Comment by AndreyNikiforov** [comment]
@menkej this is an awesome progress!

- Do you think it is possible to keep setup.py in repo at 0.0.1 version and update it only for release without committing? If not for changelog, all version-related info will be in tags and github releases (~=metadata)
- What should happen to changelog for `rc` and `ga` releases? I suspect changelog for all `rc`s should be aggregated into `ga` changelog. We'll keep updating changelog for release as manual process to cover all these complexities, correct?

Will you be taking this task for polishing release automation further? Scope is just polishing (local scripts, local processes etc), not big features?

**Comment by menkej** [comment]
> * Do you think it is possible to keep setup.py in repo at 0.0.1 version and update it only for release without committing? If not for changelog, all version-related info will be in tags and github releases (~=metadata)

Yes. It's possible. You could just create/patch `setup.py` on the fly. On the other hand it adds an extra layer of security as I check setup.py vs tag-name in the script at the moment. Alternatively the Changelog could be used for reference... But you could also "over-automate"... I was thinking about automating above mentioned steps in a local interactive script just for the fun of it. That could help in ensuring consistency. I don't really expect building issues (should be covered by the quality-checks). Issues could imho only be transfer of the packages to the repositories....

> * What should happen to changelog for `rc` and `ga` releases? I suspect changelog for all `rc`s should be aggregated into `ga` changelog. We'll keep updating changelog for release as manual process to cover all these complexities, correct?

I would do so as this improves readability and helps to focus on a last step of quality-checking.

> Will you be taking this task for polishing release automation further? Scope is just polishing (local scripts, local processes etc), not big features?

I'm already into it. Even though the "testing" really sucks, I'd continue on this.
