### ISSUE TITLE
Misattributed 1.7.1rc1 release

### ISSUE THREAD

**Issue by AndreyNikiforov** [icloud-photos-downloader/icloud_photos_downloader#233]
Github release 1.7.1rc1 has minor misattribution:
- shows 1.7.1 change log
- master change log shows that 1.7.1 was released 2020-11-10
- 1.7.0 is the latest in dockerhub and pypi

Need to fix 1.7.1rc1 to be `rc1`, not GA 1.7.1

**Comment by menkej** [comment]
Thanks for verifying! 1.7.1rc1 was a test run - I know that the Changelog does not match. I left it on 1.7.1 on purpose as it is a rc release for 1.7.1. I would just leave it like that till the final 1.7.1 (I wanted to release tomorrow). The release date is one day early as I was fighting with the transition from my fork to master (fun with new Actions) and  the migration to the scripts.

I used the DockerHub credentials provided by @ndbroadbent in the secrets, so it was released on icloudpd/icloudpd as 1.7.1rc and it correctly shows up here: https://hub.docker.com/r/icloudpd/icloudpd/tags Where did you find 1.7.0?

Same goes for pypi. Pypi shows only "real" releases in the overview. The RC is correctly listed here: https://pypi.org/project/icloudpd/#history

I would just release a clean 1.7.1 (worth it as there were some changes under the hood) and lib updates in the Changelog tomorrow.

By the way: If it happens that we push a release we want to remove later I'll need access with my login (or the real login-data) to dockerhub/pypi. Could you set me up there, @ndbroadbent ?

**Comment by AndreyNikiforov** [comment]
> I used the DockerHub credentials provided by @ndbroadbent in the secrets, so it was released on icloudpd/icloudpd as 1.7.1rc and it correctly shows up here: https://hub.docker.com/r/icloudpd/icloudpd/tags Where did you find 1.7.0?
> 
> Same goes for pypi. Pypi shows only "real" releases in the overview. The RC is correctly listed here: https://pypi.org/project/icloudpd/#history

My bad, I wanted to emphasize that 1.7.1 is not in these remote locations.

**Comment by AndreyNikiforov** [comment]
> Thanks for verifying! 1.7.1rc1 was a test run - I know that the Changelog does not match. I left it on 1.7.1 on purpose as it is a rc release for 1.7.1. I would just leave it like that till the final 1.7.1 (I wanted to release tomorrow). The release date is one day early as I was fighting with the transition from my fork to master (fun with new Actions) and the migration to the scripts. Maybe there should not have been a release date in the CHANGELOG for the test rc release at all. What do you think?

change log should match releases on github and both should match functionality available in the images IMO. That means that change log will have `rc`s and final version and all of the change log items from `rc` will be in final version as well.

Release dates may show one day off due to timezones and that is okay IMO.

Keen on seeing 1.7.1 final released though pipeline!

**Comment by menkej** [comment]
> Keen on seeing 1.7.1 final released though pipeline!

I just tagged v1.7.1. Feel free to find bugs in the release pipeline!

PS: I accidentally also pushed two old test-tags (v1.6.2.1/v1.6.2.2). I already deleted the tags. Hope it is clean now...

**Comment by menkej** [comment]
Git sucks.

As I assumed before: you have to `git push upstream && git push --tags upstream`! If you just do the latter the changes don't get pushed, just the tags. :( Now I'd like to delete the published releases and re-upload...

**Comment by AndreyNikiforov** [comment]
I noticed that 1.7.1 GH release does not have items from prev non stable releases, e.g. 1.7.1rc1. Not a big deal and we'll fix it for next releases.

**Comment by menkej** [comment]
> I noticed that 1.7.1 GH release does not have items from prev non stable releases, e.g. 1.7.1rc1. Not a big deal and we'll fix it for next releases.

Which items do you mean? I tagged master, so everything on master should go in...

**Comment by AndreyNikiforov** [comment]
@menkej here are my thoughts on versioning and release info. It is my understanding that most projects work this way.

Primary focus is on user of the stable version of the icloudpd -- they are the majority. They come to the web site/dockerhub/pypi and should be able to:
- quickly understand purpose and behavior of the product
- access/use product
- assess liveness of the project

For them non stable versions are addition to the signal for liveness, nothing more. That means they will filter out non-stable info most of the time. That is why all stable versions should have change log from previous **stable** version (==accumulate all non stable versions in between). Dockerhub latest should be stable only too.

Smaller group of users of icloudpd are those how are testing non-stable versions. Until recently, this project did not have non stable versions at all. All non stable versions should be on "parallel" lineage to stable -- show change log between each other. First non stable after stable release will show change log from stable of course. Dockerhub latest should not be updated for non stable versions.

Let's continue discussion until we all are on the same page and agree on release/versioning of the icloudpd.

**Comment by menkej** [comment]
I totally agree.

> That is why all stable versions should have change log from previous stable version (==accumulate all non stable versions in between)

exactly.

Dockerhub and pypi (I think) handled rc-releases as expected and did not tag them with "latest"l Anyways, I think we don't need non-stable releases at all. I don't think we'll push out that big changes anyways (even though base.py needs to be split up as it is way to big). We're not building the next great OS or something... I just did an rc as you mentioned that you wanted to try the automatic release on an rc.

> All non stable versions should be on "parallel" lineage to stable  [...] Dockerhub latest should not be updated for non stable versions.

Agreed. If we happen to have, p.e a big refactoring branch, we could manually release - only on GitHub I suggest.

**Comment by ndbroadbent** [comment]
> By the way: If it happens that we push a release we want to remove later I'll need access with my login (or the real login-data) to dockerhub/pypi. Could you set me up there, @ndbroadbent ?

Sure happy to do that! Please provide your username for dockerhub/pypi and I can add you there as well

**Comment by menkej** [comment]
> Sure happy to do that! Please provide your username for dockerhub/pypi and I can add you there as well

Thank you! My account is joersch on both.

**Comment by ndbroadbent** [comment]
@menkej Done! @AndreyNikiforov please let me know your usernames and I would be happy to add you as well

**Comment by Felsaspalt** [comment]
I don't want to get this mail anymore, unsubscribing but still this
happenening

2020年11月23日(月) 1:54 Andrey Nikiforov <notifications@github.com>:

**Comment by metahnetoutage** [comment]
Google how to remove self from notifications of GitHub. You receive because
you replied or used to be part of discussion thread.
