### ISSUE TITLE
“ All photos have been downloaded!” But only downloads 1 file

### ISSUE THREAD

**Issue by woopiepoopie** [icloud-photos-downloader/icloud_photos_downloader#240]
Hi, So i am referencing this [issue](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/167
). I updated to 1.7.1 and also created created an album with every file I have and call it todo 
Then I ran:
`C:\Users\PCserver>icloudpd -d Q:\Pictures —album todo -u rpandula@uh.edu -p ******** `

And it worked! I have all my files locally and I am very happy about it. I wanted to start automating this process so it runs every day. I used the following command, which removes the album requirement and adds a recent 100, thinking I can this every morning.

`C:\Users\PCserver>icloudpd -d Q:\Pictures --recent 100 -u rpandula@uh.edu -p ********`

```
2020-11-22 00:16:12 DEBUG    Authenticating...
2020-11-22 00:16:15 DEBUG    Looking up all photos and videos from album All Photos...
2020-11-22 00:16:15 INFO     Downloading 100 original photos and videos to Q:\Pictures ...
Q:\Pictures\2019\11\16\IMG_0535.MOV already exists.:   1%|4                                            | 1/100 [00:00<00:44,  2.22it/s]
2020-11-22 00:16:15 INFO     All photos have been downloaded!
```

But it goes back to downloading one random movie and then stops and I haven’t been able to figure it out. Is there a verbose mode or a way to find the logs so I can provide you the info you need? 

Thank you for your time and your tool has been a game changer for my workflow

**Comment by johnny2678** [comment]
First, thanks for this.  I'm seeing this too.  icloudpd keeps trying to download the same file when I have hundreds in iCloud.
```
/ # icloudpd --directory /home/user/iCloud --username jo***.com -a 'All Photos'
2020-11-24 08:00:14 DEBUG    Authenticating...
iCloud Password: 
2020-11-24 08:00:19 DEBUG    Looking up all photos and videos from album All Photos...
2020-11-24 08:00:19 INFO     Downloading 4 original photos and videos to /home/user/iCloud ...
/home/user/iCloud/2018/04/20/IMG_0001.MOV already exists.: 100%|################################################################################################################################################################################| 4/4 [00:00<00:00,  7.62it/s]
2020-11-24 08:00:19 INFO     All photos have been downloaded!
```

Tried adding the `--no-status-bar` as suggested [here](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/167) with the following result... only 4-5 files:
```
/ # icloudpd --directory /home/user/iCloud --username jo***.com --no-progress-bar
2020-11-24 08:01:43 DEBUG    Authenticating...
iCloud Password: 
2020-11-24 08:01:48 DEBUG    Looking up all photos and videos from album All Photos...
2020-11-24 08:01:48 INFO     Downloading 4 original photos and videos to /home/user/iCloud ...
2020-11-24 08:01:48 INFO     /home/user/iCloud/2020/06/24/IMG_0001.MOV already exists.
2020-11-24 08:01:48 INFO     /home/user/iCloud/2019/01/20/IMG_5463.png already exists.
2020-11-24 08:01:48 INFO     /home/user/iCloud/2018/12/28/IMG_5958.JPG already exists.
2020-11-24 08:01:48 INFO     /home/user/iCloud/2018/04/20/IMG_0001.JPG already exists.
2020-11-24 08:01:48 INFO     /home/user/iCloud/2018/04/20/IMG_0001.MOV already exists.
2020-11-24 08:01:48 INFO     All photos have been downloaded!
```

have also tried specifying the `recent` command to return 100 files but it grabs the same random 4-5.  Using the `-l` command does list out my iCloud albums, so I know it's able to read my iCloud photo structure.

Sorry if I'm missing something obvious.

**Comment by woopiepoopie** [comment]
@johnny2678 
So I figured it out, I think. 

I have a large library, 40k photos and have migrated from iPhoto many years ago. Through all this, I had a really messy album structure.I did some clean up and I had a few albums called "All Photos", I deleted all of them and now its working as it should!

I was running this command: 
<pre>
```
C:\Users\PCserver>icloudpd -d Q:\Pictures --recent 250 -u *** -p ***
2020-11-23 23:49:33 DEBUG    Authenticating...
2020-11-23 23:49:37 DEBUG    Looking up all photos and videos from <b>album All Photos</b> ...
</pre>


So by default, it is looking for an album called "All Photos" and downloading from there, if there is no album with that name, then it will download literally, all photos.

**Comment by johnny2678** [comment]
wait, starting to feel silly.  Does this app work on 'My Photo Streams'?  Or just iCloud photos?

I don't have iCloud photos enabled.  Made the assumption this worked on photo streams based on the Unraid Community Apps docker description:

![Screen Shot 2020-11-24 at 11 04 47 AM](https://user-images.githubusercontent.com/8219743/100119528-f485df00-2e44-11eb-841f-b5e07e442404.png)

If it only works on iCloud photos, is there a way to automatically delete old photos from iCloud to stay under the 5GB free limit?  Looks like the `auto-delete` option only deletes photos from the Recently Deleted folder

**Comment by menkej** [comment]
This script downloads photo albums respectively "All Photos" from iCloud - excluding shared albums. You understood 'auto-delete' correctly. We do not have an option to delete photos right now. This is "on purpose" as the idea of this script is mainly "backup" of (or exit strategy from...) Photos saved in iCloud.

**Comment by woopiepoopie** [comment]
Ah, I am not sure. I only use iCloud Photos.

I assume Photo Streams is an album? Your plan seems like a good way to skirt around the free iCloud storage space limit but probably requires a separate issue to be opened. I am going to close this one so so you can explain your use case in a new one.

**Comment by menkej** [comment]
> So by default, it is looking for an album called "All Photos" and downloading from there, if there is no album with that name, then it will download literally, all photos.

This is exactly the case at the moment.

**Comment by johnny2678** [comment]
Thanks for the response @menkej .  The description of the Unraid community app threw me off.

However, curious if this could be modified to work on 'My Photo Streams'?  

This seems like a natural/seamless way to archive photos taken without uploading to iCloud since My Photo Streams already syncs the last 30days/1000photos that can be accessed by all devices signed into iCloud (including iCloudpd ).  

As long as you run iCloudpd in that timeframe you will be able to keep local backups of all your photos.

If possible, maybe save as a feature request?  Thanks for considering.
