### ISSUE TITLE
Download and Authenticating stuck after a few hundred photos. 

### ISSUE THREAD

**Issue by barning** [icloud-photos-downloader/icloud_photos_downloader#248]
## Overview
I have installed the downloader on a Raspberry Pi and use it with Screen. After a few hundred photos (about 300/4476) have been successfully downloaded, the download seems to stop.
After aborting and restarting, it stops at the step "Authenticating..." and can only be executed again successfully after a reboot.

## Steps to Reproduce
1. Start Download, detach the session with screen.
2. After some time reattach the session. Download is stuck.
3. Restart script

## Expected Behavior
Download is not stopping.

**Comment by barning** [comment]
Same thing is happening after 130 photos on a mac

**Comment by menkej** [comment]
Hi!
Which command line options do you use? Is there anything in the logs/output? Did you try without using screen?

regards
Jörg

**Comment by barning** [comment]
Hi
i use `icloudpd --directory . --username foo@bar.org --password foo -a Albumtitle`
it stucks everytime after some 300 picture or so.
I will try to run it outside of screen.

**Comment by barning** [comment]
Hi @menkej it seems to be working without screen. My workaround is now to login with vnc and start it there in the terminal.
Of course I would much rather just log in via ssh, give the raspberry the command and in a few days the photos would be downloaded 🙂

**Comment by boredazfcuk** [comment]
>I would much rather just log in via ssh, give the raspberry the command and in a few days the photos would be downloaded

Just modify your ssh command so that it runs in the background, like this:
```
icloudpd --directory . --username foo@bar.org --password foo -a Albumtitle &
```
or if you want to log all the output to a file to check later, change it to this:
```
 icloudpd --directory . --username foo@bar.org --password foo -a Albumtitle >/var/log/icloudpd.log 2>&1 &
```

**Comment by menkej** [comment]
Adding to @boredazfcuk 's comment:

This would also be my way to go but also use `nohup` to allow it to continue running if the session is closed. I also recommend using `--no-progress-bar` when run non-interactive. To sum up:

`nohup icloudpd --directory . --username foo@bar.org --password foo -a Albumtitle --no-progress-bar &`

Output will automagically be written into `nohup.out`. I assume that this solves your issue and we're just having a problem with `screen`, which is the case for quite some other CLI-tools. I'd close this issue with this solution. Feel free to reopen with additional info if this not ok for you.
