### ISSUE TITLE
Docker image aborts with OCI runtime error: "exec: \"-v\": executable file not found in $PATH": unknown

### ISSUE THREAD

**Issue by jdahdah** [icloud-photos-downloader/icloud_photos_downloader#250]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )

First-time user here. I'm unable to start the Docker image on MacOS Big Sur v11.0.1 (20B29).

## Steps to Reproduce
I'm running the following command according to the README. I adapted just a few things like the Photos directory and the timezone.

```
docker run -it --rm --name icloud -v $(pwd)/PhotosTest:/data icloudpd/icloudpd:latest \
    -v $(pwd)/cookies:/cookies \
    -e TZ=Europe/Berlin \
    icloudpd --directory /data \
    --cookie-directory /cookies \
    --folder-structure {:%Y/%Y-%m-%d} \
    --username REDACTED \
    --password REDACTED \
    --size original \
    --recent 20 \
    --auto-delete
```

## Expected Behavior
I would expect that it runs.

## Actual Behavior
Instead of running, it aborts with the following error:

> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"-v\": executable file not found in $PATH": unknown.

## Context
[NOTE]: # ( Give us any additional information you may have. )
I have very little experience with Docker, in fact I started learning it just now so that I can run this on my Synology NAS. Apologies if I am missing something very obvious.

**Comment by jdahdah** [comment]
@menkej  Thanks for retagging, but this is indeed a bug. It turns out that the README gives incorrect instructions. The CLI command does not follow the order specified by the [Docker docs](https://docs.docker.com/engine/reference/commandline/run/) for `docker run`, which caused the error message.

The correct order is:

```
docker run [OPTIONS] IMAGE [COMMAND] [ARG…]
```

The [README](https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/README.md) specifies:

```
docker run [OPTIONS] IMAGE [MORE OPTIONS] [COMMAND] [ARG…]
```

Applied to the README's command, it should look like this:

```
docker run -it --rm --name icloud \
    -v $(pwd)/Photos:/data \
    -v $(pwd)/cookies:/cookies \
    -e TZ= America/Los_Angeles \
    icloudpd/icloudpd:latest \
    icloudpd --directory /data \
    --cookie-directory /cookies \
    --folder-structure {:%Y/%Y-%m-%d} \
    --username testuser@example.com \
    --password pass1234 \
    --size original \
    --recent 500 \
    --auto-delete
```

Aaaaand it works now. Note that the `-v` and `-e` options are now before the image name.

I'll create a PR.

**Comment by menkej** [comment]
Ok, so you're referring to a mistake in the documentation? Then it is indeed a bug
