### ISSUE TITLE
Apple legal department

### ISSUE THREAD

**Issue by duckheadsoftware** [icloud-photos-downloader/icloud_photos_downloader#265]
## Summary
I created an app using the API and published it to the App Store, within 3 days I was shutdown by Apple's legal team.

## Context
They complained to Microsoft on several areas, but the main one being the "use of iCloud IP". Microsoft then warned me about copyright and IP fractions and threatened to close my developer account - ouch. It's all sorted now as I removed the app and I just got a warning.

## iCloud.com/API official support
Do we know if Apple officially support apps using the iCloud API in any way? (their legal team wouldn't answer my questions on this and just repeated the violation of "use of iCloud IP")

Thanks.

**Comment by menkej** [comment]
This project just uses a third party lib ([pyicloud](https://github.com/picklepete/pyicloud)). I'm not sure which API you're talking about. If you're using the same lib you might contact pyicloud project. I can't answer your question. Sorry.
