### ISSUE TITLE
Authentication stops working when logged off from icloud

### ISSUE THREAD

**Issue by caroso-de** [icloud-photos-downloader/icloud_photos_downloader#271]
Starting about an hour ago, authentication is only successful if I'm logged in into icloud at the same time.

I'm not sure if I'm missing some iCloud settings or using wrong parameters, so I'm not making this a bug report. 
However starting roughly an hour ago, the scirpt will only authenticate successfully if I'm logged in into icloud, otherwise it says "ACCESS_DENIED". This is reproducible.

`2020-12-26 10:26:45 DEBUG    Authenticating...
private db access disabled for this account.  Please wait a few minutes then try again.  The remote servers might be trying to throttle requests. (ACCESS_DENIED)`

I'm running the downloader under wsl2/Debian inside Docker on a Windows host, here's how i call the script:

`docker run -it --rm --name icloud \
    -v $(pwd)/Photos:/data \
    -v $(pwd)/cookies:/cookies \
    -e TZ=Europe/Berlin \
    icloudpd/icloudpd:latest \
    icloudpd --directory /data \
    --cookie-directory /cookies \
    --folder-structure {:%Y/%Y-%m-%d} \
    --username $username \
    --password $password \
    --size original \
    --recent 100 \
    --auto-delete`

Thanks for making this great tool available!

**Comment by boredazfcuk** [comment]
I can confirm this too. All three containers I have started doing this on the 25th at the exact same time.
I presumed it’s an Apple side “fix” or just something to do with increased load on Christmas Day.

**Comment by caroso-de** [comment]
Tahnks for the feedback. 

Too bad, let's hope it's just a temporary thing to mitigate load issues.

**Comment by boredazfcuk** [comment]
Update: I've fired my containers back up today and the issue no longer occurs.

**Comment by caroso-de** [comment]
Same here, I'm glad this was only a temporary issue.
