### ISSUE TITLE
problem with drive

### ISSUE THREAD

**Issue by eprieto-lam** [icloud-photos-downloader/icloud_photos_downloader#284]
Sorry wrong repository...

## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
I try to acces to my drive on icloud. The error message back to the normal routine call is:

AttributeError: 'PyiCloudService' object has no attribute 'drive'

My call is simply:

ListIcloud= api.drive.dir()

Photos, Files are running well, only drive is not
I guess this is a problem of installation. I spend few times to find why butno success

could you help

Thanks

**Comment by AndreyNikiforov** [comment]
@eprieto-lam icloud photos downloader is a command line utility that does not support operations with iCloud Drive, only iCloud Photos.

If you are using https://github.com/picklepete/pyicloud library to write your own code to access iCloud Drive, post your question it that project.
