### ISSUE TITLE
code execution error

### ISSUE THREAD

**Issue by zhangbaiquan** [icloud-photos-downloader/icloud_photos_downloader#312]
![image](https://user-images.githubusercontent.com/22684684/110605604-3eac8980-81c4-11eb-9915-ad04358627c7.png)
code execution error, is there a problem in my environment?

**Comment by larsschwegmann** [comment]
It asked for an index in the list of 2FA devices, which only contains the index 0. You typed "912595", which i guess was your 2FA code? try typing in "0" to select your 2FA device first.

**Comment by zhangbaiquan** [comment]
Thank you, I misunderstood it at first. This is no problem. The project is very useful. Thank you for your open source contribution.
