### ISSUE TITLE
Option to Automatically Delete Downloaded Photos

### ISSUE THREAD

**Issue by sabaatworld** [icloud-photos-downloader/icloud_photos_downloader#314]
## Summary
Please consider adding the ability to delete downloaded photos. When this option is used, the program would automatically delete the original assets from iCloud after downloading them.

## Context
This would be very useful for people like me who would like to backup all their photos periodically to their computer. If my iCloud storage is full, all photos would not be backed up to iCloud and I would need to figure out the ones I've downloaded to my computer manually, and delete them to clear space.

With the delete option, I know that I would be deleting the ones which are already backed up, clearing space in my iCloud account without any manual intervention.

**Comment by ricmik** [comment]
Sounds dangerous. One thing is to re-download files from iCloud that has been deleted locally. 

But restoring thousands of photos and videos that has been deleted on iCloud.. is that even possible?

**Comment by sabaatworld** [comment]
Why would restoring be a concern? This option would be just for deleting the assets. They can be moved to the recycle bin where people can restore them if done by mistake.

**Comment by mooreandrew** [comment]
I've modified the app to do this. I added 2 flags:
--download-delete-age (defaults to 30 days)
--delete-if-downloaded (defaults to false)

If you want to see the code then it is here:
https://github.com/icloud-photos-downloader/icloud_photos_downloader/compare/master...mooreandrew:master

I've never had an issue with it being dangerous, iCloud Photos is quite safe as all this does it move it to the deleted folder, of which it is really simple to restore (just select all and click recover). 

This is how I got around the 5GB limit on iCloud.

**Comment by sabaatworld** [comment]
That's awesome! Thanks a lot!

**Comment by jniggemann** [comment]
Will this be available in the next release?

**Comment by aztttt** [comment]
I want to recover the deleted videos from recycled bin

**Comment by sabaatworld** [comment]
I pulled the code today to check out this option but I think its not merged into master yet. Is there something blocking the merge?

**Comment by christian1211** [comment]
> I've modified the app to do this. I added 2 flags: --download-delete-age (defaults to 30 days) --delete-if-downloaded (defaults to false)
> 
> If you want to see the code then it is here: [master...mooreandrew:master](https://github.com/icloud-photos-downloader/icloud_photos_downloader/compare/master...mooreandrew:master)
> 
> I've never had an issue with it being dangerous, iCloud Photos is quite safe as all this does it move it to the deleted folder, of which it is really simple to restore (just select all and click recover).
> 
> This is how I got around the 5GB limit on iCloud.

I just tried to implement your changes but I keep getting the error `Error: no such option: --delete-if-downloaded`.
Could you tell me if there is more to do besides modifying the files?

**Comment by boredazfcuk** [comment]
I've attempted to integrate this patch into my container, but it doesn't work correctly.

It doesn't see any of the photos in my (already downloaded) library and starts downloading them with `-original` appended to the file names. This would have duplicated my entire library had I not spotted it in time.

**Comment by AndreyNikiforov** [comment]
@sabaatworld v1.8.0 has this feature
