### ISSUE TITLE
Usage limit from Apple?

### ISSUE THREAD

**Issue by petebocken** [icloud-photos-downloader/icloud_photos_downloader#315]
Are we aware of any usage limits by Apple? Will you get timeouts if you run this command too many times in a given period?

For example, if I setup a task to run this every hour to check and download new photos.

**Comment by AndreyNikiforov** [comment]
It is my understanding that Apple changing/tweaking their rules often and no official info exists

**Comment by djjudas21** [comment]
I have been running this every hour for weeks/months. It works fine except when the 2 factor auth expires.
