### ISSUE TITLE
Download all files in a single directory

### ISSUE THREAD

**Issue by mr337** [icloud-photos-downloader/icloud_photos_downloader#326]
## Summary
Is it possible to download all the images and movies into a single directory? I have tried experimenting with the ` --folder-structure <folder_structure>` arg with no luck. A few things I have tried is an empty string, no argument, using the `%f` to represent just the file name, tried `{}`. Everything so far stores in a directory.

## Context
Our NAS has everything stored in a single directory. We are trying to match that.

**Comment by cdraf** [comment]
I had a quick peak at the source and you can use `--folder-structure none` to place all images in a single dir.

**Comment by mr337** [comment]
That worked perfectly. Thanks!

**Comment by cdraf** [comment]
np
