### ISSUE TITLE
More than 10,000 images?

### ISSUE THREAD

**Issue by mr337** [icloud-photos-downloader/icloud_photos_downloader#328]
## Summary
Does anyone know the intended behavior for handling more than 10k photos or movies?

For example it looks like the iphone uses IMG_XXXX.JPG allowing from 0 to 9999. Looking at the download it seems that the iphone has rolled over so that IMG_0009.JPG I recently took and is not the original as stated in the icloud web UI from 3 years ago. 

What I fear is the downloader is possibly overwriting the file. I didn't notice any logs on duplicates as indicated in code.
https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/9af5a7445edc48c9c4ea9b6898b79eb443370a1c/icloudpd/base.py#L454

## Context
This may be self inflicted as I wanted to download all the files in a single directory, https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/326

I may separate them out by year to ensure this doesn't happen but wanted to double check.

**Comment by AndreyNikiforov** [comment]
iCloudPD has deduplication logic that uses size of the image in addition to the path. Unless images from few year apart have exactly the same size, you should be fine downloading all into the same folder.

**Comment by mr337** [comment]
Do you happen to know how it will handle two images of the same name. For example when testing using IMG_0009.jpg it rewrote the file with the latest images of that name, thus I lost the image from 2017.

**Comment by AndreyNikiforov** [comment]
If you have two images IMG_0009.jpg from different dates and different in size, then:
- with folder structure set to YYYY/MM/DD files will end up in different folder under IMG_0009.jpg
- with folder structure set to `none` all files are copied into one destination folder and your files will have different names: IMG_0009.jpg and IMG_0009-12345.jpg where `12345` is the size in bytes of the second file.

**Comment by mr337** [comment]
Oh wow that is perfect. I didn't notice that when the folder dir is set to `none`. Thanks for the info!
