### ISSUE TITLE
Deleting photos from local filesystem?

### ISSUE THREAD

**Issue by SecurityJon** [icloud-photos-downloader/icloud_photos_downloader#330]
## Overview
Local files were deleted once removed from iCloud, this is counter intuitive for the usage of the tool

## Expected Behavior
Local files should not be deleted when removed from iCloud.

## Actual Behavior
Local files were deleted once removed from iCloud

## Context
I only have 5GB of space on my Apple account, and use a process of 'clearing out' my photos on my iphone once they've been downloaded with icloud-photo-downloader to a NAS.

Today, I realised that I didn't have enough iCloud space free to upload new photos, so I went through the process of downloading all images stored in icloud to the NAS (worked successfully) and then deleted them (first through my phone, and then through the icloud web interface).

There was now enough space to upload recent photos into icloud, and I re-ran the icloud_photos_downloader tool, expecting the recent photos to be downloaded from icloud.

Instead, the tool seemed to 'sync' my local filesystem and icloud, and wiped out a years worth of photos that were stored on my NAS.

Arguments used:

icloudpd --username XXXX --password XXXX --auto-delete -d "<directory>"

**Comment by menkej** [comment]
Hi @SecurityJon !
This is exactly what `--auto-delete` does. It deletes photos you have deleted in your iCloud locally. If you do not use that option you should have the behavior you want...

cheers, Jörg

**Comment by SecurityJon** [comment]
Had a look through the code and I see this is the intended usage for the "--auto-delete" option supplied, however this is not clear from the README.md file that this what will occur

**Comment by SecurityJon** [comment]
Ah, you beat me to it with your reply :)

**Comment by menkej** [comment]
> Had a look through the code and I see this is the intended usage for the "--auto-delete" option supplied, however this is not clear from the README.md file that this what will occur

Feel free to suggest a better description! ;-)
