### ISSUE TITLE
Hi. I send `MTPMessages_Search` request with `MTPmessages_Search::Flag::f_from_id` flag and a userID as `from_id` but it returns `USER_ID_INVALID` error. It's ok when I send channeID as `from_id`. Does it only work with channels?

### ISSUE THREAD

**Issue by samkiwi6912** [icloud-photos-downloader/icloud_photos_downloader#343]
Hi. I send `MTPMessages_Search` request with `MTPmessages_Search::Flag::f_from_id` flag and a userID as `from_id` but it returns `USER_ID_INVALID` error. It's ok when I send channeID as `from_id`. Does it only work with channels?

__Originally posted by @0xNima in https://github.com/telegramdesktop/tdesktop/issues/16464__

**Comment by AndreyNikiforov** [comment]
telegram is not supported. closing.
