### ISSUE TITLE
[Latest Edits] Doesn't download edited HEIC files or AAE sidecar files

### ISSUE THREAD

**Issue by angadsingh** [icloud-photos-downloader/icloud_photos_downloader#350]
## Summary
This tool downloads the original HEIC file only, and neither the edited HEIC file, nor the AAE file (which contains edits in XML format).

Go to iCloud photos in the browser - go to an edited photo, long press the download button - download unmodified original. This is the only file that this tool downloads.

But now go to the Photos app on mac, go to a photo synced from icloud, file > export unmodified original. It will save the HEIC as well as the AAE file:
![F5EE5A94-6BAB-40D7-A4B3-C43A1281635B](https://user-images.githubusercontent.com/1623026/125411802-e38ddc00-e3db-11eb-9c81-5958de2d683f.png)

On the iphone, you can see all 3 files:
![5A5D551C-A995-422B-888B-8647B77E8094](https://user-images.githubusercontent.com/1623026/125411750-d40e9300-e3db-11eb-9a44-326e6ee9a203.png)

## Context
This is an expected feature. without this, all edits to the photo are lost.

**Comment by AndreyNikiforov** [comment]
Agree, that functionality is expected but missing. 

What is the use fo AAE files? I suspect we can download edited version of the asset as "main" and original if no edits exist (instead of two or even tree files).

**Comment by angadsingh** [comment]
AAE files along with the original HEIC, allows one to import it back to the iphone or photos app on mac to change the edit, since it contains metadata about the edits in XML format. Storing the edited file + original not only is duplicate storage, but will not allow one to change the edit in the future in the photos app on either platform.

**Comment by AndreyNikiforov** [comment]
To confirm my understanding:
- AAE + Original when uploaded to iPhone or Mac Photos allows changes to the previous edits
- Uploading to iPhone or Mac just edited HEIC will allow edits forward, but not he changes to the previous edits

If that is correct, then:
- AAE + Original may be needed to those who plan to change their edits or upload assets back to iCloud (e.g. diff account)
- Edited file will be needed to view latest edits on any platform other than Apple (as AAE is not supported by any other tool AFAIK)

**Comment by angadsingh** [comment]
all of the above is absolutely correct. some references:
https://apple.stackexchange.com/questions/298320/how-to-view-a-photo-marked-up-in-ios-on-my-laptop-aae-file/298324#298324?newreg=580e501fff9e46c993bbf58acd1f6fd7
https://discussions.apple.com/thread/8262581
http://asktimgrey.com/2019/08/20/mysterious-aae-files/

the situation becomes more serious as all portrait photos are treated as edits. currently icloud photo downloader only retains the original HEIC, without the portrait effect, since it does not have neither the AAE nor the edited HEIC file with the portrait bokeh. so fulfilling this feature request is critical to a core photography style and not just for users wanting to retain edits.

**Comment by angadsingh** [comment]
we should give an option to the user if they want to download (a) original HEIC (b) edited HEIC (c) edited JPEG (d) AAE files - and any combination of these. AAE files allows non-destructive edits, so the user can import them back to photos and change their edits.

**Comment by hirenr** [comment]
There is another need why this should be done.

My iPhone is set to take 16:9 resolution photos instead of 4:3 format. iCloud photos, Photos.app on Mac and Photos on iPhone all automatically show 16:9 for photos taken after the setting change. My assumption was that the iPhone now takes and stores the photos in the new resolution.

HOWEVER, looks like, iPhone ALWAYS takes 4:3 format and applies and post-capture edit and crops of top/bottom of the photo to make it 16:9. Same for Live Photos (video).

I found this out, when I used icloudpd to download all my photos. And ALL of them turned out to be 4:3 instead of 16:9.

**Comment by prawnPANDI** [comment]
Any update on this? Anyone working on it?

**Comment by interpretor** [comment]
@AndreyNikiforov I would mark this as critical, because photos are not saved as they appear in iCloud. This gets more serious with the "incorrect" saving of the portrait or landscape photos.

**Comment by AndreyNikiforov** [comment]
1.19.0 can download adjusted files (edits, portraits etc)
