### ISSUE TITLE
Option to delete item after successful download

### ISSUE THREAD

**Issue by dzg** [icloud-photos-downloader/icloud_photos_downloader#368]
I primarily use this to move stuff from iCloud over to Google Drive/Photos.
So it would be great to have an option to delete every item after it successfully downloads. (I assume it would get moved to the 'deleted item's folder on iCloud.)

Thanks!

**Comment by rcmpayne** [comment]
+1

**Comment by hurricane-dorian** [comment]
This would be great for those of us with limited space in our devices.

**Comment by RDKRACZ** [comment]
I'm in huge need of this feature since I just downloaded whole 5GB of media to move it to a new account but I need to delete it from the old one too...

**Comment by Jonnypleasehelp** [comment]
Please no I have lost a lot of valuable stufff
