### ISSUE TITLE
Does this program work as sync of as a backup software?

### ISSUE THREAD

**Issue by nihelmasell** [icloud-photos-downloader/icloud_photos_downloader#371]
## Summary
I want to know if this program propagates deletions from the cloud (syncs) or if it doesn’t (keeps the local files untouched even if I delete them from iCloud).

**Comment by AndreyNikiforov** [comment]
there is an `--auto-delete` flag that will remove local files if they are removed from iCloud. See https://github.com/icloud-photos-downloader/icloud_photos_downloader#usage
