### ISSUE TITLE
Invalid letters in filename will download failed

### ISSUE THREAD

**Issue by piscesvivian** [icloud-photos-downloader/icloud_photos_downloader#378]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Error log, with save a mp4 file, which has `:` in filename on windows
```
IOError while writing file to E:\icloud-2021-09-06\2021\09\03\1034:4677447615184994.mp4! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...
```

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Tiktok saved video download failed
2. url has invalid letters on windows

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

## Context
[NOTE]: # ( Give us any additional information you may have. )

**Comment by MrDecepticon** [comment]
I am assuming the error message does not include the ! at the end and this is in the filename?

`2021-12-01 13:57:12 ERROR    IOError while writing file to /home/user/iCloud/2021/01/31/IMG_2184.HEIC! You might have run out of disk space, or the file might be too large for your OS. Skipping this file...`

**Comment by piscesvivian** [comment]
```
logger.error(
--
92 | "IOError while writing file to %s! "
93 | "You might have run out of disk space, or the file "

```

! is a log message, filename `1034:4677447615184994.mp4` is illegal on windows. it will raise a IOError
