### ISSUE TITLE
Error Message while trying out for the first time

### ISSUE THREAD

**Issue by lost-while-translating** [icloud-photos-downloader/icloud_photos_downloader#390]
Hi,
I installed the script like shown on github page via pip.
But when calling, I get this message:
`C:\Users\frank>icloudpd -d D:\icloudPD\Frank -u wonttell@gmail.com -p falschabersorichtig
Traceback (most recent call last):
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\Scripts\icloudpd.exe\__main__.py", line 4, in <module>
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\icloudpd\base.py", line 17, in <module>
    from pyicloud_ipd.exceptions import PyiCloudAPIResponseError
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\__init__.py", line 2, in <module>
    from pyicloud_ipd.base import PyiCloudService
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\base.py", line 19, in <module>
    from pyicloud_ipd.services import (
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\services\__init__.py", line 7, in <module>
    from pyicloud_ipd.services.account import AccountService
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\services\account.py", line 5, in <module>
    from pyicloud_ipd.utils import underscore_to_camelcase
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\pyicloud_ipd\utils.py", line 2, in <module>
    import keyring
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\core.py", line 14, in <module>
    from . import backend
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\backend.py", line 18, in <module>
    from .util import properties
  File "C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\site-packages\keyring\util\properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (C:\Users\frank\AppData\Local\Programs\Python\Python310\lib\collections\__init__.py)
`
Any hints what I could check or install? Looks like there is something around the crypting while login not in place?
Version of python:
C:\Users\frank>python --version
Python 3.10.0

Anything else I should put in here?

Thanks a lot

Frank

**Comment by boredazfcuk** [comment]
Try downgrading to Python 3.8.

I found it broke when I upgraded to Python 3.9 (https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/353) and it hasn't been updated since then. I should imagine it's incompatible with Python 3.10 too.

**Comment by lost-while-translating** [comment]
Thanks for the idea. I just face a minor obstacle:
According to the release calendar specified in PEP 569, Python 3.8 is now in the "security fixes only" stage of its life cycle: 3.8 branch only accepts security fixes and releases of those are made irregularly in source-only form until October 2024. Python 3.8 isn't receiving regular bug fixes anymore, and binary installers are no longer provided for it. Python 3.8.10 was the last full bugfix release of Python 3.8 with binary installers.

Will try to go further back.

thank you

**Comment by lost-while-translating** [comment]
Thanks a lot. I found 3.8.9 Installation package and after installing and again installing icloudpd it now runs.

Your hint was exactly what worked.

Frank

**Comment by lost-while-translating** [comment]
Summary: there seems to exist issues with python version 3.9+ at least on Windows 64bit
Downgrading to 3.8.9 and installing icloudpd via pip again under 3.8.9 is a working workaround.

**Comment by boredazfcuk** [comment]
I'm running this in an Alpine Linux container so it's not just Windows.

**Comment by joe00dev** [comment]
Just upgraded to Fedora 35, running Python 3.10. Can confirm mine broke too, used to work on previous versions of Fedora / Python. I get the same "ImportError: cannot import name 'Callable' from 'collections'" message.

**Comment by djjudas21** [comment]
Another Fedora 35 user here, seeing the same symptoms. I propose renaming this issue to "Python 3.9 support" as that seems to be the crux of the issue.

As a workaround, it is possible to run `icloudpd` in Docker as [documented in the README](https://github.com/icloud-photos-downloader/icloud_photos_downloader#docker), but bear in mind you'll need to run as root for the bind mounts to work. So you'll probably end up with your photos owned by root.

**Comment by djjudas21** [comment]
Hi there, any update on this issue?

**Comment by boredazfcuk** [comment]
You’re probably best off trying my container as it will handle the permissions issue you mentioned. It’s on dockerhub as boredazfcuk/icloupd

**Comment by AndreyNikiforov** [comment]
Last time I checked (sometime back) there were issues in upstream packages with Python 3.9+ -- that was the blocker for supporting 3.9+ in icloudpd. If they are resolved, we may be able to bump supported Python version. Need volunteers for for this research and testing effort.

**Comment by boredazfcuk** [comment]
I started learning Python during lockdown, but got 6 hours into a beginners course before it fell by the wayside. Now I’m struggling to keep up with work as they want to implement all the stuff missed in 19/20, plus do stuff for 21.

I won’t have time to learn Python and debug code, but should be able to help with testing any PRs.

**Comment by joe00dev** [comment]
I'm still somewhat of a noob with both Python and Linux, but I installed Python 3.8 on my Fedora 35, and my icloud downloader is working now. Honestly I was playing around with a lot of things and I can't pinpoint exactly how I fixed it.. but in any case it's working for me now.

**Comment by menkej** [comment]
If I remember right there were mainly issues with our old pyicloud base library fork. Unfortunately I could not finish bringing this project back to the upstream version. I'm sunk in our house building project. I hope I can find some time during xmas for digging into that again. Till then please stick with an older python version.

**Comment by Toxsch** [comment]
Another workaround, just simple upgrading the **keyring** can also works fine for me, win10+python3.10
But I am curious why this is no issue for python 3.8? Per my understanding, this error should be encountered on Python 3.3 and above.

**Comment by jfburdet** [comment]
I made the following on my Arch Linux server to make things work again : 

```
cd ~/photo_backup
rm -rf .venv
yay -S python38
virtualenv --python=/usr/bin/python3.8 .venv
.venv/bin/pip install icloudpd
.venv/bin/icloudpd --until-found $RECENT -d ./photos/mickey -u mickey@disney.com --no-progress-bar --log-level info
```

**Comment by fmsonic** [comment]
> 



> Another workaround, just simple upgrading the **keyring** can also works fine for me, win10+python3.10 But I am curious why this is no issue for python 3.8? Per my understanding, this error should be encountered on Python 3.3 and above.

Can you tell me how?

**Comment by boredazfcuk** [comment]
@Toxsch

Don't leave us hanging... how did you upgrade the keyring?

**Comment by boredazfcuk** [comment]
@JiangXL

Thanks, I'd already tried that, but it complained about unmet dependencies.

I've tried keyring 23.5.0 on Python 3.9 and 3.10 and get the same error as this issue. I've no idea how @Toxsch has got this working.

**Comment by w1zz4** [comment]
You should look at https://github.com/picklepete/pyicloud, he fixed this issue in release 1.0.0

**Comment by sinnerlolqt** [comment]
Been trying to remove myself for months still having problems! Please remove me!

Thank you

**Comment by paul** [comment]
*Note* I know nothing about python development, but here's how I got this working for my simple use-case on Fedora 35:

1. Clone this repo
1. Edit `requirements.txt` to replace `pyicloud-ipd` with `pyicloud`, and updated some other versions that pip was whining about. I've pasted the full diff below.
1. Ran `pytest` to see what happened, got a handful of failures. Decided to try anyway.
1. Did `pip install .` to install my local version.
1. Ran my script that downloads my photos from iCloud. It seems to have worked. 

The test failures seemed to be around what to do when the session expires, but I already had a working one from before I upgraded, so we'll have to see what happens when this one expires.

```diff
diff --git a/requirements.txt b/requirements.txt
index b5b6bd4..7b735f6 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -1,7 +1,7 @@
-pyicloud_ipd==0.10.1
+pyicloud>=1.0.0
 schema==0.7.4
-click==6.7
-python_dateutil==2.8.2
+click>=7.1.2
+python_dateutil>=2.8.2
 requests>=2.20.0
-tqdm==4.62.0
-piexif==1.1.3
+tqdm>=4.62.0
+piexif>=1.1.3
```

**Comment by Toxsch** [comment]
> Thanks, I'd already tried that, but it complained about unmet dependencies.
> 
> I've tried keyring 23.5.0 on Python 3.9 and 3.10 and get the same error as this issue. I've no idea how @Toxsch has got this working.

Yes, due to the version required of pyicloud-ipd, it's impossible to update keyring directly.
I hacked the meta file of pyicloud-ipd(it's locate in `%python_path%/site-packages\pyicloud_ipd-0.10.1.dist-info\METADATA`) as below:
```
# Requires-Dist: keyring (<9.0,>=8.0) <-- comment this line, modify to below
Requires-Dist: keyring (>=8.0)
```
Then update keyring with the command `pip install --upgrade keyring`

**Comment by AndreyNikiforov** [comment]
icloudpd v1.8.0+ has updated dependencies and works with later versions of python. Pls see if latest version solves your problem and reopen the issue if it does not.
