### ISSUE TITLE
Minor readme typo - icloudpd.py: command not found. icloudpd works.

### ISSUE THREAD

**Issue by RDKRACZ** [icloud-photos-downloader/icloud_photos_downloader#405]
In the usage section the readme says to run `icloudpd.py` which is not found. Below there is an example that uses `icloudpd` command.

**Comment by menkej** [comment]
Hey! You're right. I can say: I put that error there on purpose... ;-) Actually this happens when you run the python script directly in dev environment and copy/paste the help output to README... Need to come up with a better process here...
