### ISSUE TITLE
macOS cron cannot find icloudpd

### ISSUE THREAD

**Issue by petebocken** [icloud-photos-downloader/icloud_photos_downloader#407]
I can run icloudpd from terminal just fine, but when add it to crontab, it reports "icloudpd: command not found" when it tries to run. Do I need to put the full path to icloudpd on the disk in my script? What is the path?

**Comment by menkej** [comment]
Cron uses a different environment so, yes you need to provide the full path. You can use `pwd` to find out your working directory.

**Comment by menkej** [comment]
Ok. Your script... What exactly are you running? What is your crontab entry? How do you edit your crontab?

**Comment by menkej** [comment]
btw: pip installs icloudpd in `/usr/local/bin/icloudpd`

`$ type icloudpd`
`icloudpd is /usr/local/bin/icloudpd`

**Comment by petebocken** [comment]
> Ok. Your script... What exactly are you running? What is your crontab entry? How do you edit your crontab?

Here's my script:

```
#!/bin/bash

pgrep -f icloudpd && echo "icloudpd is already running." && exit

icloudpd --directory "path/to/download/folder" --username email@domain.com --folder-structure none
```

crontab, editing with "crontab -e"

`0 19 * * * "path/to/download/folder/icloudpd.sh" >> /path/to/cron.txt 2>&1`

**Comment by petebocken** [comment]
> btw: pip installs icloudpd in `/usr/local/bin/icloudpd`
> 
> `$ type icloudpd` `icloudpd is /usr/local/bin/icloudpd`

/usr/local/bin/ does not contain icloudpd for me.

**Comment by menkej** [comment]
> > btw: pip installs icloudpd in `/usr/local/bin/icloudpd`
> > `$ type icloudpd` `icloudpd is /usr/local/bin/icloudpd`
> 
> /usr/local/bin/ does not contain icloudpd for me.

did you try running `which icloudpd`?

**Comment by petebocken** [comment]
> did you try running `which icloudpd`?

It's in /opt/homebrew/bin/icloudpd


I updated the script:

```
#!/bin/bash

pgrep -f icloudpd && echo "icloudpd is already running." && exit

/opt/homebrew/bin/icloudpd --directory "path/to/download/folder" --username email@domain.com --folder-structure none
```

Now I'm getting:

```
2022-01-23 14:03:01 DEBUG    Authenticating...
iCloud Password: /opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/lib/python3.9/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.

Aborted!
```

I already have the password stored in keyring.

**Comment by menkej** [comment]
Try again running from command line and/or try using -p option in crontab. Maybe specifying `--cookie-directory` could help, too

**Comment by petebocken** [comment]
> Try again running from command line and/or try using -p option in crontab. Maybe specifying `--cookie-directory` could help, too

Running again from command line works fine.  Adding `--cookie-directory /Users/peter/.pyicloud` yielded same cron output as above. Adding -p option with the Apple password works when run with cron.

I'd prefer not having the password saved in the script and would rather utilize the keyring. Any other ideas why this wouldn't run from cron?

**Comment by petebocken** [comment]
I had tested using launchd instead previously and had issues getting it to work. I switched back to it now and I can remove the -p password and it runs fine with launchd.
