### ISSUE TITLE
i fixed the code to run with python 3.10

### ISSUE THREAD

**Issue by ghost** [icloud-photos-downloader/icloud_photos_downloader#425]
before i fix the `test use cases`, i want to make sure someone will take a look at the PR and merge the code. 

changes:
- removed  `--skip-videos` and   `--skip-live-photos`  switches because the `photo` object does not have the `item_type` property, so i removed lines 368 to 378 from https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/icloudpd/base.py
- code refactored from `pyicloud_ipd==0.10.1` to `pyicloud==1.0.0`

life test:
```
python icloudpd.py --username appleid@example.com --password 12345678 --directory /Volumes/photos    
2022-04-19 21:24:40 DEBUG    Authenticating...
2022-04-19 21:24:41 DEBUG    Looking up all photos and videos from album All Photos...    
2022-04-19 21:24:41 INFO     Downloading 123724 original photos and videos to /Volumes/photos ...
/Volumes/photos/IMG_0000.JPG already exists.: 100%|#####################################################################################| 123724/123724 [1:27:33<00:00, 23.55it/s]
2022-04-19 22:52:14 INFO     All photos have been downloaded!
```

**Comment by martin-juul** [comment]
Can you make a fork with the changes?

**Comment by scurvylogs** [comment]
of course.

**Comment by AndreyNikiforov** [comment]
@ghost is your switching off pyicloud fork is similar to #528 ?

**Comment by AndreyNikiforov** [comment]
We have support for python 3.7..3.11 in 1.8.0+
