### ISSUE TITLE
Option to download RAW files

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#428]
Somebody logged an issue requesting the feature named in the subject and added these details:

> When you shoot RAW+jpg on your DSLRs and import them into your photo library, either on Mac or iPad/iPhone, the pair will be recognized as one photo but two assets. and both are uploaded into iCloud.
> on iPad/iPhone and Mac, the photo will have a JPEG+RAW tag on the upper left hand.
> 
> this article should give you some idea
> [https://appleinsider.com/articles/21/02/23/how-to-use-raw-images-with-photos-app-on-the-mac]
> https://github.com/boredazfcuk/docker-icloudpd/issues/156

I think it would be a good feature to add and presumably wouldn't be too difficult to add an additional file type to download (or even prefer), if it exists on icloud.com

**Comment by Jonnypleasehelp** [comment]
Yes ok

**Comment by boredazfcuk** [comment]
Looks like this has been implemented at some point: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/662
