### ISSUE TITLE
I'm stuck in a 2FA problem 'two-step expired'

### ISSUE THREAD

**Issue by kmplngj** [icloud-photos-downloader/icloud_photos_downloader#430]
## Summary
I'm stuck in a 2FA problem.

I use icloudpd two backup two iCloud accounts on my Synology NAS. Each backup task also has its own (Linux) user on the NAS. Both Apple accounts use 2FA. Both worked fine sometime. Now one account backups normally and ask for the renew 2FA if needed. Perfect. The other also would need a new 2FA but the output I get from the command is

```
2022-05-03 10:00:03 DEBUG    Authenticating...
iCloud Password: 
2022-05-03 10:00:17 INFO     Sending 'two-step expired' notification via email...
```

and it does not ask to renew the 2FA.

I already tried to delete the cookie from .pyicloud. 

I run this command to download the images
```
icloudpd --directory /volume1/photo/iCloud/daggi \
-u foo@bar.com \
--auto-delete \
--smtp-username foo@bar.com \
--smtp-password xxxxx \
--smtp-host smtp.mail.me.com \
--smtp-port 587 \
--notification-email foo@bar.com
```

How could I renew the 2FA?

Thank for the help!

**Comment by Piccirello** [comment]
I'm experiencing this same issue. icloudpd prints "Sending 'two-step expired' notification via email..." and then immediately exits. I do receive the "Two step authentication has expired" email and the MFA prompt on my devices, but there's no ability to enter the MFA code. I've also tested with an app-specific password, which fails with the below error:

```sh
iCloud Password: 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/icloudpd/authentication.py", line 29, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 141, in __init__
    password = get_password_from_keyring(apple_id)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/utils.py", line 40, in get_password_from_keyring
    raise NoStoredPasswordAvailable(
pyicloud_ipd.exceptions.NoStoredPasswordAvailable: No pyicloud password for [REDACTED] could be found in the system keychain.  Use the `--store-in-keyring` command-line option for storing a password for this username.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 209, in authenticate
    req = self.session.post(
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 590, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 100, in request
    self._raise_error(code, reason)
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 122, in _raise_error
    raise api_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.8/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/icloudpd/base.py", line 255, in main
    icloud = authenticate(
  File "/usr/lib/python3.8/site-packages/icloudpd/authentication.py", line 36, in authenticate
    icloud = pyicloud_ipd.PyiCloudService(
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 193, in __init__
    self.authenticate()
  File "/usr/lib/python3.8/site-packages/pyicloud_ipd/base.py", line 216, in authenticate
    raise PyiCloudFailedLoginException(msg, error)
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))
```

**Comment by bandundu** [comment]
Hi for everyone having the same issue, I did a little of debugging and I found what's causing the problem here. I am not sure what the authors originally intended, but if you just want a quick (and possibly dirty) fix, do the following.

1. Open  `~/.local/lib/python3.10/site-packages/icloudpd/base.py` in the editor of your choice
2. On line 250 comment out the "raise_error_on_2sa" variable and just set it to false like so

![grafik](https://user-images.githubusercontent.com/41874924/189323333-a66dfa2f-b057-4199-9388-9b1c10cd4dfb.png)

You should then be prompted again to enter your 2FA Code etc.

Hope that helps and that someone actually fixes it in the repo.

**Comment by Jonnypleasehelp** [comment]
I can search for phone numbers

**Comment by AndreyNikiforov** [comment]
@kmplngj is it still an issue? Did you try the latest version of icloudpd? How are you running it (exe, docker, source; parameters)?

**Comment by AndreyNikiforov** [comment]
@Piccirello are you still seeing the issue with the latest version of the icloudpd? Pls specify which version and how are you running. TIA

**Comment by AndreyNikiforov** [comment]
> I get the same exact log messages as the OP. I removed the SMTP flags and then I was finally able to enter my 2FA code and begin downloading.

Makes sense. SMTP params are used with "unattended" execution (cron or `--watch-with-interval`) and there is no way to enter 2FA from console. User needs to run `icloudpd` without SMTP (and without cron/watch), enter 2FA, so that 2FA cookies are saved to the disk. Then restart "unattended" execution again.

**Comment by stevehammond68** [comment]
@AndreyNikiforov Thank you, was having this issue, and did not realized that the script is not "smart enough" to ask for the 2FA if the SMTP information is in the command. It worked fine after that.

**Comment by latonita** [comment]
@AndreyNikiforov I was using docker version for quite a while w/o any issues, but recently token got expired and I can't get new one.
```
docker run --rm --name icloud \
    -v /Backup/Photos:/data \
    -v /Backup/Cookies:/cookies \
    -e TZ=America/Los_Angeles \
    icloudpd/icloudpd:latest \
    icloudpd --directory /data \
    --cookie-directory /cookies \
    --folder-structure {:%Y/%Y-%m} \
    --set-exif-datetime \
    --username user@mail.com \
    --password password \
    --size original \
    --recent 500
```
And what I'm getting is 
```
2023-10-02 14:42:30 DEBUG    Authenticating...
2023-10-02 14:42:31 INFO     Two-step/two-factor authentication is required
  0: SMS to ********00
  1: Enter two-factor authentication code
Please choose an option: [0]: Aborted!
```
I have just updated an image to latest 1.16.2 and still have the same problem. Any ideas?

**Comment by latonita** [comment]
I solved it, sorry for spamming :) 
I missed -it in command line so i can have interactive shell. It works okay )
```
docker run -it --rm --name icloud \ ....
```
