### ISSUE TITLE
Docker linux/arm/v7 version

### ISSUE THREAD

**Issue by FrankHdf** [icloud-photos-downloader/icloud_photos_downloader#434]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Add a docker image for linux/arm/v7

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
Hi, I would like to use the docker image with LibreElec. If I try to add the image I get this:

docker pull icloudpd/icloudpd
Using default tag: latest
latest: Pulling from icloudpd/icloudpd
no matching manifest for linux/arm/v7 in the manifest list entries

It would be really great if it would be possible to use icloud_photos_downloader with LibreElec.

Thanks
Frank

**Comment by boredazfcuk** [comment]
I build my container for armv7: https://hub.docker.com/repository/docker/boredazfcuk/icloudpd

**Comment by FrankHdf** [comment]
Great, thanks a lot! This helped me greatly!

**Comment by AndreyNikiforov** [comment]
#567
