### ISSUE TITLE
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

### ISSUE THREAD

**Issue by rmpadilla** [icloud-photos-downloader/icloud_photos_downloader#435]
After entering the command at the terminal, I received the above error. Here is my input along with the output of the command:
icloudpd --directory ./Pictures \
           --username abc@123.com \
           --password ABCD1234 \
           --recent 500
Traceback (most recent call last):
  File "/usr/bin/icloudpd", line 5, in <module>
    from icloudpd.base import main
  File "/usr/lib/python3.10/site-packages/icloudpd/base.py", line 17, in <module>
    from pyicloud_ipd.exceptions import PyiCloudAPIResponseError
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/__init__.py", line 2, in <module>
    from pyicloud_ipd.base import PyiCloudService
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/base.py", line 19, in <module>
    from pyicloud_ipd.services import (
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/services/__init__.py", line 7, in <module>
    from pyicloud_ipd.services.account import AccountService
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/services/account.py", line 5, in <module>
    from pyicloud_ipd.utils import underscore_to_camelcase
  File "/usr/lib/python3.10/site-packages/pyicloud_ipd/utils.py", line 2, in <module>
    import keyring
  File "/usr/lib/python3.10/site-packages/keyring/__init__.py", line 6, in <module>
    from .core import (set_keyring, get_keyring, set_password, get_password,
  File "/usr/lib/python3.10/site-packages/keyring/core.py", line 14, in <module>
    from . import backend
  File "/usr/lib/python3.10/site-packages/keyring/backend.py", line 18, in <module>
    from .util import properties
  File "/usr/lib/python3.10/site-packages/keyring/util/properties.py", line 1, in <module>
    from collections import Callable
ImportError: cannot import name 'Callable' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

Can I please get help for this?  Thank you in advance.

**Comment by error426** [comment]
Try to change first line in /usr/lib/python3.10/site-packages/keyring/util/properties.py "from collections import Callable"
to  "from collections.abc import Callable".

**Comment by ibizaman** [comment]
This worked for me. Thanks!

**Comment by raleighlittles** [comment]
I found a hack that allowed me to workaround this issue -- it was described in this comment here: https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/390#issuecomment-1032671742

Simply run

```bash
$ pip install --upgrade keyring
```

Hopefully the maintainer fixes the underlying issue.

**Comment by sthenge** [comment]
error426 gave the following advice to fix this issue:
"Try to change first line in /usr/lib/python3.10/site-packages/keyring/util/properties.py "from collections import Callable"
to "from collections.abc import Callable".

However, I found this file in folder /usr/local/lib/python3.10/site-packages/keyring/util/.  Note the additional folder of "local".  Not sure if this is an artifact of I have several different versions of python installed or what.  Modifying the properties.py file as described by error426 fixed the issue for me. Thanks for solving this issue or at least how to deal with it while a patch is issued at some later date.

**Comment by jungaretti** [comment]
This problem seems to come from a dependency of a dependency:
- [`icloudpd` requires `pyicloud-ipd`](https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/d1644ad0f3c22118509e9b834e54148733122f7b/requirements.txt#L1)
    - [`pyicloud-ipd` requires `keyring`](https://github.com/icloud-photos-downloader/pyicloud/blob/d1153d0424e4788604ab577bd44f763d835dddd5/requirements.txt#L2)

`keyring` throws because `Callable` moved to a new module in Python 3.10: https://bobbyhadz.com/blog/python-importerror-cannot-import-name-callable-from-collections

Upgrading to a more recent version of `keyring` seems to fix the problem. Here's how we could fix this for everyone:
1. Upgrade `pyicloud-ipd` to a more recent version of `keyring`
2. Upgrade `icloudpd` to a more recent version of `pyicloud-ipd` with the fix

**Comment by AndreyNikiforov** [comment]
1.8.0+ `icloudpd` updates dependencies, so it is expect to work with keyring and latest versions of python. Pls try and reopen issues is error persists.
