### ISSUE TITLE
Duplicate JPG photos appear

### ISSUE THREAD

**Issue by 404gods** [icloud-photos-downloader/icloud_photos_downloader#437]
Hello, I am using Synology NAS, I used the variable set_exif_datetime:True in order to display the shooting time in JPG format pictures, everything looks normal.
However, I found that some duplicate JPG images appeared, with the same file size and the same content, named IMG_1234-12345.jpg These images all had EXIF information with the correct capture time.
And, the log content prompts as follows:
2022-05-24 15:06:22 DEBUG    Setting EXIF timestamp for /photo/icloud/2021/IMG_5701.JPG: 2021-12-15 10:13:00+0800
2022-05-24 15:06:28 INFO     /photo/icloud/2021/IMG_5701-435527.JPG deduplicated.
2022-05-24 15:06:28 INFO     Downloading /photo/icloud/2021/IMG_5701-435527.JPG
2022-05-24 15:06:28 DEBUG    Setting EXIF timestamp for /photo/icloud/2021/IMG_5701-435527.JPG: 2021-12-15 10:13:00+0800
![屏幕截图 2022-05-24 151912](https://user-images.githubusercontent.com/50573302/169975032-98bbd136-0b65-4366-a5e6-2cd8f10fa887.png)

How can I avoid these duplicate jpg files? thanks

**Comment by Jonnypleasehelp** [comment]
Yes

**Comment by AndreyNikiforov** [comment]
local files are checked by name and size. if both match to the asset in icloud, then downloading is skipped. if size does not match than ithey are considered different files with the same name (icloud allows multiple files with the same name) and new one is downloaded with new name.

if exif update flag is used, the local files are modified after downloading. their size changes, so deduplication logic sees them as different files and downloads second time.

this issue has been reported before and we haven't figured out deduplication logic that works for all possible scenarios. if you have ideas - please share
