### ISSUE TITLE
[Question] Pause (Cancel) Download & Resume Later?

### ISSUE THREAD

**Issue by jakobjjw** [icloud-photos-downloader/icloud_photos_downloader#445]
## Summary
Hi and thanks for this great tool!
I wasn't able to find any information on one thing, so I thought I would ask it here:

**Is it safely possible to pause (cancel) an ongoing download process (of e.g. all iCloud photos) and to resume it later?**
And if so, what's the best/recommended way to do so?

## Context
This question is especially relevant for big iCloud Photo libraries, for which the download may take many hours. During this time, the user might unexpectedly encounter the need to pause the download in order to resume it later on.

**Comment by AndreyNikiforov** [comment]
You can cancel downloading process at any time and when started again it will download only assets that are not on your local system yet. Partial download of large files is not supported though.

**Comment by jakobjjw** [comment]
It worked! Thanks! 😎
