### ISSUE TITLE
iCloud Photo Library not finished indexing.  Please try again in a few minutes

### ISSUE THREAD

**Issue by isharky** [icloud-photos-downloader/icloud_photos_downloader#454]
I'm always getting the following error message when trying to download the pictures:

```
2022-08-02 16:06:40 DEBUG    Authenticating...
iCloud Photo Library not finished indexing.  Please try again in a few minutes
```

Any idea what to do?

**Comment by menkej** [comment]
This is a common issue with iCloud when you run this for the first time. Try again later. Should work for sure tomorrow…

cheers
Jörg

**Comment by isharky** [comment]
In fact you're right ! Thanks for your help !
