### ISSUE TITLE
"All photos have been downloaded!", but nothing is actually downloaded (Docker)

### ISSUE THREAD

**Issue by jacobschellenberg** [icloud-photos-downloader/icloud_photos_downloader#463]
## Brief Summary
The "All photos have been downloaded!" log is output, but nothing is actually downloaded. Authentication is correct, I can even print out a list of my albums. But it seems photos are just not being downloaded. There are no errors or anything indicating something is wrong.

#Edit: I originally noted this as a in issue when using Docker, but since then I have been able to get it to run locally via python3, and actually still have the same issue. So it doesn't seem to matter whether it's docker or not.

#Edit2: I can now download photos but I have to specify the album. But it still doesn't work even if I specify "All Photos". I'm wondering if it has to do with the fact that I have about 700gb worth of photos/videos that it doesn't know how to handle.

## Log Output
```
2022-08-17 11:57:12 DEBUG    Authenticating...
2022-08-17 11:57:17 DEBUG    Looking up all photos and videos from album All Photos...
2022-08-17 11:57:17 INFO     Downloading 10 original photos and videos to /data ...
  0%|                                                                                                                  | 0/10 [00:00<?, ?it/s]
2022-08-17 11:57:17 INFO     All photos have been downloaded!
2022-08-17 11:57:17 INFO     Deleting any files found in 'Recently Deleted'...
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
Expected that images are actually downloaded.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
Photos and Cookies folder is created, and cookies are stored correctly, but no photos are actually downloaded.

## Context
[NOTE]: # ( Give us any additional information you may have. )
OS: PopOS
Docker command: 

```
docker run -it --rm --name icloud \
    -v $(pwd)/Photos:/data \
    -v $(pwd)/Cookies:/cookies \
    -e TZ=America/Phoenix \
    icloudpd/icloudpd:latest \
    icloudpd \
    --directory /data \
    --cookie-directory /cookies \
    --folder-structure {:%Y/%Y-%m-%d} \
    --username USERNAME \
    --password PASSWORD \
    --size original \
    --recent 10 \
    --auto-delete
```

**Comment by menkej** [comment]
Regrading docker: did you map a directory from outside the container to the container for download? Otherwise the pictures will not end up somewhere "outside"...

Regarding "All Photos": could you please provide a list of all your albums? Maybe the album name for all photos is different in your account? I dare Apple to change things at will, so lets check...

**Comment by boredazfcuk** [comment]
Have you installed iOS 16 Beta on your device and enabled the shared library feature?

**Comment by boredazfcuk** [comment]
@jacobschellenberg I've now merged an iOS 16 shared libraries patch into my container: https://hub.docker.com/r/boredazfcuk/icloudpd#!
