### ISSUE TITLE
Skip movie part of live photo

### ISSUE THREAD

**Issue by steinrr** [icloud-photos-downloader/icloud_photos_downloader#471]
What exactly does the  "--skip-live-photos" option do?

I want to download the photo part of live photos - but not the movie part. Can I use this option for that? Or any other options?

**Comment by zhaobenx** [comment]
I have the same demand to download only photo part.

**Comment by AndreyNikiforov** [comment]
> What exactly does the "--skip-live-photos" option do?
> 
> I want to download the photo part of live photos - but not the movie part. Can I use this option for that? Or any other options?

Yes, this is exactly the way `--skip-live-photos` works. You can also see what files it would download with `--only-print-filenames` option.
