### ISSUE TITLE
Is there any way to set or change Environmental Variables after iCloudpd is installed and running?

### ISSUE THREAD

**Issue by Look2046** [icloud-photos-downloader/icloud_photos_downloader#481]
Just want to try shorter synchronisation_interval. Thank you.

**Comment by AndreyNikiforov** [comment]
@Look2046 there is no `synchronisation_interval` parameter. What tool are you using and how?

**Comment by AndreyNikiforov** [comment]
interval is supported in v1.10.0+ #568
