### ISSUE TITLE
Removal

### ISSUE THREAD

**Issue by ADMiNZ** [icloud-photos-downloader/icloud_photos_downloader#497]
Is it possible to somehow delete all the photos that have been deleted? If the delete folder is already cleared and the photos and videos have been deleted a lot and you need to clean the downloaded photos.

Redownload 500gb?

**Comment by AndreyNikiforov** [comment]
I am not clear what are you trying to achieve. We do support deleting photos locally when they are removed from iCloud (`--auto-delete` option) and removing from iCloud after successful downloading (`--delete-after-download` option), so please be specific where you want photos to be deleted.
