### ISSUE TITLE
Application gets stuck and hangs indefinitely

### ISSUE THREAD

**Issue by Sasafrass** [icloud-photos-downloader/icloud_photos_downloader#516]
## Overview
Hey all! I was super excited when I tried out this application because I have a ton of photos I need to remove and the iCloud UX was a.. pain. However, after a couple of 100 photos, the application hangs. When I retry it manages to get beyond it a little bit but the issue persists after a few 100 pics again. This also persists when I use the dockerized version. It doesn't seem to be a network or API throttling issue afaics. I couldn't find this among the issues, is this a known issue?

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Run application with given command in the README
2. With for ~5-10 minutes of several 100s of images
3. The application hangs and doesn't continue processing any more images.
4. This persists when running the dockerized version.

## Context
Ubuntu 18.04 LTS
Dell XPS 15, I believe 95xx range from 2k17

If anyone has experienced this before and/or knows of a quick fix, lmk! Thanks so much!

**Comment by kjarnot** [comment]
Same issue.  It would be great if the program could retry or even start from a specific photo number.

**Comment by AndreyNikiforov** [comment]
The app processes one image at a time. If you are downloading large file without progress indicator, then symptoms similar to app hanging are possible.

Throttling is certainly possible, but I don't know how it manifests itself in the app behavior. Suspect the app fails...
