### ISSUE TITLE
No PyPI upload for release 1.8.0

### ISSUE THREAD

**Issue by AndreyNikiforov** [icloud-photos-downloader/icloud_photos_downloader#549]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )

Release 1.8.0 went out [without publishing to PyPI](https://github.com/icloud-photos-downloader/icloud_photos_downloader/actions/runs/4029727827/jobs/6927929415).

## Context
[NOTE]: # ( Give us any additional information you may have. )

PyPI does not accept package requirement as git links and in this release we have pyicloud_ipd link as git ref.

Git link was used because pyicloud_ipd was not published to PyPI due to missing PYPI credentials.

To resolve the issue:
- set PyPI credentials for pyicloud_ipd project OR icloud_photo_downloader org
- retry publishing for pyicloud_ipd; assuming it will succeed
- change git ref to pyicloud_ipd in this project to version (0.10.2)
- next release (e.g. 1.8.1) will go to PyPI (will not fix 1.8.0)

 @menkej can you please take care of PyPI credentials if you have them? I'll do the rest.

**Comment by menkej** [comment]
Damn, these secrets are repo and not organizational secrets. Actually I do not know the original secrets. I contacted @ndbroadbent via mail. I hope he can help out quickly.

**Comment by menkej** [comment]
Unfortunately no response from @ndbroadbent to my mail yet, @AndreyNikiforov .  So for now the workaround to include the fork into this repo. Really time to get rid of the fork for good. Unfortunately I'm currently (and still) out of time for this project, so I can't be much of a support right now. Sorry.

**Comment by AndreyNikiforov** [comment]
> Unfortunately no response from @ndbroadbent to my mail yet, @AndreyNikiforov . So for now the workaround to include the fork into this repo. Really time to get rid of the fork for good. Unfortunately I'm currently (and still) out of time for this project, so I can't be much of a support right now. Sorry.

Thanks for reply. Yes, I proceed with including fork into main repo -- that will unblock publishing and keep the door open for other requested improvements, e.g. shared albums, as the original `pyicloud` seems to be is not moving fast either.

**Comment by menkej** [comment]
Good way for now. PyiCloud is really not progressing that much, right. I remember when I tried to reach out to them a good year ago when i tried to include our changes into the upstream version but there was not much interaction unfortunately. Thinking about login issues for Asian users and stuff is handled there AFAIR and it would help us to address issues we find to them and join forces in a way.

**Comment by menkej** [comment]
I received credentials from @ndbroadbent and added them to the pyicloud-ipd project. I reran the Pipeline and was able to publish the update. So it's working now, @AndreyNikiforov
