### ISSUE TITLE
ModuleNotFoundError: No module named

### ISSUE THREAD

**Issue by estatistics** [icloud-photos-downloader/icloud_photos_downloader#550]
on bullseye 11, debian, kde. 

```
/icloud_photos_downloader-master$ python3 icloud.py
Traceback (most recent call last):
  File "icloud_photos_downloader-master/icloud.py", line 2, in <module>
    from pyicloud_ipd.cmdline import main
ModuleNotFoundError: No module named 'pyicloud_ipd'

/icloud_photos_downloader-master$ python3 icloudpd.py
Traceback (most recent call last):
  File "/icloud_photos_downloader-master/icloudpd.py", line 2, in <module>
    from icloudpd.base import main
  File "/icloud_photos_downloader-master/icloudpd/base.py", line 16, in <module>
    from tzlocal import get_localzone
ModuleNotFoundError: No module named 'tzlocal'

/icloud_photos_downloader-master$ python icloudpd.py
Traceback (most recent call last):
  File "icloudpd.py", line 2, in <module>
    from icloudpd.base import main
  File "/icloud_photos_downloader-master/icloudpd/base.py", line 383
    f"Skipping {photo.filename}, only downloading photos."
                                                         ^
SyntaxError: invalid syntax

/icloud_photos_downloader-master$ python icloud.py
Traceback (most recent call last):
  File "icloud.py", line 2, in <module>
    from pyicloud_ipd.cmdline import main
ImportError: No module named pyicloud_ipd.cmdline

```

**Comment by AndreyNikiforov** [comment]
@estatistics  can you provide steps you used? I can guess that you are getting source code and running from there, so python/pip versions installed may be helpful too.

**Comment by estatistics** [comment]
icloudpd-linux is not found. python --version
Python 2.7.18
python3 --version
Python 3.9.4

Note that I run sudo pip install icloudpd /  sudo pip3 install icloudpd or without sudo.
Finally, I succcesfully run `icloudpd -d myphotofolder -u username -p password`
Checking after that on source code, `sudo python3 icloud.py`, `sudo python3 icloudpd.py`, is running ok too. 
So, I think, some python dependencies were not installed (or not installed in sudo or not sudo dirs). 
Cause, installing with `sudo`, didnt run too. 
Or maybe i must closed terminal in order to update paths? I have read something like that. 
Finally, icloud photos were all downloaded successfully. thanks for your useful program.
