### ISSUE TITLE
Missing icloud utlity from pip version

### ISSUE THREAD

**Issue by gec1-dev** [icloud-photos-downloader/icloud_photos_downloader#594]
## Overview
My system is ubuntu 22.10.
After having installed icloudpd via the pip command (non-root account) I wanted to store my password in the keyring using the icloud utility, however, the icloud utility is missing, at least from the whl (pip package)

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. pip install icloudpd (correctly installs the icloudpd package)
2. icloudpd --version (correctly gives version number, so installation was succesful)
3. icloud --version or icloud (gives an error:
```
Command 'icloud' not found, but can be installed with:
sudo apt install python3-pyicloud

```
)
4. ls -l ./local/bin/ shows icloudpd script but does not show icloud.

## Expected Behavior
icloud utility is installed together with icloudpd and can be executed

## Actual Behavior
icloud utility is missing

## Context
N/A, I think

**Comment by AndreyNikiforov** [comment]
@gec1-dev thanks for reporting the issue. Fix will be in the next release.

Curious if binary packages (binaries or docker) would work for you. Binary distributions solve many dependency issues and if you prefer src, I would like to know why (so I will continue to cover different use cases).

**Comment by gec1-dev** [comment]
Thank you for the answer. I am using the binaries right now. I just prefer cleaniness of package managers plus like to run from source in case I need to debug or understand better the program.
