### ISSUE TITLE
icloud utility with cookies parameter

### ISSUE THREAD

**Issue by steffenmartin** [icloud-photos-downloader/icloud_photos_downloader#597]
## Summary
Provide option to specify cookie directory for _icloud_ utility

## Context
It's been an odyssey chasing down the location of the (authentication) cookies directory created by the _icloud_ utility, which also needs to be provided to _icloudpd_. The most confusing portion from a user standpoint is the inconsistency of the default location used by the _icloud_ utility (e.g. C:\Temp\pyicloud on Windows or /tmp/pyicloud on Unix/Linux) vs. the default used by the _icloudpd_ application (~/.pyicloud). The increased adoption and ease of use by providing consistency would help tremendously, including the case where expired cookies might have to get refreshed. Being able to specify the location of the cookies using the _icloud_ utility would help.

## Proposal
![image](https://user-images.githubusercontent.com/3614263/223619151-8c54363f-220d-4e09-8164-c804f8c63f07.png)

**Comment by AndreyNikiforov** [comment]
@steffenmartin when do you need to provide cookies directory to `icloud` and then use it in `icloudpd` (and cannot use only `icloudpd`)?

**Comment by steffenmartin** [comment]
I thought it's necessary when having _icloudpd_ run while "watching" for changes and the authentication cookie expiring. I just now realized that there's no authentication anyways while "watching", so yeah, could just stop and re-run _icloudpd_ to refresh the authentication cookie (including 2FA). Now just wondering whether that watching option would work forever. Also, it appears that if running off of cron (i.e. always authenticating) also automatically refreshes the cookie without there ever being another need for 2FA, which is probably the better way to go over "watching" every few hours or so (which will certainly cause the cookie to fully expire).

**Comment by AndreyNikiforov** [comment]
"--watch-with-interval" parameter should be the same behavior as running `icloudpd` as cron job, just simpler and platform-agnostic. Every now and then Apple may expire cookies, in which case "watch" and "cron" approaches both would require re-authentication.
