### ISSUE TITLE
Only download files not available in backup

### ISSUE THREAD

**Issue by freakinpenguin** [icloud-photos-downloader/icloud_photos_downloader#612]
## Summary
I'm using the script to backup all of my iCloud photos to an harddisk. This means I will run the script in regular turns by a cron-job or something. Furthermore I propably won't download all photos on one run (>30k).

What I expected is that the script checks the files available on the harddisk and then only downloads the ones which are not available locally. But the script starts to download all photos from scratch.

I'm aware of the switches `--until-found` and `--recent`, but as the script starts to download the newest photos first, this doesn't really help.
Maybe I missed the proper setting for this, so please feel free to bump to the proper one in case.

## Context
I'm not sure whether this is a special circumstance, but maybe a different approach on how to use this tool

## Thanks
For this tool 👍

**Comment by AndreyNikiforov** [comment]
@freakinpenguin `icloudpd` always checks for existing files and never overrides. What cmd are you using? What output leads you to believing that `icloudpd` downloads your collection again?
