### ISSUE TITLE
Saving password to keyring broken?

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#619]
## Overview
Cannot save password to keyring. Prompted for password on each run

## Steps to Reproduce
Create vanilla container:
```
docker run --interactive --tty --rm \
   --name icloudpd_test \
   --env TZ=UTC \
   --network containers \
   alpine:latest /bin/ash
```
Add pip, wheel, icloudpd, then run icloudpd twice:
```
apk add py-pip >/dev/null
pip3 install --quiet --no-cache-dir wheel
pip3 install --quiet --no-cache-dir icloudpd
icloudpd --username appleid@domain.com --directory /dev/null --only-print-filenames --recent 1
icloudpd --username appleid@domain.com --directory /dev/null --only-print-filenames --recent 1
```

## Expected Behavior
Only prompted for password/2FA the first time. keyring_pass.cfg created at ~/.local/share/python_keyring/keyring_pass.cfg

## Actual Behavior
![image](https://user-images.githubusercontent.com/14807258/230717183-b178addd-157b-4894-8434-c76720fdfbba.png)
~/.local/share/python_keyring/keyring_pass.cfg is missing and does not exist inside container

**Comment by AndreyNikiforov** [comment]
Was the behavior of saving password to keyring available in prior versions of `icloudpd` and then broken? If it was available, do you know when it was broken by any chance? I don't see explicit saving in the code, only reading.

You can use `icloud` to save password to keyring BTW.

**Comment by boredazfcuk** [comment]
> You can use `icloud` to save password to keyring BTW.

I thought it was icloudpd I was using, and that it was saving the password at login... Guess I must have amended the path of this app to an incorrect one.
