### ISSUE TITLE
Keep reporting errors, unable to download

### ISSUE THREAD

**Issue by PWMFI** [icloud-photos-downloader/icloud_photos_downloader#624]
Keep reporting errors, unable to download, provide log files, can you help me see
<img width="1244" alt="20230416232825" src="https://user-images.githubusercontent.com/63692121/232323372-03858275-16d6-4600-8b7a-1cd4529ba4b8.png">

**Comment by AndreyNikiforov** [comment]
@PWMFI Seems that you are using image from another project
