### ISSUE TITLE
Allow download of RAW photos when using "--skip-videos" option

### ISSUE THREAD

**Issue by pjahn** [icloud-photos-downloader/icloud_photos_downloader#662]
With the iPhone 12 Pro, Apple introduced the functionality to take photos in RAW data format (see https://support.apple.com/en-us/HT211965). However, these photos are not included in the download and there is currently no option to do so. Those files are currently skipped. I suggest that this option be added to optionally include these files (they have the suffix "dgn") in downloads.

**Comment by AndreyNikiforov** [comment]
> ...Those files are currently skipped...

Can you provide more detain on the cmd you tried that with? Version of `icloudpd`, cmd line params and any other detail you find relevant.

I tried latest version `icloudpd -d ./ASSETS -u my@email.address --recent 2` and it downloaded Pro image (DNG) and Pro video (MOV) just fine.

**Comment by pjahn** [comment]
> > ...Those files are currently skipped...
> 
> Can you provide more detain on the cmd you tried that with? Version of `icloudpd`, cmd line params and any other detail you find relevant.
> 
icloudpd, version 1.13.0

parameters:
`icloudpd --username user@domain.com --password anypassword --until-found 5 --skip-videos --no-progress-bar --set-exif-datetime --folder-structure {:%Y/%Y-%m-%d} --directory /somepath --cookie-directory /somepath`

> I tried latest version `icloudpd -d ./ASSETS -u my@email.address --recent 2` and it downloaded Pro image (DNG) and Pro video (MOV) just fine.

Will try the latest version now.

**Comment by pjahn** [comment]
Tried with the latest version.

Output:
`2023-07-26 18:47:21 DEBUG    Skipping IMG_1804.DNG, only downloading photos.(Item type was: movie)`

**Comment by pjahn** [comment]
`icloudpd -d /tmp -u user@domain.com  --skip-videos --recent 2` => no dng downloaded
`icloudpd -d /tmp -u user@domain.com --recent 2` => dng downloaded

--skip-videos parameter skips dng files.

**Comment by kfstorm** [comment]
My camera (a Panasonic camera) saves both JPG and RW2 files. I upload them manually to iCloud. A photo with two files (one for JPG and one for RW2) is shown as a single photo on iCloud (and on my iPhone too), with a "JPEG + RAW" hint at the top left corner of the photo if I click it.

I can download both files of the photo by clicking the three dots button next to the delete button and choosing "More Download Options" -> "Unmodified Original". The downloaded zip is like this:

```shell
$ unzip -l ~/Downloads/iCloud\ Photos\ \(3\).zip
Archive:  /Users/yangkai/Downloads/iCloud Photos (3).zip
  Length      Date    Time    Name
---------  ---------- -----   ----
  7954944  08-17-2023 12:36   iCloud Photos/P1200376.JPG
 23651328  08-17-2023 12:36   iCloud Photos/P1200376.RW2
---------                     -------
 31606272                     2 files
```

Hope there's an option to allow downloading both JPG and RAW files.

**Comment by odedia** [comment]
Would be great to also have an option to *only* download RAW files. In my case I'm using Nikon cameras and the extension is .NEF.

**Comment by AndreyNikiforov** [comment]
1.19.0 fixes single-raw file assets (recognized as images now) as well as introduces support for raw+jpeg. raw files from different manufacturers are supported

**Comment by pjahn** [comment]
Thank you!
