### ISSUE TITLE
[MacOS] Upon Completing A Request icloudpd Displays A Resource Leak Warning Followed By Inducing The New CLI Prompt

### ISSUE THREAD

**Issue by scrutinizer11** [icloud-photos-downloader/icloud_photos_downloader#668]
## Overview

Immediately after completing the request, **icloudpd** invokes the new command line prompt, displays a warning and exits.

## Steps to Reproduce

1. run **icloudpd --list-albums** and authenticate
2. Wait until the session wraps up and see what happens.

## Expected Behavior

No uncalled actions.

## Actual Behavior

The utility displays the warning "multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak." and then calls up another prompt before exiting. 

## Context
**macOS 10.14, icloudpd 1.15.1**

![icloudpd-err](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/45983734/31728e37-4b8f-439e-b901-ea233c25ecd2)

**Comment by AndreyNikiforov** [comment]
Reproduced the issue on mac M1 and icloudpd 1.15.1, but linux & windows are fine.

As a fast mitigation you can downgrade to 1.14.2 (or earlier):
```
pip3 install icloudp==1.14.2
```

**Comment by genfersee** [comment]
I have the same issue.

`2023-09-25 08:14:31 INFO     Downloading ??? original photos and videos to /Users/rrr/Library/Mobile Documents/com~apple~CloudDocs/Photos ...
0it [00:00, ?it/s]multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.`

**Comment by petebocken** [comment]
This issue was fixed (or previously fixed and now a problem again)? I just updated to 1.17.0 and everything appears to be working again, but this displays every time when run:

```
me@computername icloudpd % ./icloudpd.sh
Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B
multiprocessing/resource_tracker.py:123: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
me@computername icloudpd % Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B
```

**Comment by AndreyNikiforov** [comment]
confirming that the fix works for experimental binary only (icloudpd-ex), but not main binary (icloudpd).

**Comment by AndreyNikiforov** [comment]
pls see if 1.17.1 fixed the issue. reopen if not

**Comment by petebocken** [comment]
Yup, 1.17.1 fixed it. thanks!
