### ISSUE TITLE
How to change icoud password in keyring?

### ISSUE THREAD

**Issue by MrDecepticon** [icloud-photos-downloader/icloud_photos_downloader#681]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I have had to recently change my icloud password and I am not sure how to change it within the keyring.  

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I am using the UnRaid docker of icloudpd and it is now erroring out since I changed my password.  I used the --initialize swich expecting it to see that the current stored password is incorrect and I thought it would prompt me to change it and then follow up with the 2FA cookie process. 

I cannot figure out how to change the stored password for my icloud account in the keyring.  Using 'icloud' commands do not seem to work in my instance.

**Comment by boredazfcuk** [comment]
Your mention of the --initialise parameter makes me think you are using the icloupd container I built, but have logged this issue in the wrong repo.

If you head over to my repo and check out the configuration documentation, you should find what you need.

**Comment by MrDecepticon** [comment]
> Your mention of the --initialise parameter makes me think you are using the icloupd container I built, but have logged this issue in the wrong repo.
> 
> If you head over to my repo and check out the configuration documentation, you should find what you need.

Oh wow, yeah.  I didn't even notice I was in the wrong repo.

**Comment by MrDecepticon** [comment]
This was moved to the proper repo.

**Comment by MrDecepticon** [comment]
This was moved to the correct repo.
