### ISSUE TITLE
Closes on launch, kind of

### ISSUE THREAD

**Issue by ChillyFlake** [icloud-photos-downloader/icloud_photos_downloader#686]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Whenever i launch 'icloud-1.15.1-windows-amd64.exe' it opens, shows a little menu of some sort with options like move or copy, says theres no username to work with and closes. when i launch 'icloudpd-1.15.1-windows-amd64.exe' all i see is "enter email/username." when i do so, it says i must submit or it needs folders or whatever and then closes. 
i dont think this is a bug as it is likely my own ineptitude in using the program, but im not well versed in this type of thing and simply would rather spend my time troubleshooting than downloading 200 photos at a time over 500 times. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I couldn't find any instruction sin the faq or any files in the master folder about step by step how to just run the exe files and get it to work so i figured itd be self explanatory, and googling the issue only leads to a direct link to here.

**Comment by ChillyFlake** [comment]
@AndreyNikiforov as in i double click the exe and a command window opens up. attatching a snip i was able to get in the second and a half it loads before closing.
![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/133548613/01f32750-89ff-489a-852c-0f7762b405e5)

**Comment by AndreyNikiforov** [comment]
Windows double clicking runs cli programs in cmd window but without parameter. For `icloudpd` some parameters are required, so you need to open cmd window first and then run executable with parameters there, e.g.:
- hit Windows-R to open Run dialog
- enter "cmd" there and click run - that will open CMD window; the following cmds are in that CMD window
- change drive to where you downloaded exe, e.g. `D:`
- run `cd folder_where_you_downloaded_exe`, e.g. `cd D:/downloads/`
- run `icloudpd -u your@email.address -d path_where_to_download`
- you can read about parameters by running `icloudpd --help`

**Comment by ChillyFlake** [comment]
yep, that did the trick! now i hope its alright to ask, but if i just want it to download to a folder in my d drive and delete them from icloud (so itll be empty again and ill have the photos on my drive), would this command be correct? only asking cause if its not i dont want to have 50 gb of photos download wrong or something
" C:\Users\[My User]\Downloads>icloudpd-1.15.1-windows-amd64 -u [My Email] -p [My Password] -d D:\[Destination Folder] --auto-delete "

**Comment by ChillyFlake** [comment]
nevermind, did some poking around in the faq and read me and found what i was looking for. thanks so much!
