### ISSUE TITLE
Maybe support aarch64

### ISSUE THREAD

**Issue by jsbxyyx** [icloud-photos-downloader/icloud_photos_downloader#689]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by AndreyNikiforov** [comment]
We have docker container for arm64. Will that work for RPi? Will that work for your use case?

**Comment by AndreyNikiforov** [comment]
For posterity: Executables in GitHub releases are limited to MacOs, Linux x64, and Windows x64 by GitHub infra used for releases. List of supported arch by Docker releases is bigger and is only limited to archs supported by Docker, as building of the images is ran on emulators on top of GitHub Linux x64 infra.
