### ISSUE TITLE
Logging seems broken

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#697]
## Overview
In my container, when I run icloudpd, I output the logs to stdout and stderr for further parsing. This worked in previous versions, but in release 16.2, logging seems broken.

## Steps to Reproduce
1. ./icloudpd --directory /icloud --cookie-directory /config --domain com --username myemail@domain.com --auto-delete --folder-structure {:%Y/%m} 2>/tmp/icloudpd/icloudpd_download_error | tee /tmp/icloudpd/icloudpd_sync.log

## Expected Behavior
stdout is passed to tee which pushes the logs to stdout and also to /tmp/icloudpd/icloudpd_sync.log

## Actual Behavior
Nothing goes to tee, so no logging to screen. Everything ends up in stderr.

**Comment by AndreyNikiforov** [comment]
What version did it work? Can you highlight differences in behavior in two versions, pls? I tried running the following in 1.6.1 and 1.15.1 and then seem to produce same `./d`:
```
icloudpd -u my@email.address -d ./ --dry-run --recent 10 --no-progress-bar 2> ./d
```

**Comment by AndreyNikiforov** [comment]
Maybe related to #664 when we switched to using standard python logging.

**Comment by boredazfcuk** [comment]
Just confirming that I've now tested v1.16.2 and it's working as expected.
