### ISSUE TITLE
Mix of Copy and Sync mode for Backup?

### ISSUE THREAD

**Issue by thisisbommy** [icloud-photos-downloader/icloud_photos_downloader#702]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )

Thanks for building this tool. I was delighted to discover it. 

I wondered if you’d considered an option where all new iCloud Photos content is downloaded (like Copy) but where content that’s deleted in iCloud is moved to a sub-folder (as opposed to deleted, which Sync does) and held permanently or for a configurable number of days?

This would leave me with two sets of content. 
1. My iCloud library exactly as I have it managed and curated on my Apple devices. 
2. A separate backup folder of deleted content as a safeguard in case I need to restore any of it, like a permanent Recycle Bin. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

I have enough iCloud storage for all of my content. I will be using this tool on my local file server so that I have a backup in case of some kind of catastrophic error on iCloud, like account compromise or accidental deletion.

**Comment by AndreyNikiforov** [comment]
Folder with deleted photos is just an album, so it you try to download it using `--album` parameter, it should work.

**Comment by boredazfcuk** [comment]
> Folder with deleted photos is just an album, so it you try to download it using `--album` parameter, it should work.

Can confirm this does work as I've done it in the past.
