### ISSUE TITLE
WARNING  Downloading

### ISSUE THREAD

**Issue by qwe466730094** [icloud-photos-downloader/icloud_photos_downloader#710]
<html>
<body>After I entered the icloud password, there was no prompt to use the bound phone number to receive verification code text messages. After restarting, I was unable to initialize the prompt not 2FA

2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Restarting in 5 minutes...
-- | -- | --
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO      - Example: docker exec -it icloudpd sync-icloud.sh --Initialise
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO      - Syntax: docker exec -it <container name> sync-icloud.sh --Initialise
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO      - Please recreate your cookie using the --Initialise script command line option.
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 ERROR    Cookie is not 2FA capable, authentication type may have changed.
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Cookie exists, check expiry date
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Check 2FA Cookie
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Synchronisation starting at 04:54:51
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Sync user qwe466730094
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set 640 permissions on iCloud files, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set 750 permissions on iCloud directories, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct group on keyring directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct owner on keyring directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct group on config directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct owner on config directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct group on icloudpd temp directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct owner on icloudpd temp directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set group, users, on iCloud directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set owner, qwe466730094, on iCloud directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Failsafe file /iCloud/.mounted exists, continuing.
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Check download directory mounted correctly
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Using password stored in keyring file: /config/python_keyring/keyring_pass.cfg
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Configure password
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set 640 permissions on iCloud files, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set 750 permissions on iCloud directories, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct group on keyring directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct owner on keyring directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct group on config directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct owner on config directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct group on icloudpd temp directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Correct owner on icloudpd temp directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set group, users, on iCloud directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Set owner, qwe466730094, on iCloud directory, if required
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     User, qwe466730094:1028, already created
2023/11/04 04:54:51 | stdout | 2023-11-04 04:54:51 INFO     Group, users:100, already created
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 WARNING  Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Downloading from: icloud.com.cn
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     JPEG conversion quality: 90
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Convert HEIC to JPEG: False
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Skip videos: False
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Live photo size: original
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Stop downloading when prexisiting files count is: Download All Photos
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Number of most recently added photos to download: Download All Photos
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Skip live photos: False
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Skip download check: true
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Photo size: original
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Auto delete: False
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Set EXIF date/time: False
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Time zone: Asia/Shanghai
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Synchronisation delay (minutes): 0
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Synchronisation interval: 86400
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     File permissions: 640
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Directory permissions: 750
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Folder structure: {:%Y/%m/%d}
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Download destination directory: /iCloud
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Cookie expiry notification period: 7
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Cookie path: /config/466730094qqcom
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Authentication Type: 2FA
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Apple ID: 466730094@qq.com
2023/11/04 04:54:48 | stdout | 2023-11-04 04:54:48 INFO     Route check to icloud.com.cn successful
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     DNS lookup for icloud.com.cn: 103.115.248.1
2023/11/04 04:54:20 | stdout | 192.168.50.1
2023/11/04 04:54:20 | stdout | 192.168.50.1
2023/11/04 04:54:20 | stdout | 192.168.50.1
2023/11/04 04:54:20 | stdout | 114.114.114.114
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     DNS server: 192.168.50.1
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     Default gateway: 172.17.0.1
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     LAN IP Address: 172.17.0.2
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     Force GID: True
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     Local group: users:100
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     Local user: qwe466730094:1028
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     Running group id: 0
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:20 INFO     Running user id: 0
2023/11/04 04:54:20 | stdout | 2023-11-04 04:54:16 INFO     pyicloud-ipd version: 0.10.1
2023/11/04 04:54:20 | stdout | You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.[0m
2023/11/04 04:54:20 | stdout | [33mWARNING: You are using pip version 21.3.1; however, version 23.3.1 is available.
2023/11/04 04:54:16 | stdout | 2023-11-04 04:54:12 INFO     icloudpd version: 1.7.2
2023/11/04 04:54:16 | stdout | You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.[0m
2023/11/04 04:54:16 | stdout | [33mWARNING: You are using pip version 21.3.1; however, version 23.3.1 is available.
2023/11/04 04:54:12 | stdout | 2023-11-04 04:54:12 INFO     Python version: 3.8.10
2023/11/04 04:54:12 | stdout | 2023-11-04 04:54:12 INFO     Alpine Linux 3.13.5
2023/11/04 04:54:12 | stdout | 2023-11-04 04:54:12 INFO     ***** /usr/local/bin/sync-icloud.sh hash: 74dfafa177492086fb3c777f518fbb55 *****
2023/11/04 04:54:12 | stdout | 2023-11-04 04:54:12 INFO     ***** /usr/local/bin/sync-icloud.sh date: 2021/12/13_07:53 *****
2023/11/04 04:54:12 | stdout | 2023-11-04 04:54:12 INFO     ***** https://github.com/boredazfcuk/docker-icloudpd *****
2023/11/04 04:54:12 | stdout | 2023-11-04 04:54:12 INFO     ***** boredazfcuk/icloudpd container for icloud_photo_downloader started *****

</body>
</html>

**Comment by AndreyNikiforov** [comment]
Log says: `Downloading from icloud.com.cn is untested. Please report issues at https://github.com/boredazfcuk/docker-icloudpd/issues` - you are using docker container from downstream project, not `icloudpd` docker from this repo.
