### ISSUE TITLE
"resource_tracker: process died unexpectedly, relaunching.  Some resources might leak." and "no such option" errors

### ISSUE THREAD

**Issue by scrutinizer11** [icloud-photos-downloader/icloud_photos_downloader#713]
## Overview
icloudpd errors several times during the command execution, prints out the required output, and re-launches to the same error message. The OS is **macOS 10.14**.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Prerequisite: the password is saved with **icloud**  
2.  Run **icloudpd -l** and answer the prompts.

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
A command output followed by an exit.

## Actual Behavior
On passing authentication and finalizing the supplied command option an error shows up twice during which the utility launches again so that a force-quit is needed.

## Context
The output of the running session is below:
```bash
COMPUTER:~user$ icloudpd -l
iCloud username/email: *********@*****.com
2023-11-11 14:24:40 DEBUG    Authenticating...
Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B
2023-11-11 14:25:09 INFO     Two-step/two-factor authentication is required
  0: SMS to ******83
  1: Enter two-factor authentication code
Please choose an option: [0]: 1
Please enter two-factor authentication code: 362736
2023-11-11 14:25:41 INFO     Great, you're all set up. The script can now be run without user interaction until 2SA expires.
You can set up email notifications for when the two-step authentication expires.
(Use --help to view information about SMTP options.)
Albums:
All Photos
Time-lapse
Videos
Slo-mo
Bursts
Favorites
Panoramas
Screenshots
Live
Recently Deleted
Hidden
Adam and Amy
Untitled
Untitled 2
Loyalty cards
Smart-ID
Cover art
multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
COMPUTER:~user$ Usage: icloudpd <options>
Try 'icloudpd -h' for help.

Error: No such option: -B

COMPUTER:~ user$
```
The computer name, login shell name, and e-mail address are anonymized.

**Comment by AndreyNikiforov** [comment]
same as #668 , right? You are using macos, correct?

**Comment by scrutinizer11** [comment]
Yes. I forgot I had a similar issue opened nearly 4 months ago. It wasn't addressed since then. The shell is **bash 3.2.57**.

**Comment by AndreyNikiforov** [comment]
dup

**Comment by scrutinizer11** [comment]
The error is slightly different this time. _"-B: No such option"_ wasn't in the previous version. Will it find its fix as well as this weird execution after execution accompanying the operation?
