### ISSUE TITLE
Time Zone not works.

### ISSUE THREAD

**Issue by bowencool** [icloud-photos-downloader/icloud_photos_downloader#714]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )

This is the info in iCloud:
<img width="280" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/20217146/ee4527ed-1f90-4335-88d4-b470c8bf777f">

This is the info in icloudpd-downloaded:
<img width="393" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/20217146/93300b05-c1a3-4494-97b4-7bcb31fdf592">

The logs do not match system time also:
<img width="601" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/20217146/370a7fb3-3f6e-4d30-b92f-4ad83f6f5458">

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
here is my script:
``` bash
icloud_home=/mnt/xxx/icloudpd
mkdir -p ${icloud_home}
docker run -it --rm --name icloudpd \
    -v ${icloud_home}/Photos:/data \
    -v ${icloud_home}/cookies:/cookies \
    -e TZ=Asia/Shanghai \
    icloudpd/icloudpd:latest \
    icloudpd --directory /data \
    --cookie-directory /cookies \
    --folder-structure {:%Y/%Y-%m-%d} \
    --username xxx \
    --password xxx \
    --size original \
    --domain cn \
    --auto-delete
```

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )

The downloaded photos should have the exact same information as their info in iCloud.

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )

The information of the downloaded photos does not match their information in iCloud.

## Context
[NOTE]: # ( Give us any additional information you may have. )

**Comment by AndreyNikiforov** [comment]
Looks like the difference in time is related to timezone (8hr for Shanghai). What time zone do you have on iPhone where you took picture, device (Mac?) where you saw iCloud data and device where you run docker image?

icloudpd uses local timezone (in docker in your case) to setup time.

**Comment by boredazfcuk** [comment]
To show correct time in the log files inside my container, I install the tzdata package from the OS repo:
```
apk add --no-progress --no-cache tzdata
```
Maybe there is an issue with the pyinstaller tzdata package?

**Comment by AndreyNikiforov** [comment]
> To show correct time in the log files inside my container, I install the tzdata package

In other docker containers I saw ppl mounting /etc/localtime from the host, e.g. `-v /etc/localtime:/etc/localtime:ro`. IIUC that approach does not need tzdata in container.

> Maybe there is an issue with the pyinstaller tzdata package?

I wonder how can we reproduce the issue reliably?

**Comment by boredazfcuk** [comment]
Maybe it's operating on different levels?
In this screenshot, it shows the correct time zone information in the log file (which should be handled by Python's tzdata package):
<img width="601" alt="283088895-370a7fb3-3f6e-4d30-b92f-4ad83f6f5458" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/14807258/bef51a14-b643-4415-aa9f-27e6bd1df4ed">
However, the `date` command run immediately after shows a different date. This won't be using pyinstaller's tzdata and will be pulling the system time zone, which is defaulting to CST, at a guess.

**Comment by AndreyNikiforov** [comment]
@bowencool zooming out a bit: how do you use OS-level attributes of the downloaded files? If your assets have right EXIF data inside, I assume all image manipulation software will use EXIF and don't pay attention to file attributes.

**Comment by bowencool** [comment]
> Looks like the difference in time is related to timezone (8hr for Shanghai). What time zone do you have on iPhone where you took picture, device (Mac?) where you saw iCloud data and device where you run docker image?
> 
> icloudpd uses local timezone (in docker in your case) to setup time.

My iPhone, Mac, and NAS (unRAID) are all set to Beijing time (+8), and they are all located in China.

Mac OS:
<img width="434" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/20217146/c4dcf340-213c-4474-8839-e6c1d5267acf">

unRAID:
<img width="502" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/20217146/f3f3d983-2692-4906-b131-eadd87f7ef0b">

I'm checking the original information in the Photos app(MacOS):
<img width="280" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/20217146/9d70b0b5-1d7c-4435-b2fb-6d6c7f6a6b18">

I am accessing the file downloaded by unRAID using Finder via SMB:
<img width="886" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/20217146/e81b7ea1-2fa6-4282-8328-cb4d8dfdf333">

**Comment by bowencool** [comment]
I am using MtPhotos to view EXIF data and have noticed conflicts within the data:
``` jsonc
{
  "ExifToolVersion": 12.4,
  "FileName": "IMG_3842.JPG",
  "FileModifyDate": "2023:11:10 04:00:37+08:00", 
  "FileAccessDate": "2023:11:10 04:00:37+08:00", 
  "FileInodeChangeDate": "2023:11:16 10:56:34+08:00",
  "ModifyDate": "2023:11:09 20:00:37",
  "DateTimeOriginal": "2023:11:09 20:00:37",
  "CreateDate": "2023:11:09 20:00:37",
  "GPSDateStamp": "2023:11:09",
  "SubSecCreateDate": "2023:11:09 20:00:37.607+08:00",
  "SubSecDateTimeOriginal": "2023:11:09 20:00:37.607+08:00",
  "SubSecModifyDate": "2023:11:09 20:00:37+08:00",
  "GPSDateTime": "2023:11:09 11:58:34Z"
  // ...
}
```

**Comment by AndreyNikiforov** [comment]
From the data above, it looks to me:
- image was taken 2023-11-09 20:00:37+08:00 (this is CST); that is recorded as DateTimeOriginal without timezone info
- folder structure was correctly created using 09 day of month
- File attributes (Created & Modified) were set with extra 8hrs adjustment as if TZ was applied twice

Two approaches from here that I see:
1. do not set file attributes at all and set correct expectations; rationale: IIUC, most/all image organizing and manipulating software use EXIF/XMP, not file attributes
1. figure out why timezone calc was applied to file attributes incorrectly, fix, and, possibly, add extra setup to code/doc

I am leaning toward the former (remove file attributes at all) and would love to hear other opinions.

**Comment by bowencool** [comment]
> From the data above, it looks to me:
> 
> * image was taken 2023-11-09 20:00:37+08:00 (this is CST); that is recorded as DateTimeOriginal without timezone info
> * folder structure was correctly created using 09 day of month
> * File attributes (Created & Modified) were set with extra 8hrs adjustment as if TZ was applied twice
> 
> Two approaches from here that I see:
> 
> 1. do not set file attributes at all and set correct expectations; rationale: IIUC, most/all image organizing and manipulating software use EXIF/XMP, not file attributes
> 2. figure out why timezone calc was applied to file attributes incorrectly, fix, and, possibly, add extra setup to code/doc
> 
> I am leaning toward the former (remove file attributes at all) and would love to hear other opinions.

I recommend the latter.

We will miss this feature of setting file attributes if someone else fixes the TZ issue. This absence may confuse those who are accustomed to using it.

**Comment by AndreyNikiforov** [comment]
> ... This absence may confuse those who are accustomed to using it.

I am trying to understand how people are accustomed to using file attributes of image/videos, especially if attributes are incorrect. Since attributes are incorrect (and I suspect for a long time) it is very reasonable to assume that they are not used at all. Are you using/relying of file attributes yourself? How? I do not pay any attention to them at all. BTW I don't rely on dates in folder hierarchy either, but storing all photos in one big folder has other challenges, so I am using hierarchy.

**Comment by bowencool** [comment]
> > ... This absence may confuse those who are accustomed to using it.
> 
> I am trying to understand how people are accustomed to using file attributes of image/videos, especially if attributes are incorrect. Since attributes are incorrect (and I suspect for a long time) it is very reasonable to assume that they are not used at all. Are you using/relying of file attributes yourself? How? I do not pay any attention to them at all. BTW I don't rely on dates in folder hierarchy either, but storing all photos in one big folder has other challenges, so I am using hierarchy.

No, I'm not using file attributes.

**Comment by AndreyNikiforov** [comment]
@bowencool pls check if 1.16.3 works for you and reopen the issue if it does not.

**Comment by bowencool** [comment]
> @bowencool pls check if 1.16.3 works for you and reopen the issue if it does not.

I encountered #717 in various ways.
