### ISSUE TITLE
Download from Recents, not All Photos

### ISSUE THREAD

**Issue by mythofechelon** [icloud-photos-downloader/icloud_photos_downloader#715]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It seems that icloudpd downloads from All Photos, rather than Recents, at least when using the argument `--until-found`.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I'm planning to add photos to my iCloud Photo Library that have EXIF time stamps from months or even years ago. This isn't a problem in the iOS app because you can either see them in order of when they were taken in Library or in order of when they were added in recents, but I'm guessing that I won't be able to easily use icloudpd because it'd need to scan and/or redownload my entire library to pick out these new photos, rather than just downloading from the recents backwards?

**Comment by AndreyNikiforov** [comment]
`icloudpd` never redownloads file, so it is safe to run it without `--until-found` or `--recent`. These two parameters can be viewed as optimizations with "fine print".

Will using `icloudpd` without `--until-found` work for you?

**Comment by mythofechelon** [comment]
My test photo has an EXIF date of 2010/11/19, and I added it to my Photos on 2023/11/19. My library contains 29,471 items, and I've created 91 photos or videos since then (this is relevant).

While testing https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/715#issuecomment-1840147786, I noticed that folder `<path>\iCloud Photos Backup\2010` existed and only contained my test photo, so I deleted that folder and:

1. Ran `icloudpd-latest-windows-amd64.exe --directory "<path>\iCloud Photos Backup" --username <username> --until-found 20` but nothing changed.
2. Ran `icloudpd-latest-windows-amd64.exe --directory "<path>\iCloud Photos Backup" --username <username> --until-found 100` and, after only ~10 seconds, the 2010 folder and photo re-appeared.

So, it seems that it is actually downloading from Recents after all?

**Comment by AndreyNikiforov** [comment]
help for `-until-found`: "Download most recently added photos until we find x number of previously downloaded consecutive photos"

How many photos have you added to your collected after 2023/11/19 and how many of latest of them were already downloaded to your local drive? Answers to these questions will help you answer why `-until-found 20` did not work, but `--until-found 100` did.

**Comment by mythofechelon** [comment]
I understand why one worked and the other didn't - I was provided both examples of evidence of why I think it does actually download from Recents. This can be closed now, thanks.
