### ISSUE TITLE
Is it possible to rename the image/video files? Also I have another question about Recents and the main page of the photos app.

### ISSUE THREAD

**Issue by iammarxg** [icloud-photos-downloader/icloud_photos_downloader#718]
I'm trying to use folder structure to sort by: year, month, day. Then each image/video inside day would be renamed to the time it was saved (just like in Recents) or the time it was downloaded/shot. I just don't know how to do it. (I'm downloading a singular album)

If renaming the image/video file is not possible, then what are the available parameters/formats for --folder-structure?
The only example I can find is (default: {:%Y/%m/%d}). I don't really know how to use it or modify it, as I'm pretty new to advanced scripts and stuff like this. Sorry if this is a stupid question, I tried googling it but I couldn't find an answer for 20 minutes.

Also, all the images/videos I'm downloading from iCloud have been downloaded through safari, and then saved from the files app to the photos app a few hours later. In Recents (in the photos app), they were organized in the order I saved them in. But in the main photos app page, the videos are saved first then the images below. I also noticed that the videos have the same time I downloaded them at (downloaded from safari), meanwhile the photos have the same time I saved them at (saved from files app). Is there a way to only use the time I saved them at, for both videos and photos? Just like in Recents.

EDIT: [This](https://www.reddit.com/r/ApplePhotos/comments/14mxwnc/comment/jq4c40c/) is what I mean. I want to save the photos and videos I downloaded on the date, time, and most importantly sequence (order) of import.

**Comment by AndreyNikiforov** [comment]
@iammarxg `icloudpd` uses original image name and does not have capability to change it with pattern.

That said, I am wondering what do you need timestamps as a filename for? If you are using any image organization software to manipulate your local library after you have downloaded images from iCloud, there is a very high chance that such software will use image date/time from EXIF tag in the image and not from folder/file name/attributes. From that perspective creating subfolders with dates is mostly needed for 1) huge collections so filesystem does not choke on large folders 2) avoiding image duplication when image numbering is cycling

**Comment by AndreyNikiforov** [comment]
no response from requestor. closing
