### ISSUE TITLE
Delete files I deleted from iCloud

### ISSUE THREAD

**Issue by thedinz** [icloud-photos-downloader/icloud_photos_downloader#722]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
It seems simply enough but I have toggled various delete options on and off in the config but when icloudpd runs, it will not remove photos I have removed from iCloud, which is actually what im looking for, more of a true sync scenario.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
I thought this is the way it worked or COULD work and maybe it does but im not understanding the correct settings to enabled for it to work this way.
I am running this on unraid if that matters.

**Comment by AndreyNikiforov** [comment]
@thedinz what parameters are you using for icloudpd? icloudpd does not have configs, so I am not sure what delete options you are talking about.

**Comment by thedinz** [comment]
I am sorry I am on the wrong GitHub page *facepalm*
