### ISSUE TITLE
Path not readable

### ISSUE THREAD

**Issue by osmaterdca** [icloud-photos-downloader/icloud_photos_downloader#737]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
I'm unable to get the sync working on my Synology NAS despite the path to the download folder incl .mounted file is present

Here is my download folder  with .mounted file  : 
![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/133154466/7b31ae4a-dc28-4f4d-bf9d-1758c02323de)

Here is my docker parameters :
![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/133154466/0f7d8491-1939-4869-ac0a-101c5632ab20)

Here is the log error :
![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/133154466/d725d96d-e889-4fcb-bf00-9a7e7d5aad61)

I know a surely missed something but I can't find what :(

Thanks a lot for your help.

**Comment by Greymean** [comment]
Because your folder name is wrong :) iCloud not ICloud
