### ISSUE TITLE
Error: Invalid value for '-d' / '--directory': Path 'P:\\Photos\\neu\\09 Delta iClouds\\Steffi' does not exist.

### ISSUE THREAD

**Issue by fischmir** [icloud-photos-downloader/icloud_photos_downloader#739]
## Overview
I was using icloudpd for a long time on my old machine. Now I purchased a new machine and I am re-installing everything. So I am basically trying to get this running for the first time on this machine.

## Steps to Reproduce
1. Create  share on synology
2.  Map that share into Win11
3. Use this share as directory 

## Expected Behavior
Find the directory, even if it resides on a syno.

## Actual Behavior
Error:
![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/29099751/ecc8e912-eabc-4578-97ad-082f0afb64ff)

## Context
If I try a local folder, I receive another error message:

![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/29099751/87cd3c16-3f16-48ab-b32c-9d13c200f000)

This is not good as well, but at least the local folder is found. I am wondering, why the folder on the synology is not found.

**Comment by AndreyNikiforov** [comment]
Try a) local path b) path without spaces. Hope that should narrow down the problem

Note that Apple auth changeed recently and `icloudpd` cannot authenticate. #729

**Comment by fischmir** [comment]
Not reproducable with 1.17.2 => solved
