### ISSUE TITLE
Container on Synology NAS does not start

### ISSUE THREAD

**Issue by git-newbe** [icloud-photos-downloader/icloud_photos_downloader#762]
Hi,
in the past i successfully used Icloudpd 1.8.1. But somehow I'm not able to fix the keystore topic (https://github.com/OrZidkani/icloudpd_auth_fix)
.
I now tried to download the latest version 1.17.2 but this does not even start. The container stops shortly after startup with nearly no message:

2024/01/03 14:46:08 | stdout | watch     Watch for iCloud changes
2024/01/03 14:46:08 | stdout | move      Move assets from iCloud to local storage
2024/01/03 14:46:08 | stdout | icloudpd  Download all iCloud photos to a local directory
2024/01/03 14:46:08 | stdout | icloud    Legacy iCloud utils (keyring)
2024/01/03 14:46:08 | stdout | copy      Copy assets from iCloud to local storage
2024/01/03 14:46:08 | stdout | auth      Manages persistant credentials
2024/01/03 14:46:08 | stdout | Commands:
2024/01/03 14:46:08 | stdout |  
2024/01/03 14:46:08 | stdout | --help  Show this message and exit.
2024/01/03 14:46:08 | stdout | Options:
2024/01/03 14:46:08 | stdout |  
2024/01/03 14:46:08 | stdout | Usage: icloudpd_ex [OPTIONS] COMMAND [ARGS]...

![Screenshot 2024-01-03 144726_new](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/2ac1bda7-680f-4823-814e-120e05365301)

Could it be that it is related to ENTRYPOINT? in the previous version this was not part of docker image.

**Comment by git-newbe** [comment]
Hi,

I tried a bit around and the last version that I can start is: 1.10.0
All later versions stop running unexpected immediately after I try to start the docker.

The only difference is, all versions below 1.10.0 using:
command: /bin/sh

versions 1.11.0 ++
Entrypoint: /app/exec

Could we change this back to /bin/sh?

**Comment by AndreyNikiforov** [comment]
entrypoint is something that is running inside the container. for icloudpd to do something meaningful, you need to supply parameters, e.g. username.  the oouput you gave suggests that parameters are not configured and you are given help info.

example params: "icloudpd -u your@address -d . --dry-run". note "icloudpd" as part of param. these params should be set somewhere in dsm ui

**Comment by AndreyNikiforov** [comment]
I just tried on linux:
```
~$ docker run --rm -it icloudpd/icloudpd:1.8.0 icloudpd -u dummy@add -p abc -d .
2024-01-05 07:44:04 DEBUG    Authenticating...
Traceback (most recent call last):
  File "pyicloud_ipd/base.py", line 209, in authenticate
  File "requests/sessions.py", line 635, in post
  File "pyicloud_ipd/base.py", line 100, in request
  File "pyicloud_ipd/base.py", line 122, in _raise_error
pyicloud_ipd.exceptions.PyiCloudAPIResponseError: Unknown reason
```
log suggests that icloudpd started and tried to authenticate (and failed since my email and passwords were bogus)

**Comment by git-newbe** [comment]
let me show you - what setup I have

1. Docker
![Docker_ui](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/b81d901a-a319-4425-86be-973d79cae800)
2. my script
![Script_icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/362b7a9a-62d5-453c-b3d7-41197e89e743)
3. Scheduler
![Scheduler_icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/acb0e528-a138-4429-88e5-36ab05ca6ffd)
4. Log
![Log_icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/86198d1d-97af-4863-913d-af86348ff676)

Doing it with version below 1.10.0 was working.

**Comment by git-newbe** [comment]
Let me show you the setup that was working for all versions below 1.10.0 (with commands). Please bear with me - I don't have that much experience :)

1. Docker Setup:

![Docker_ui](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/8003d68f-f5bf-4c18-9c81-03e828fccfa3)

2. Script (now a short one - usually filled with folder details, structure, etc.)

![Script_icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/32fd4946-7975-4084-af58-2d2baa6d0127)

3. Schedule setup

![Scheduler_icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/608a7b4c-0146-4eb6-9626-420b24caf30f)

4. Log 

![Log_icloudpd](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/123659661/fef31f52-331a-45fc-839e-02da920d6cdd)

Again, I can not simply start the docker image via ui to get a console to e.g. setup keyring. It directly stops working shortly after pressing START button.

Previously it worked :)

Thanks.

**Comment by AndreyNikiforov** [comment]
I cannot read language in UI (German?), nor do I know much about Synology. With that in mind let's see how far we can go.

To start container from image, one has to specify a) image b) setup for container c) parameters for the in container (if any). For icloudpd:
- image is "icloudpd/icloudpd:1.17.3" and it is specified in UI on screen 1
- setup for container includes volume mapping between host and container (default is full isolation) and UI has that on screen 1
- parameters for icloudpd itself specified in screen 2 are incomplete as "-d" is required. Should be "icloudpd -u aaa -p bbb -d /icloud"

All three component should be provided together to start container. you can either put full "docker run ..." cmd in icloudpd.sh and than run that shell script from scheduler or avoid shell script all together and use "docker run ..." in scheduler setup, but splitting functionality as shown on screens 2 & 3 would not work IIUC.

Screen 3 shows start, exec, and stop command, I would recommend using on one "docker run" instead. I don't understand how Synology UI combines image and setup from screen 1 with cmd in screen 3. Screen 3 with all combined should look: "docker --rm -i -v /volume1/docker/icloud:/icloud:rw -e TZ=UTC icloudpd/icloudpd:1.17.3 icloudpd -u aaa -p bbb -d /icloud".

You can also use "--watch-with=interval 3600" parameter and avoid using scheduler all together - icloudpd will run infinitely and synchronize icloud content to your drive periodically.

**Comment by AndreyNikiforov** [comment]
I see that DSM has support for docker-compose (called [container projects](https://kb.synology.com/en-br/DSM/help/ContainerManager/docker_project?version=7)). That may be easier to setup in UI.

Docker-compose is a simplest way to orchestrate containers. Once you define "service" with all params we supplied to "docker run", you can use start and stop cmds (without repeatedly specifying params again). Should work well with "--watch-with-interval" param as with it icloudpd becomes a service that runs until stopped.

**Comment by git-newbe** [comment]
Hey Andrey,

Let me check this. If you can spare some time would it be possible to have
a screen sharing session:-)?

Thanks
Roman

Andrey Nikiforov ***@***.***> schrieb am Fr. 5. Jan. 2024 um
17:45:

**Comment by git-newbe** [comment]
Hi – its me again😂

I think we compare apples and pears.
What I used in the past and that was working perfectly fine is the approach I described above. Till entrypoint was introduced 😂

1. Set up a container in docker gui
2. Started the container from gui and connected to Terminal
3. Within the docker I configured keyring and could execute icloudpd with parameter to download the images

later I configured the scheduler to download images by handing over the icloudpd parameter statement via a script. Only from time to time I need to do 2.) to re-setup keyring.
I always re-used the same container.

Now since you introduced entrypoint I have no chance to simply start the container and access the shell inside the container to configure e.g. keyring.

the approach with:
docker run --rm -i -v /volume1/docker/icloud:/icloud:rw -e TZ=UTC icloudpd/icloudpd:1.17.3 icloudpd -u aaa -p bbb -d /icloud
was indeed working but how can I then leverage keyring to not have password in clear text.

Best 
Roman

**Comment by boredazfcuk** [comment]
```
docker run --rm --entrypoint /bin/ash -i -v ./test:/icloud:rw -e TZ=UTC icloudpd/icloudpd:1.17.3
```

**Comment by AndreyNikiforov** [comment]
As mentioned above by @boredazfcuk , you can get command prompt into container by overriding entrypoint. Here is my session:
```
[~]$ docker run --rm -it --entrypoint /bin/sh icloudpd/icloudpd:1.17.3
Unable to find image 'icloudpd/icloudpd:1.17.3' locally
1.17.3: Pulling from icloudpd/icloudpd
c926b61bad3b: Already exists
f821361375b1: Pull complete
e619753a56d7: Pull complete
eb0652d33051: Pull complete
4f4fb700ef54: Pull complete
2647709a09f9: Pull complete
Digest: sha256:c28e9ac5bae49122bd8007be7d89582e793434341c539b7d1244f2e3bcb52898
Status: Downloaded newer image for icloudpd/icloudpd:1.17.3
/app # ls
icloudpd_ex
/app # icloudpd_ex --help
/bin/sh: icloudpd_ex: not found
/app # ./icloudpd_ex --help
Usage: icloudpd-ex-1.17.3-linux-amd64.dynamic [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  auth      Manages persistant credentials
  copy      Copy assets from iCloud to local storage
  icloud    Legacy iCloud utils (keyring)
  icloudpd  Download all iCloud photos to a local directory
  move      Move assets from iCloud to local storage
  watch     Watch for iCloud changes
/app #
```

Note that "script" that is packaged inside docker container is called `icloudpd_ex`, not `icloudpd`, and it accepts `icloudpd` and `icloud` commands (the rest of commands are experimental), so you have to run it as `./icloudpd_ex icloudpd -u aaa -p bbb -d /icloud` as if `icloudpd_ex` is another shell. To manage keyring you'll use `./icloudpd_ex icloud`.

Note: I don't use keyring, so I cannot comment on the expected behavior of keyring inside the container.

**Comment by git-newbe** [comment]
Thanks guys / I will try it tomorrow but your way is still different as I used in the past.

The docker run command runs a command in a new container, pulling the image if needed and starting the container with parameters.

I used to restart a stopped container with all its previous changes intact using docker start out of scheduler or via docker gui app. Main reason was to have keyring within docker not touching the NAS os.

But as docker start command obviously does not allow to over right entry point it will not work anymore. Then I only have chance to give Passwort in clear text via script.

**Comment by AndreyNikiforov** [comment]
You may be able to start container with new entrypoint and then reuse it -- you have to experiment.

**Comment by boredazfcuk** [comment]
> The docker run command runs a command in a new container, pulling the image if needed and starting the container with parameters.

Your run command contains `--rm`. This removes the container after it exits, including the keyring file and cookie that is created inside your container as they do not live in the path which you have mapped to persistent storage (/icloud)

> I used to restart a stopped container with all its previous changes intact using docker start out of scheduler or via docker gui app. Main reason was to have keyring within docker not touching the NAS os.

Then your previous container could not have been created with the `--rm` command line parameter. If a container is run with this parameter, it is deleted when the container is next stopped.

> But as docker start command obviously does not allow to over right entry point it will not work anymore. Then I only have chance to give Passwort in clear text via script.

Using `--entrypoint /bin/ash` overwrites the entrypoint inside the container.

**Comment by git-newbe** [comment]
Exactly I did not used —rm this came from Andrey 😀

I just downloaded the image once from GitHub.
Created a container via gui assistant and mapped some folders and pressed the START button. 
Then the container was running and I could connect via Terminal from Docker gui to the container. The keyring setup / cookie was stored in mapped folder. Afterwards I could press STOP container button.

When I want to download pictures I just had 3 commands in my scheduler taskplaner.

1.) docker start [containername]
2.) sh [script icloudpd with all parameters] stored in mounted folders
3.) docker stop [containername]

🤓

**Comment by boredazfcuk** [comment]
Give this a go:
```
docker create --name icloudpd --interactive --entrypoint /usr/bin/env -v /volume1/docker/icloud:/icloud:rw -e TZ=UTC icloudpd/icloudpd:1.17.3 /bin/ash
docker start icloudpd
docker exec -it icloudpd /bin/ash
```

This should get you a terminal prompt in the running container.

**Comment by git-newbe** [comment]
Hi both,
Thank for your great support.
@boredazfcuk: This is the statement I needed:

docker create --name icloudpd --interactive --entrypoint /usr/bin/env -v /volume1/docker/icloud:/icloud:rw  -e TZ=UTC icloudpd/icloudpd:latest /bin/sh

With running this statement once via taskplanner I can create a container into Synology docker app that can simply started and stopped! I can also simply connect to terminal via this app to do Keyring setup.

I simply cannot use the Synology Docker App Assistant anymore to create a container as I can not give the relevant parameters. But this is absolutely fine to do it once via a Taskplanner script or SSH.

Thanks again!!
