### ISSUE TITLE
[Latest Edits] Allow downloading of edited files

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#769]
## Summary
Currently icloud_photos_downloader downloads the original version of the files stored in iCloud. This means that the current version of the files cannot be downloaded if they have been edited, or if filters have been applied (e.g. portrait).

I presume that icloud_photos_downloader is emulating the file download by selecting the "Download" option for each file:
![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/14807258/cd98001c-0c0f-4738-a9a2-1f4a79264bd6)

However, if the `More download options...` option is selected, three choices are presented; Unmodified Original, Including Edits - Highest Resolution & Including Edits - Most Compatible:
![image](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/14807258/a9bdd4a2-785c-41cb-9e78-4e61e5ee1a2d)

Unmodified Original is basically the same as clicking Download, from what I can tell.
Including Edits :-
     - Highest Resolution: This will download HEIC files, except when the file has been edited, in which case a JPEG file is downloaded
     - Most Compatible: This will download JPEG files every time.

## Context
If the behaviour of icloud_photos_downloader is changed so that it selects the "Including Edits - Highest Resolution" option, the downloaded photo stream will more accurately represent what the user sees on icloud.com.

**Comment by AndreyNikiforov** [comment]
#704 #350 #249

**Comment by AndreyNikiforov** [comment]
1.19.0 can download adjusted files (edits, portraits etc)
