### ISSUE TITLE
Can't login "Bad username or password for"

### ISSUE THREAD

**Issue by theikid** [icloud-photos-downloader/icloud_photos_downloader#771]
Hi there, I'm using icloudpd on my truenas scale install through truecharts catalog.  I manage to launch the "--Initialise" script but when trying to enter my password it throw an error "Bad username or password for xxxx@xxxx". I've seen that the problem was supposed to be fixed a few version ago (during December". I've checked with the docker image creator which say it is up to date and on btruecharts side it's also supposed to be uptodate. 

I'm wondering if Apple broke again the MFA login ? I have change twice my password of my appleid to be sure but I can login elsewhere.

**Comment by boredazfcuk** [comment]
For reference:

https://github.com/boredazfcuk/docker-icloudpd/issues/476

**Comment by theikid** [comment]
Any update on this possible ?

**Comment by AndreyNikiforov** [comment]
> Any update on this possible ?

pls use https://github.com/boredazfcuk/docker-icloudpd/ repo for issues with that distribution.
