### ISSUE TITLE
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseError('Unknown reason'))

### ISSUE THREAD

**Issue by AlexaAmaya** [icloud-photos-downloader/icloud_photos_downloader#790]
<img width="1032" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/109637800/1e01b9e2-d909-40ea-8826-22c69c25ba87">

After the massive 7/12/23 bug, my containers stopped his downloading, I did a reinstall of the docker's files, but it shows the following error, any assistance to help me would be greatly appreciated ~
:-)

**Comment by SinoBoeckmann** [comment]
Hey, same issue here. 100% sure, that the password/mail combination is correct.
Are there any other information required, to have a look into this?

Thank you!

**Comment by Mintume** [comment]
facing the same issue

**Comment by norton-chris** [comment]
Same issue here, but I tested a bunch of iCloud account and got one of my family member's accounts to work. So I wonder if there's some subtle difference in accounts that won't allow the iCloud API to go through. (I don't know much about the API or this project, I have just been testing the docker command.)

**Comment by Mintume** [comment]
Finally, this issue is gone and everything is working great with 1.7.4 released yesterday.

**Comment by SinoBoeckmann** [comment]
Thank you very much! Is there any "buy me a coffee" button, somewhere? 😉

**Comment by AndreyNikiforov** [comment]
Is this issue still relevant?

**Comment by Hexpertise** [comment]
Sorry - I'm afraid, it is still relevant. I faced this issue just few days ago with one of my accounts. Three family apple accounts worked as expected. One failed with the error message above. I've changed icloud-password (a new username/password combination) but it still fails with regards to this account. It fails directly in CLI using bash with npx ... --auth-only parameter. 
I've configured my server to send me an email, if an command failes automatically. Unfortunately this will expose apple-id and passwords from commandline/script (which are I think necessary to use in my cron-triggerd mechanism) in clear text. Failed command (with clear text password) are also exposed to server logs. For security reasons I've deactivated sendmail for this cases und also icloudpd !!!. I like your software much, but you should find an alternative authentication method (account defined app keys?) to access icloud without the effortness exposing any passwords (in clear text).

**Comment by AndreyNikiforov** [comment]
> Sorry - I'm afraid, it is still relevant. I faced this issue just few days ago with one of my accounts. Three family apple accounts worked as expected. One failed with the error message above. I've changed icloud-password (a new username/password combination) but it still fails with regards to this account. It fails directly in CLI using bash with npx ... --auth-only parameter. I've configured my server to send me an email, if an command failes automatically. Unfortunately this will expose apple-id and passwords from commandline/script (which are I think necessary to use in my cron-triggerd mechanism) in clear text. Failed command (with clear text password) are also exposed to server logs. For security reasons I've deactivated sendmail for this cases und also icloudpd !!!. I like your software much, but you should find an alternative authentication method (account defined app keys?) to access icloud without the effortness exposing any passwords (in clear text).

There are [four ways](https://icloud-photos-downloader.github.io/icloud_photos_downloader/authentication.html#password-providers) to provide password for `icloudpd`, use the one that works best for you
