### ISSUE TITLE
No JPG downloaded

### ISSUE THREAD

**Issue by Nexius2** [icloud-photos-downloader/icloud_photos_downloader#791]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Hello, I just noticed icloupd stop downloding JPG files taken from my iphone. (jpeg via whatsapp are downloaded)
video and heic are downloaded, everything is ok, but i have no jpg. I don't understand why.

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
my settings:
Time Zone: Europe/Paris
set_exif_datetime: true
convert_heic_to_jpeg: true 
jpeg_quality: 100
folder_structure: {:%Y/%Y-%m-%d}
until_found: 1

**Comment by AndreyNikiforov** [comment]
What cmd are you using? What version of icloudpd and where are you getting it? icloudpd does not take settings in any form other than parameters, so context in your post confuses me.

**Comment by Nexius2** [comment]
Hello, it is a docker container, no command.
I removed every option, made it run and put back everything as is... seems to work
no idea what happened.
thanks
