### ISSUE TITLE
Thinks it's a find my iphone command line tool

### ISSUE THREAD

**Issue by theredhoodedthot** [icloud-photos-downloader/icloud_photos_downloader#794]
I don't know how to install the tool so I've been dragging and dropping it into the terminal. Every time i try to add a directory it says it doesn't recognize the argument. It won't use --auth-only either. When using -h, before it lists the options it says "Find My iPhone CommandLine Tool" I'm on a fresh install of linux mint 21.3, and it worked fine when i had 20.3.

**Comment by alexspringgit** [comment]
Hi, perhaps you downloaded an icloud binary instead of the icloudpd one. Try downloading icloudpd from the release page after clicking "Show all 60 assets."

**Comment by AndreyNikiforov** [comment]
> I don't know how to install the tool so I've been dragging and dropping it into the terminal.

I assume you are using Windows. To get to console (~= terminal, command line) on windows: press Win+R, type "cmd" in popup window, and click "Ok". To start a program in console, you need to type its name (with the path) and parameters (if applicable), e.g. "icloudpd --help". As mentioned in the [tip](https://github.com/icloud-photos-downloader/icloud_photos_downloader#usage), use "icloudpd", not "icloud"
