### ISSUE TITLE
Group ID alrady in use

### ISSUE THREAD

**Issue by jbeck22** [icloud-photos-downloader/icloud_photos_downloader#799]
I'm installing on unRaid 6.12.4 using Docker. 

When I run sync-icloud.sh --Initialise I get the following error:

`2024-03-06 14:09:55 ERROR    Group id, 100, already in use by the group: group - exiting. If you must to add your user to this pre-existing system group, please set the force_gid variable to True`

**Comment by latel** [comment]
same here, must be lowercase

**Comment by AndreyNikiforov** [comment]
`sync-icloud.sh` is not part of this repo. pls use another repo to report issues.
