### ISSUE TITLE
[Idea] Duplicate photo remover

### ISSUE THREAD

**Issue by brandonros** [icloud-photos-downloader/icloud_photos_downloader#80]
So... I am probably not the only person with this problem, but somewhere between having an iPhone 3G and an iPhone 8 (and however many versions of Mac OS X in between, across multiple machines none the less), my photos collection got messed up. I have duplicates scattered throughout my library (not easily sortable by date unfortunately...), and none of the duplicate photo removal tools out there work (probably because half of my library is on my machine, and half is in iCloud... or wherever the fault/shortcoming may be)

So... my idea was, to run this script, then pipe the downloaded images to Imagemagick's identify perceptual hash function. From there, I'd filter out duplicates, yada yada. The only missing piece of the puzzle in my eyes is... once I've identified what filenames I want to delete... how do I turn around and remove them from iCloud in a programmatic fashion? It is clear to me that your script is a read-only one way pull from iCloud, but I figured I'd ask if you had any ideas on how to implement a "remove X files from my library", if it wasn't already supported someway by this code in a hidden fashion.

Thanks!

**Comment by ndbroadbent** [comment]
That's a great idea! I've used a tool on my Mac to remove some duplicate photos in the past. But would be great if this could be done with a script.

This script just uses the [pyicloud](https://github.com/picklepete/pyicloud) library for authentication and fetching photos, but looks like [they don't have any function to delete photos](https://github.com/picklepete/pyicloud/blob/master/pyicloud/services/photos.py). I would use something like [Charles Proxy](https://www.charlesproxy.com/) to record API requests from the Photos app on your computer or phone, and then add a function for that to `pyicloud`.

**Comment by brandonros** [comment]
Do they have a function to add a photo to a specific folder/album, or to tag it?

**Comment by ndbroadbent** [comment]
Oh wait! I just remembered this example I saw a while ago, from someone who already implemented these API calls: https://gist.github.com/Tatsh/0b5a10a2d25f6c8466290401d2026055

They wrote that to delete all their photos, but you could use that as a starting point.

It was a while ago, but I think it was this one: [Duplicate File Finder](https://nektony.com/duplicate-finder-free). Now that I think about it, I think I was just removing duplicate files from other folders (e.g. Downloads, Dropbox), and it doesn't look like it integrates with the Photos library.

**Comment by brandonros** [comment]
The download is pretty slow. Any plans of adding parallelism to the downloading?

**Comment by ndbroadbent** [comment]
That's a good idea. If Apple is limiting the download speed for photos, then it would make sense to download 3-5 in parallel. I don't have any time to add parallelism at the moment, but had a quick look at the `tqdm` progress bar and it will support [nested progress bars for each thread](https://github.com/tqdm/tqdm#nested-progress-bars). But yes that would be a good feature to have

**Comment by ndbroadbent** [comment]
I also like the duplicate photo removing feature so will reopen this issue

**Comment by brandonros** [comment]
```
#!/bin/bash
# 
# Developed by Fred Weinhaus 7/7/2014 .......... revised 4/25/2015
# 
# ------------------------------------------------------------------------------
# 
# Licensing:
# 
# Copyright © Fred Weinhaus
# 
# My scripts are available free of charge for non-commercial use, ONLY.
# 
# For use of my scripts in commercial (for-profit) environments or 
# non-free applications, please contact me (Fred Weinhaus) for 
# licensing arrangements. My email address is fmw at alink dot net.
# 
# If you: 1) redistribute, 2) incorporate any of these scripts into other 
# free applications or 3) reprogram them in another scripting language, 
# then you must contact me for permission, especially if the result might 
# be used in a commercial or for-profit environment.
# 
# My scripts are also subject, in a subordinate manner, to the ImageMagick 
# license, which can be found at: http://www.imagemagick.org/script/license.php
# 
# ------------------------------------------------------------------------------
# 
####
#

infile="$1"

# syntax: phashconvert imagefile


# get 42 values from each image and put into arrays
# first: grep verbose info to get all lines that include PH
# second: sed returns the pairs of comma separated values
# third: sed removes all spaces
# fourth: tr converts comma to new line so all values are on their own line
# then convert list of values to arr


arr1=(`identify -quiet -verbose -moments -alpha off "$infile[0]" | grep "PH[1-7]" | sed -n 's/.*: \(.*\)$/\1/p' | sed 's/ *//g' | tr "," "\n"`)
num1="${#arr1[*]}"
#echo $num1

# test for correct number of values
if [ $num1 -ne 42 ]; then
	echo "--- Number of Phash Values ($num1) is Incorrect --- "
	exit 1
fi


# convert 42 values into string of 168 digits as hash using 4 digits for each float
hash1=""
for ((i=0; i<42; i++)); do
# bc cannot handle scientific notation; have to change e to 10^
#val1=`printf %0004d $(echo "scale=0; if (${arr1[$i]}<0) 100*(${arr1[$i]}-0.005)/1 else 100*(${arr1[$i]}+0.005)/1" | bc)`
val1=`echo "${arr1[$i]}" |\
	awk ' { printf "%0004d", ($1<0)?100*($1-0.005):100*($1+0.005) } '`
hash1="${hash1}${val1}"
done

echo "$1 $hash1"

exit 0
```

I used this to get a "visual hash" for all photos.

**Comment by ndbroadbent** [comment]
Thanks! Interesting that it's just a bash script and uses imagemagick. I've used the [pHash](http://phash.org/) library before, and the [phashion Ruby library](https://github.com/westonplatter/phashion) makes it easy to install.

This Python library looks pretty good too: https://github.com/JohannesBuchner/imagehash

Also interesting to read about [how pHash works](http://www.hackerfactor.com/blog/index.php?/archives/432-Looks-Like-It.html), I didn't realize it was such a simple algorithm.

**Comment by AndreyNikiforov** [comment]
Current scope of the tool is to download photos. Two way synchronization is not on a roadmap and will have at least two challenges:
1. support for deletion in API libs
1. detrimental impact is may have if used by mistake

Closing the issue
