### ISSUE TITLE
Images not getting deleted in Shared LIbrary with delete_after_download=true

### ISSUE THREAD

**Issue by b00llean** [icloud-photos-downloader/icloud_photos_downloader#802]
## Overview
Images are not getting deleted when Shared Library is used and delete_after_download is set to true. 

## Steps to Reproduce
1.  Supply delete_after_download=true command line optio, auto_delete=false, photo_library=SharedSync-CA6C4E18-xxxxxxxx
2.  Observe debug messages in logfile . Example:

2024-03-11 22:25:13 INFO     Deleted IMG_2225.HEIC in iCloud

4.  Observe downloaded (and per log messaged deleted) mages remain in "Shared Library" in iCloud on all devices. Verified via web access to iCloud. Nothing gets deleted automatically. 

## Expected Behavior
Downloaded images are expected to disappear from "Shared Library"

## Actual Behavior
Downloaded images remain visible in "Shared Library". If deleted locally, icloudpd re-downloads them from "Shared Library"

## Context
I tried latest version of icloudpd to run on native os paython and within docker - same behavior.

**Comment by AndreyNikiforov** [comment]
What version of icloudpd are you using, how are you getting it (docker, binary etc; what location, image name), what parameters are you using? The parameters you provided suggested that you may be using images from other projects. If you give full cmd line with minimum set of params reproducing the issue, it may give others better idea how to help too.

Re "Shared libs": I don't use it myself and saw reports in GH suggesting that SL may have some unexpected behavior.

**Comment by b00llean** [comment]
Sure, 

Here is the command line that is being used in docker version and what I've tried to use in command line in "bare" install:
`icloudpd --directory /photo_archive --cookie-directory /config --domain com --username xxxxxxx@icloud.com --no-progress-bar --delete-after-download --skip-videos --folder-structure SharedSync-xxxxxxxxxxx/{:%Y/%Y-%m/%Y-%m-%d} --library SharedSync-xxxxxxxxxxxx`

**Comment by AndreyNikiforov** [comment]
From what I can tell current code [supports deleting from PrimarySync only](https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/28188c3b371e54e734cbaf4e261cad34081ff93f/src/icloudpd/base.py#L631)

**Comment by b00llean** [comment]
Evidently so. 

Should this be a bug or an RFE?

**Comment by AndreyNikiforov** [comment]
It has never been implemented, so RFE seems better suited.

**Comment by AndreyNikiforov** [comment]
fixed in 1.17.7. reopen if issue persists
