### ISSUE TITLE
Just trying to get started, no dice. 

### ISSUE THREAD

**Issue by Biggles94** [icloud-photos-downloader/icloud_photos_downloader#821]
## Summary
[NOTE]: # Hey, running windows10(x64) on intel. 

I logged in on my first run of the script, and even input the 2FA code successfully. Everything past that I cannot figure out, though.

The instructions for usage state:
To keep your iCloud photo collection synchronized to your local system:

icloudpd --directory /data --username my@email.address --watch-with-interval 3600

So, I put into cmd 
icloudpd.exe --username myacct --password mypassword --directory E:\2024phone\cmdthing  --watch-with-interval 3600

which output 
icloudpd.exe: error: unrecognized arguments: --directory E:\2024phone\cmdthing --watch-with-interval 3600

I even tried using the -d [path] instead of --directory and it still told me unrecognized arguments. 

I do not understand anything inside of the FAQ or issues threads that relates to figuring out how to use this script to do the very most baseline function with it: sync the icloud storage onto the specified directory path.

**Comment by AndreyNikiforov** [comment]
Since it complains about parameters starting with `--directory` I suspect that your password may have special characters that Windows misinterpreting somehow. If you don't use `--password` parameter, then you will be prompted for password - pls see if that helps.

**Comment by Biggles94** [comment]
The password had a ! in it, so I changed it to _. but, the error is still there even when I try to not put the password paremeter in. 

icloudpd.exe --username myacct --directory E:\2024phone\cmdthing --watch-with-interval 3600

outputs the error:

icloudpd.exe: error: unrecognized arguments: --directory E:\2024phone\cmdthing --watch-with-interval 3600

**Comment by AndreyNikiforov** [comment]
Where did you get .exe file? If from Github, then which one did you download and renamed to `icloudpd.exe`?

`icloud.exe` does not have `--directory` parameter and shows such error (also shows all supported parameters), but `icloudpd.exe` supports it.

**Comment by gryzzly** [comment]
I have the same issue with the macOS binary downloaded just now: 

```
./icloud-1.17.4-macos-amd64 --directory icloud --username foo-bar@gmail.com --watch-with-interval 3600
> icloud-1.17.4-macos-amd64: error: unrecognized arguments: --directory icloud --watch-with-interval 3600
```

**Comment by gryzzly** [comment]
and help flag `-h` doesn’t print directory or watch-with-interval as valid options at all: 
```
usage: icloud-1.17.4-macos-amd64 [-h] [--username USERNAME] [--password PASSWORD] [-n]
                                 [--delete-from-keyring] [--list] [--llist] [--locate]
                                 [--device DEVICE_ID] [--sound] [--message MESSAGE]
                                 [--silentmessage SILENTMESSAGE] [--lostmode]
                                 [--lostphone LOST_PHONE] [--lostpassword LOST_PASSWORD]
                                 [--lostmessage LOST_MESSAGE] [--outputfile] [--domain DOMAIN]
```

**Comment by AndreyNikiforov** [comment]
use `icloudpd`, not `icloud` executable. [see](https://github.com/icloud-photos-downloader/icloud_photos_downloader#usage)

**Comment by AndreyNikiforov** [comment]
@Biggles94 do you still experience this issue?
