### ISSUE TITLE
Can rogue items occur??

### ISSUE THREAD

**Issue by robdejonge** [icloud-photos-downloader/icloud_photos_downloader#827]
## Summary
I wondered this morning what would happen to 'rogue files' in the `--directory` location. Meaning, does icloudpd do anything to those files to ensure a clean backup location? So I placed one and ran icloudpd, and checked after and the file was still there. No mention of it in the log output either. 

This made me also wonder ... if I use the `--auto-delete` mode, icloudpd downloads everything on iCloud and deletes anything marked as _Recently Deleted_. But what happens to files that on a previous sync existed, but then were manually deleted AND deleted from the Recently Deleted folder. Would those files become orphaned of sorts and live within the backup location forever? 

It could very well be that iCloud provides this information somehow and this is all handled gracefully. But the initial experiment made me wonder if it is possible. 

## Context
Potentially this creates a bunch of files that take up wasted space. But there is a follow-up question to this as well, which I'll submit for discussion once I have the answer to the above.

**Comment by AndreyNikiforov** [comment]
`icloudpd` has [three modes of operation](https://github.com/icloud-photos-downloader/icloud_photos_downloader#features):
- Copy - download new photos from iCloud (default mode)
- Sync - download new photos from iCloud and delete local files that were removed in iCloud (--auto-delete option)
- Move - download new photos from iCloud and delete photos in iCloud (--delete-after-download option)

It deletes local files only when it was instructed to do so (`--auto-delete`) and files to delete are in Recently Deleted folder in iCloud. In all other cases, `icloudpd` is oblivious to other local files.
