### ISSUE TITLE
Container Stopped Unexpectedly 

### ISSUE THREAD

**Issue by Jholmgren5** [icloud-photos-downloader/icloud_photos_downloader#828]
When running the latest container version within Docker, container stoped working unexpectedly, within 2 seconds of running. Using Synology NAS, running Docker, using the latest build of icloudpd

I go through the setup process, download the image, run it, the only change I make is setting the folder path for the photos to be downloaded, /photo.  I run the container, and synology give me a notification and the container stops unexpectedly. 

If there a config somewhere I am missing?

**Comment by Jholmgren5** [comment]
Here is the log for the container: 

2024/04/30 10:36:11 | stdout | watch     Watch for iCloud changes
2024/04/30 10:36:11 | stdout | move      Move assets from iCloud to local storage
2024/04/30 10:36:11 | stdout | icloudpd  Download all iCloud photos to a local directory
2024/04/30 10:36:11 | stdout | icloud    Legacy iCloud utils (keyring)
2024/04/30 10:36:11 | stdout | copy      Copy assets from iCloud to local storage
2024/04/30 10:36:11 | stdout | auth      Manages persistant credentials
2024/04/30 10:36:11 | stdout | Commands:
2024/04/30 10:36:11 | stdout |  
2024/04/30 10:36:11 | stdout | --help  Show this message and exit.
2024/04/30 10:36:11 | stdout | Options:
2024/04/30 10:36:11 | stdout |  
2024/04/30 10:36:11 | stdout | Usage: icloudpd-ex [OPTIONS] COMMAND [ARGS]...

**Comment by AndreyNikiforov** [comment]
What version of container are you using? What command line options are you providing?

"Usage: icloudpd-ex" suggests to me that you are not using the latest version and do not provide `icloudpd` cmd - see [example](https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/README_DOCKER.md)

**Comment by Jholmgren5** [comment]
All set.  It was an issue with DSM permissions.  Thanks for the reply, I appreciate it!

**Comment by Jholmgren5** [comment]
All set. It was an issue with DSM permissions. Thanks for the reply, I appreciate it!
