### ISSUE TITLE
iCloudPD needs to check expiration date before initialization

### ISSUE THREAD

**Issue by CreativePR** [icloud-photos-downloader/icloud_photos_downloader#829]
## Overview
Now iCloudPD will try to run regardless if the cookie has expired.  If iCloudPD is ran in an automated fashion, this will result in the user receiving multiple verification codes over and over depending if iCloudPD is ran at an automatic interval.

IcloudPD should 1st check the cookie for the expiration date and if it is past thrown an error,  do not try to authenticate, and send the email (if so configured)

**Comment by AndreyNikiforov** [comment]
What automated fashion are you referring to? `--watch-with-interval` param? If not, how are you executing `icloudpd` and it what moment you are getting repeated 2fa codes?

If you are running `icloudpd` periodically by external scheduler, then I assume each run will be blocked until you enter 2fa code and no subsequent attempts to authenticate will be made. If external scheduling starts another instance of `icloudpd` while prev is blocked waiting for user input, fixing scheduling is probably an appropriate step.

**Comment by AndreyNikiforov** [comment]
closing due to no response from requestor
