### ISSUE TITLE
x86 1.17.5: "--help" option returns help for 'Find My iPhone CommandLine Tool', not iCloudPD

### ISSUE THREAD

**Issue by Speedbird979** [icloud-photos-downloader/icloud_photos_downloader#833]
As topic, 

downloaded x86 1.17.5 this morning as a first time user, tried to get working - partial success. 

Wanted to check what options/parameters to pass as 'ReadMe' on here lacking examples.

Running 'file.exe --help' returns the below:

I:\>icloud-1.17.5-windows-amd64.exe --help
usage: icloud-1.17.5-windows-amd64.exe [-h] [--username USERNAME] [--password PASSWORD] [-n] [--delete-from-keyring]
                                       [--list] [--llist] [--locate] [--device DEVICE_ID] [--sound]
                                       [--message MESSAGE] [--silentmessage SILENTMESSAGE] [--lostmode]
                                       [--lostphone LOST_PHONE] [--lostpassword LOST_PASSWORD]
                                       [--lostmessage LOST_MESSAGE] [--outputfile] [--domain DOMAIN]

Find My iPhone CommandLine Tool

options:
  -h, --help            show this help message and exit
  --username USERNAME   Apple ID to Use
  --password PASSWORD   Apple ID Password to Use; if unspecified, password will be fetched from the system keyring.
  -n, --non-interactive
                        Disable interactive prompts.
  --delete-from-keyring
                        Delete stored password in system keyring for this username.
  --list                Short Listings for Device(s) associated with account
  --llist               Detailed Listings for Device(s) associated with account
  --locate              Retrieve Location for the iDevice (non-exclusive).
  --device DEVICE_ID    Only effect this device
  --sound               Play a sound on the device
  --message MESSAGE     Optional Text Message to display with a sound
  --silentmessage SILENTMESSAGE
                        Optional Text Message to display with no sounds
  --lostmode            Enable Lost mode for the device
  --lostphone LOST_PHONE
                        Phone Number allowed to call when lost mode is enabled
  --lostpassword LOST_PASSWORD
                        Forcibly active this passcode on the idevice
  --lostmessage LOST_MESSAGE
                        Forcibly display this message when activating lost mode.
  --outputfile          Save device data to a file in the current directory.
  --domain DOMAIN       Root domain for requests to iCloud. com or cn

**Comment by Speedbird979** [comment]
PEBKAC...

**Comment by AndreyNikiforov** [comment]
Use `icloudpd`, not `icloud`. [See tip](https://github.com/icloud-photos-downloader/icloud_photos_downloader#usage)
