### ISSUE TITLE
KeyError: 'alternative' attribute was not found in the photo field

### ISSUE THREAD

**Issue by smaugfm** [icloud-photos-downloader/icloud_photos_downloader#859]
## Overview
After update to 1.19.0 I occasionally get this errors:
```
KeyError: 'alternative' attribute was not found in the photo fields.
```
I traced the error to this line: 
https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/b49194cc7571beb8e06be840929f43463b69fafe/src/pyicloud_ipd/utils.py#L113

Here are a couple of `icloudpd-photo-error.json`s:
https://gist.github.com/smaugfm/9fbed4bd93a7ae637dac289a6d54867f
https://gist.github.com/smaugfm/4e065051c455592e36d926bb68512dbf

## Steps to Reproduce
Seems to happen with MOV files, HEIC files, etc.

**Comment by AndreyNikiforov** [comment]
fixed in 1.19.1
