### ISSUE TITLE
Need a little help with Truenas Scale setup

### ISSUE THREAD

**Issue by MufasasBalls** [icloud-photos-downloader/icloud_photos_downloader#860]
For the past few hours I have been trying to get the iCloudPD downloader to work from the truecharts repo on my newer Nas build and for the life of me I have gotten nowhere with it. I have looked at my settings compared to some screenshots that @boredazfcuk uploaded in https://github.com/boredazfcuk/docker-icloudpd/issues/381 but a lot of his images don't match up with what is downloaded from truecharts. Am I doing something wrong here? I keep getting the message of 

ERROR    No route to icloud.com found. Please check your container's network settings - exiting
ERROR    Error debug - traceroute: socket(AF_INET,3,1): Operation not permitted

Can someone please explain to me what I am doing wrong here? I am quite lost. Any help would be much appreciated, I am pretty new to some of this stuff so some lingo can be a little confusing, but I am trying to learn it all the best I can.

![Screenshot 2024-06-01 at 10-52-38 TrueNAS - 192 168 1 250](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/146595882/4e2abda9-456e-4138-b9f1-14da05cfc912)
![Screenshot 2024-06-01 at 10-53-08 TrueNAS - 192 168 1 250](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/146595882/2a89aeac-ccfd-4794-9ec8-f053b274d1a5)
![Screenshot 2024-06-01 at 10-53-20 TrueNAS - 192 168 1 250](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/146595882/58d5f567-5734-41c6-9b90-b8a1a22184d9)
![Screenshot 2024-06-01 at 10-53-31 TrueNAS - 192 168 1 250](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/146595882/8f948e3c-9a38-4a93-a953-aebd23ad4f09)
![Screenshot 2024-06-01 at 10-53-41 TrueNAS - 192 168 1 250](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/146595882/d5cb6f55-ec35-444d-ba54-091fa32fcf27)
![Screenshot 2024-06-01 at 10-53-54 TrueNAS - 192 168 1 250](https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/146595882/a7a43178-9a0b-474b-9ad6-08f345aa3381)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

**Comment by AndreyNikiforov** [comment]
I am not yet familiar with trueNas, but instructions you are linking are for a different docker image than this repo, so some config may not work out of the box.

General thoughts for running `icloudpd` docker:
- image is using outgoing networking and it should be easy/zero config for that (as opposite to listening to incoming traffic)
- image needs access to your drives to save downloaded photos - usually done with docker volumes (~=mounting paths from the host into docker container)
- optionally, image can save authentication cookies to disk, so authentication is simplified on container restarts - same as mounting host paths for photos

**Comment by MufasasBalls** [comment]
Yeah and that's what's weird to me. Every other app that has been installed via TrueCharts or the standard TrueNas Repo has worked just fine. As far as I know the image should have full access to the drives, since the user/group have admin access to the apps directory. It's a bit strange.

**Comment by AndreyNikiforov** [comment]
use 1.21.0+. see [doc](https://icloud-photos-downloader.github.io/icloud_photos_downloader/nas.html#truenas) for instructions

**Comment by MufasasBalls** [comment]
This is still not super helpful for someone who is trying to learn this stuff. Has a lot of info sure and I'm thankful for that, but I don't understand what half this info is, so it's still not super helpful.

**Comment by AndreyNikiforov** [comment]
> This is still not super helpful for someone who is trying to learn this stuff. Has a lot of info sure, and I'm thankful for that, but I don't understand what half this info is, so it's still not going to help a novice like me get this up and running. I'd certainly say this is not "Completed"

What specific question do you have?

I started with assumption that user of TrueNAS is familiar with its basic functionality, e.g. setting up pool, dataset etc. I also assumed that even if user hasn't used any apps on TrueNAS yet, they can follow official [TrueNAS doc](https://www.truenas.com/docs/scale/23.10/scaletutorials/apps/usingcustomapp/) to familiarize themselves. With that in mind, I documented only details specific to `icloudpd` on the latest version of TrueNAS.

I never used TrueNAS before. I downloaded the latest version and set it up in VM. Then, by trial and error I setup `icloudpd` and documented all relevant settings. There is, of course, a chance I have missed something.

**Comment by MufasasBalls** [comment]
Some of the wording in the documentation did not line up perfectly with the install of iCloudPD so it was a bit confusing. Things like (Port Forwarding/Host Port), documentation says 9090, sure, that works fine. However in the TruNas app setup it is listed as (Node Port), not Host. That was one that was a little odd. Then (Portal Configuration/Enable Portal Configuration) is what the documentation says but TruNas has it labeled as (Enable WebUI Portal). Also with ports it doesn't tell me if I should be using TCP Protocol or UDP Protocol, little things like this can make it a little confusing. I was able to finally get it working after a bit of trial and error so I would say the documentation did certainly point me in the right direction after I went through it for a while and was able to get it to actually link up. My only questions now are if I am able to set additional things in the ARGs category so I can tell the program to Sort the files a bit differently. In the normal version there is a Configuration file but I don't have access to editing that so I was curious if there is a full list of all the ARGs that can be added to customize it a bit better and such. Thank you for all the help on this though. I do really appreciate it.

**Comment by AndreyNikiforov** [comment]
> Some of the wording in the documentation did not line up perfectly with the install of iCloudPD so it was a bit confusing. Things like (Port Forwarding/Host Port), documentation says 9090, sure, that works fine. However in the TruNas app setup it is listed as (Node Port), not Host. 

You need mapping between Container Port 8080 (because `icloudpd` container is coded to expose port 8080) AND Host Port 9090 where your browser will connect to WebUI (TrueNAS requires port to be >9000 and it can be any unused port, not necessarily 9090). See [TrueNAS doc](https://www.truenas.com/docs/scale/23.10/scaletutorials/apps/usingcustomapp/#figure-8)

> My only questions now are if I am able to set additional things in the ARGs category so I can tell the program to Sort the files a bit differently. In the normal version there is a Configuration file but I don't have access to editing that so I was curious if there is a full list of all the ARGs that can be added to customize it a bit better and such.

`icloudpd` does not support configuration files. You are probably mistaken this project for another one that supports config files: https://github.com/boredazfcuk/docker-icloudpd  If you indeed want to use another project, you need to file support tickets there.

**Comment by MufasasBalls** [comment]
> You need mapping between Container Port 8080 (because `icloudpd` container is coded to expose port 8080) AND Host Port 9090 where your browser will connect to WebUI (TrueNAS requires port to be >9000 and it can be any unused port, not necessarily 9090). See [TrueNAS doc](https://www.truenas.com/docs/scale/23.10/scaletutorials/apps/usingcustomapp/#figure-8)

Right, I get how it works, just the wording on some of the documentation doesn't perfectly match Truenas which is where some of my confusion came in. 

> `icloudpd` does not support configuration files. You are probably mistaken this project for another one that supports config files: https://github.com/boredazfcuk/docker-icloudpd If you indeed want to use another project, you need to file support tickets there.

Also that's on me, I didn't realize there were multiple projects with exactly the same name. I thought initially when I posted this thread it was for Boredazfcuks version, but never the less, this one is working.

Still, are there additional args to control things like the quality of the downloads, and removing files from iCloud after download is completed? Those kinds of things.

**Comment by AndreyNikiforov** [comment]
> > You need mapping between Container Port 8080 (because `icloudpd` container is coded to expose port 8080) AND Host Port 9090 where your browser will connect to WebUI (TrueNAS requires port to be >9000 and it can be any unused port, not necessarily 9090). See [TrueNAS doc](https://www.truenas.com/docs/scale/23.10/scaletutorials/apps/usingcustomapp/#figure-8)
> 
> Right, I get how it works, just the wording on some of the documentation doesn't perfectly match Truenas which is where some of my confusion came in.

Please be specific, so the documentation can be improved.

> Still, are there additional args to control things like the quality of the downloads, and removing files from iCloud after download is completed? Those kinds of things.

The functionality of `icloudpd` grew quite complex over the years and the way to adjust it is to use parameters. See [doc](https://icloud-photos-downloader.github.io/icloud_photos_downloader/#icloud-photos-downloader) ("use --help option to get full list"). TrueNAS example config is what it is - an example to get `icloudpd` on TrueNAS working, which you can customize for your needs with parameters.

**Comment by MufasasBalls** [comment]
> Please be specific, so the documentation can be improved.
Like I mentioned in an earlier post, you have things listed as Host Port when Trunas calls it a node port, certain tiny things like that are confusing for someone trying to learn all of this. 
![image](https://github.com/user-attachments/assets/1c873e76-b9ee-4abf-ac7a-0a0f70374845)
![image](https://github.com/user-attachments/assets/21927fd0-5a3f-4ffd-96bf-19976d5490a5)


> The functionality of `icloudpd` grew quite complex over the years and the way to adjust it is to use parameters. See [doc](https://icloud-photos-downloader.github.io/icloud_photos_downloader/#icloud-photos-downloader) ("use --help option to get full list"). TrueNAS example config is what it is - an example to get `icloudpd` on TrueNAS working, which you can customize for your needs with parameters.

And this I understand, but I am looking for the entire list of args/parameters, I don't see it in your documentation and when I type --help in the shell, I get nothing in return. 
![image](https://github.com/user-attachments/assets/d203acb5-9f89-463f-bcea-96083e982fb5)

**Comment by MufasasBalls** [comment]
Is my previous comment about being able to download all files into a single folder possible in Truenas? I still have not been able to figure out how to get it to function in that manner. @AndreyNikiforov

**Comment by MufasasBalls** [comment]
Okay I think I understand how to args work so "--(command)" is an arg, and then the defining factors for those args are placed right below as a second arg and that defines how it's supposed to function. Also the new WebUI is very nice. Very useful to see all the commands that can be added/adjusted even if I have not added them myself.
