### ISSUE TITLE
How to download historical RAWs?

### ISSUE THREAD

**Issue by hawaaiianmiraclecreel** [icloud-photos-downloader/icloud_photos_downloader#868]
https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/675

I saw that this has been implement and I am super happy! But I cant figure out how to enable this for RAW+JPG. Any guidance? I have been using the default settings but I didnt see any flag to enable downloading of RAWS

Thanks

**Comment by AndreyNikiforov** [comment]
updated [doc](https://icloud-photos-downloader.github.io/icloud_photos_downloader/raw.html)
