### ISSUE TITLE
Documentation: What's the difference of iCloud Photos Downloader to the "Download originals to Mac" setting in Apples Photos?

### ISSUE THREAD

**Issue by rafo** [icloud-photos-downloader/icloud_photos_downloader#873]
Seriously: can't I do exactly the same thing with photos if I have enough space on my hard drive? Somehow I can't figure out from the documentation why I need this tool... Maybe something like "Thanks to iCloud Photos Downloader, you don't need to have all the photos downloaded locally and can still access them selectively" should be added to github and the documentation.

**Comment by AndreyNikiforov** [comment]
I am not familiar with "Download originals to mac" action in Apple photos. Does it download all files from your icloud.com collection to your local drive with just one action? What does it do when you perform the same "Download originals to mac" action again a month later (with the changes to your icloud.com collection)?

**Comment by subinznz** [comment]
<img width="835" alt="image" src="https://github.com/icloud-photos-downloader/icloud_photos_downloader/assets/3947979/051c9a7f-4210-4ea7-804a-9b102db9768b">

Looks like its in the photos settings.

**Comment by subinznz** [comment]
how do you retrieve the files mate ? are you scraping icloud with this tool or is there a seperate API ?

**Comment by subinznz** [comment]
@AndreyNikiforov  how do you retrieve the files mate with this tool ? are you scraping icloud with this tool or is there a seperate API ?

**Comment by AndreyNikiforov** [comment]
> @AndreyNikiforov how do you retrieve the files mate with this tool ? are you scraping icloud with this tool or is there a seperate API ?

`icloudpd` simulates browser access to icloud.com to authenticate and download assets

**Comment by AndreyNikiforov** [comment]
> Seriously: can't I do exactly the same thing with photos if I have enough space on my hard drive? Somehow I can't figure out from the documentation why I need this tool...

If you are happy with whatever you are using today, there is no need to change (==don't use `icloudpd`)

**Comment by rafo** [comment]
@AndreyNikiforov Thanx for the clarification. 

> I am not familiar with "Download originals to mac" action in Apple photos. Does it download all files from your icloud.com collection to your local drive with just one action?

Yes. If you have enough space on your hard drive.

> What does it do when you perform the same "Download originals to mac" action again a month later (with the changes to your icloud.com collection)?

It's not a single action, you activate a continuous sync in both ways. All photos and videos are the same on all devices.

**Comment by boredazfcuk** [comment]
> Yes. If you have enough space on your hard drive.

Awesome. I have 48TB on my server, so bags of room. How do I install this "Photos" app on my Linux server, or even a Windows VM?
