### ISSUE TITLE
Failed to execv() /tmp/staticx-JhBoMc/icloudpd-1.17.3-linux-amd64.dynamic: Permission denied

### ISSUE THREAD

**Issue by BLLiNNK** [icloud-photos-downloader/icloud_photos_downloader#876]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Using icloud photo station to run on Synology NAS
https://github.com/skarppi/icloud_photo_station

This has been working for years but now getting error eveytime i attempt to run the code to sync. 

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. ssh to Synology NAS
2. run below code:
` (env) broche@JARVIS:/tmp$     icloudpd \
> --directory /volume1/iCloud \
> --username x@x.com \
> --until-found 10 \
> --auto-delete `

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
code runs 

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
error:
`Failed to execv() /tmp/staticx-JhBoMc/icloudpd-1.17.3-linux-amd64.dynamic: Permission denied`

**Comment by AndreyNikiforov** [comment]
see https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/master/FAQ.md#running-on-synology-nas
