### ISSUE TITLE
Change locale for folder structure for example

### ISSUE THREAD

**Issue by holomekc** [icloud-photos-downloader/icloud_photos_downloader#897]
I want to be able to change the locale for the python process. The reason is to define folder patterns like this:
`--folder-structure {:%Y/%m\ %B}`

But at the moment this will create something like this:
`.../2024/07 July`

But I want the german translation
`.../2024/07 Juli`

I am a python noob so not 100% sure how and where. Otherwise, I could create a PR. I think though you need to add only this:
https://docs.python.org/3/library/locale.html#locale.setlocale

```python
import locale
locale.setlocale(locale.LC_ALL, '')
```

Although, I am not sure if it needs to be `locale.setlocale(locale.LC_ALL, 'de_DE.UTF-8')`

**Comment by AndreyNikiforov** [comment]
That is interesting use case. IIUC you want `icloudpd` to use locale of the OS. I haven't used anything other than `en` for long time, so I need to learn how locale work. Is it possible to change locale just for one process from OS shell?

**Comment by holomekc** [comment]
Hi @AndreyNikiforov 
thx for the quick answer. I do not think so. At least they say something like this:
https://stackoverflow.com/questions/48270191/python-does-not-use-locale-from-environment
> Initially, when a program is started, the locale is the C locale, no matter what the user’s preferred locale is.

But as I mentioned, I am not that of an python expert.

**Comment by AndreyNikiforov** [comment]
What I have found:
To show available locales:
```shell
locale -a
```
To Install all:
```shell
sudo apt-get update
sudo apt-get install locales locales-all
```
python test.py code:
```python
import datetime
from locale import LC_ALL, setlocale
setlocale(LC_ALL, '')
print(f"{datetime.datetime.now():%B}")
```
to test different locales
```shell
LANG=de_DE.UTF-8 python test.py
```

@holomekc check that works as expected and I'll update `icloudpd` to support reading locales from OS (with the flag)

**Comment by holomekc** [comment]
Hi @AndreyNikiforov 

```Dockerfile
FROM python:bookworm

RUN apt-get update && apt-get install locales locales-all -y

RUN locale

RUN echo 'import datetime\nfrom locale import LC_ALL, setlocale\n\nsetlocale(LC_ALL, "")\nprint(f"{datetime.datetime.now():%B}")' > test.py

RUN LANG=de_DE.UTF-8 python test.py
```

```log
Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM python:bookworm
 ---> fa2a2a87a538
Step 2/5 : RUN apt-get update && apt-get install locales locales-all -y
 ---> Using cache
 ---> 0c3aa0d3fafa
Step 3/5 : RUN locale
 ---> Running in e35e457d779e
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=
Removing intermediate container e35e457d779e
 ---> 51cf133ede5d
Step 4/5 : RUN echo 'import datetime\nfrom locale import LC_ALL, setlocale\n\nsetlocale(LC_ALL, "")\nprint(f"{datetime.datetime.now():%B}")' > test.py
 ---> Running in 1ac3f44c2520
Removing intermediate container 1ac3f44c2520
 ---> 5a338c32e909
Step 5/5 : RUN LANG=de_DE.UTF-8 python test.py
 ---> Running in c4760d5c9e74
Juli
Removing intermediate container c4760d5c9e74
 ---> 4367c0fde5a8
Successfully built 4367c0fde5a8
Successfully tagged test:latest
```

Yes this works. "Juli" is printed.

**Comment by AndreyNikiforov** [comment]
v1.22.0 has `--use-os-locale` flag. During testing, I learnt more about locales and building [compatibility for tz & locale in each release](https://github.com/icloud-photos-downloader/icloud_photos_downloader/releases/download/v1.22.0/tzlc-1.22.0.md) - while there is an opportunity to improve, I hope your issue is resolved.

**Comment by holomekc** [comment]
Thank you so much for the hard work!
