### ISSUE TITLE
What happens if I moved the photos within the directory used by icloudpd (watched by other photo organizer software)

### ISSUE THREAD

**Issue by dsync89** [icloud-photos-downloader/icloud_photos_downloader#904]
## Context
I'm currently using Mylio Photos to organize my photo thanks to its rich tagging/filter capabilities. What happens if I **link** the icloud folder used by icloudpd from Mylio and then move pictures within that folder? Will icloudpd detect that the photo is now missing from the icloud folder and then attempt to download again? Or would it constantly check if any of the files in icloud has missing hash, and only download if it is not found, regardless of its physical location in the icloud folder? Hope the later is true and my current workflow will work as expected.

For example: `[]` is folder

Before moving
```
[2024]
- img01.png
- img02.png
```

I then move `img01.png` to another folder `test`.
```
[2024]
- img02.png
[test]
- img01.png
```

Would icloudpd download `img01.png` and placed it under `[2024]` folder if I moved it?

**Comment by AndreyNikiforov** [comment]
> What happens if I link the icloud folder used by icloudpd from Mylio and then move pictures within that folder? 

Haven't tried that. Curious to know what your experimentation brings.

> Will icloudpd detect that the photo is now missing from the icloud folder and then attempt to download again? Or would it constantly check if any of the files in icloud has missing hash, and only download if it is not found, regardless of its physical location in the icloud folder?

Linking aside, `icloudpd` just checks files on the disk and if they are not present, downloads them. There are [two options](https://icloud-photos-downloader.github.io/icloud_photos_downloader/naming.html#duplicates) to tune presence checking logic, but hashing is not one of them.
