### ISSUE TITLE
some version check failure with 1.22.0 and 1.23.0

### ISSUE THREAD

**Issue by chenrui333** [icloud-photos-downloader/icloud_photos_downloader#922]
👋 seeing some version test failures with 1.22.0 and 1.23.0. Any pointer? Thanks!

```

version:0.0.1, commit sha:abcdefgh, commit timestamp:Fri Feb 13 18:31:30 2009 EST

```

relates to:
- https://github.com/Homebrew/homebrew-core/pull/177174
- https://github.com/Homebrew/homebrew-core/pull/178524

**Comment by AndreyNikiforov** [comment]
version and commit info is constructed during release process. You can a) use one of the wheels produced by release, or b) replicate part of the release process.

for a) you need to use `pip install --find-links <folder_with_downloaded wheels>`
for b) run scripts/patch_version

Note that solution (b) relies on internals of the `icloudpd` release process (not a public "API") and is subject to change at any moment.
