### ISSUE TITLE
How to download photos from all libraries once

### ISSUE THREAD

**Issue by moonsquare** [icloud-photos-downloader/icloud_photos_downloader#923]
How can I download all libraries at once instead of multiple times? Currently, I can find all libraries through the --list-libraries parameter, and then download them multiple times through the --library parameter. Does the --library parameter support a command similar to all?

**Comment by AndreyNikiforov** [comment]
Only one library at a time is supported. Support for multiple accounts, libraries, albums is on my mind, but not immediately planned.

**Comment by AndreyNikiforov** [comment]
1.32.0 support multiple configs and, by extension, multiple libraries
