### ISSUE TITLE
Running docker container as non-root user

### ISSUE THREAD

**Issue by isundaylee** [icloud-photos-downloader/icloud_photos_downloader#953]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
Just started with `icloudpd` so apology in advance if I missed anything. I noticed that the docker command given in the documentation runs the commands inside the container as the `root` user - so all the downloaded files are owned by `root`. I couldn't seem to find a way to have the commands inside the container run as a given non-`root` user instead.

I tried adding `--user` to the command, but it gives me

```
$ sudo docker run --user 21015:21015 -it --rm --name icloudpd -p 8080:8080 -v ... -e TZ=America/New_York icloudpd/icloudpd:latest icloudpd --directory=/data --username=... --watch-with-interval=3600 --until-found=1 --password-provider=webui --mfa-provider=webui

Traceback (most recent call last):
  File "starters/icloudpd_ex.py", line 122, in <module>
  File "starters/icloudpd_ex.py", line 118, in main
  File "click/core.py", line 1157, in __call__
  File "click/core.py", line 1078, in main
  File "click/core.py", line 1688, in invoke
  File "click/core.py", line 1434, in invoke
  File "click/core.py", line 783, in invoke
  File "icloudpd/base.py", line 745, in main
  File "icloudpd/base.py", line 1179, in core
  File "icloudpd/authentication.py", line 53, in authenticate_
  File "pyicloud_ipd/base.py", line 105, in __init__
PermissionError: [Errno 13] Permission denied: '/.pyicloud'
[8] Failed to execute script 'icloudpd_ex' due to unhandled exception!
```

For reference, usually other Docker containers I've used expose env vars `PUID` and `PGID` to support this. 

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )

This feature would be helpful to better control the owner and permissions of downloaded files.

**Comment by AndreyNikiforov** [comment]
try specifying cookie dir on mounted volume with sufficient permissions

**Comment by AndreyNikiforov** [comment]
> try specifying cookie dir on mounted volume with sufficient permissions

explanation: `$HOME/.pyicloud` is the default folder where `icloudpd` persists authentication information. `--cookie-directory` parameter can be used to override that setting. Since you are changing user id for the process, that folder should have access by that new user id and AFAIK one way to achieve that is to mount it from the host.

**Comment by isundaylee** [comment]
That did the trick, thank you very much!
