### ISSUE TITLE
When multiple sizes and --force-size are specified, some sizes can be skipped even if exist.

### ISSUE THREAD

**Issue by iowk** [icloud-photos-downloader/icloud_photos_downloader#955]
## Overview
When both `--size medium` and  `--size thumb` are specified with `--force-size`, but only the thumb-size asset exists for a photo, both sizes will be skipped.

## Steps to Reproduce
1. Upload a small image to iCloud Photos, such that the medium-size asset exists but thumb-size does not. (e.g. a 200*250 heic file)
2. Execute `icloudpd -d syncdir --size medium --size thumb --force-size`.

## Expected Behavior
The medium-size asset should be skipped and the thumb-size asset should be downloaded.

## Actual Behavior
Both medium-size and thumb-size assets are skipped.

## Context
Changing this to `continue` should be a simple fix.
https://github.com/icloud-photos-downloader/icloud_photos_downloader/blob/6e9c6c69996a39d0e7f77c9fd4f9b160b4b8bcdd/src/icloudpd/base.py#L896
I would be glad to issue a PR if you consider this appropriate.

**Comment by iowk** [comment]
I have created a PR with tests.

I am developing an application that utilizes the assets to preview the photos.

It would be helpful to me if `--live-photo-size` also supports multiple sizes. I can work on that if you think it's a good idea.

**Comment by AndreyNikiforov** [comment]
> It would be helpful to me if `--live-photo-size` also supports multiple sizes. I can work on that if you think it's a good idea.

I did not see requests for live photo and main assets sizes, so I suspect that with the increase of the internet speed, ppl are using original size. From that point of view, I do not see much value in implementing multiple size support for live photos.
