### ISSUE TITLE
Every version Shuts itself down

### ISSUE THREAD

**Issue by ChillyFlake** [icloud-photos-downloader/icloud_photos_downloader#963]
## Overview
[TIP]:  # ( DO NOT include your login-information when pasting in program output! )
[NOTE]: # ( Give a BRIEF summary about your problem )
Essentially no matter what version i use, icloudpd-ex-1.23.4-windows-amd64, icloud-1.23.4-windows-amd64, or icloud-1.23.4-windows-amd64, even a 1.15 something that i know for a FACT worked earlier in the year, they all open, and either shut themselves off as soon as they load text, or they let me enter my username, tell me i did it wrong, then shut off.

## Steps to Reproduce
[NOTE]: # ( Provide a simple set of steps to reproduce this bug. )
1. Open it
2. Wait
3. If it doenst do it by itself, enter any command- accepted or otherwise-, and wait

## Expected Behavior
[NOTE]: # ( Tell us what you expected to happen )
I expect it to function

## Actual Behavior
[NOTE]: # ( Tell us what actually happens )
It doesnt

## Context
[NOTE]: # ( Give us any additional information you may have. )
I dunno i cant think of anything that would have changed between now and when 1.15 was the latest + why 1.15 wouldnt work + + why any and all versions (windows 64 amd is my comp) just bungle instantly. 
i also cant get any docker to work and i dont know the first thing about building myself, and i would LOVE if i had to restart my pc as little as possible (already have once) because it takes about an hour to go from on to off to back to on (which i know because i reset it twice today.)

**Comment by AndreyNikiforov** [comment]
How are you running executable? What does it tell you when you run it? Run it in opened command window, so you can see the output.

`icloudpd` is the one that download photos, `icloud` is for managing saved credentials. Choose the one you need. Worth checking [documentation](https://icloud-photos-downloader.github.io/icloud_photos_downloader/)

**Comment by ChillyFlake** [comment]
> How are you running executable? What does it tell you when you run it? Run it in opened command window, so you can see the output.
^ I was downloading it and then running it. I tried that numerous times, but every time itd ask for my username, and i'd give it, it'd close after telling me i didnt do correct syntax (not including --directory for example). Key thing to note is if i DID include the necessary parts, passwords and instructions, itd open a bigger menu that is clearly the next step, and then crash.

> `icloudpd` is the one that download photos, `icloud` is for managing saved credentials. Choose the one you need. Worth checking [documentation](https://icloud-photos-downloader.github.io/icloud_photos_downloader/)
^ Funnily enough, the documentation has NO actual instructions as far as i can see for just running it normally. As in, it tells you what each command does, sort of, but theres not really a dummys guide to "Start with this copy paste and tailor it to your needs". (I assume cause the program itself would tell you all that.)
All the installation instructions are obviously for dockers or building yourself since you just download it and run it if you go that route, and nowhere is there a reason my experience would be happening.
With that said, i started with `icloudpd`, and when that didnt work no matter what i did, i tried the others in a vain hope that something would happen. Some of them crashed before putting out anything, and some of them didnt even let me type at all.

**Comment by AndreyNikiforov** [comment]
To help you I need three answers:
- What are you trying to achieve? I assume to download photos from iCloud
- How are you trying to achieve your goal? I need full command line pasted here (replace sensitive info of course) and version you are using
- Where your expectations are not met? I need error that you get when the app is crashing.

**Comment by ChillyFlake** [comment]
- Download photos from iCloud, removing them from it in the process to ease my storage limit (I have plenty of storage on my External Hard Drive)
- Given that i recall last time being instructed with --help / --h to construct the specific command line, i don't have an inkling that it is even related, nor have i had the ability to construct what i need given that there's no documentation online on how to use the basic feature, just specific niches.. No matter what i type, the same thing happens.
  - With that said, both my Email (which i wont share of course but the command is formatted as "someone@email.com") and basics like "`--h`" "`--help`" "`[email] --list-libraries`" etc all do the same thing, as if it doesn't even read my commands
    - Scratch the above, i just tried before submitting this "`--username [Email] --password [Password] -h`" and "`--username [Email] --password [Password]--libraries`" and neither of them were recognized as anything, giving me the same 'these are required' messages as seen in the attatchment.
- Versions 1.23.4 and versions 1.15.1, with version 1.15.1 having worked earlier this year.
- I am getting no error code at all. It appears to be working fine, giving me things like "you didn't include the directory", then crashes

I'm attatching a video including all versions ive tried (some 23.4 some 15.1) to show exactly what is happening, with all sensitive info removed 

https://github.com/user-attachments/assets/be2fbdfb-b4e3-404f-a8b6-4696693894ac

**Comment by AndreyNikiforov** [comment]
Do you have command that you used last time that `icloudpd` worked for you? You keep mentioning that 1.15 worked and exactly the same params should continue to work in 1.23

Great that you figured how to use `--help` param - it should give you all other params. We do have [Reference](https://icloud-photos-downloader.github.io/icloud_photos_downloader/reference.html) online too.

Using `icloudpd --username your@email.address --directory photos` as you mentioned, should be the minimum that works. What error does it give to you?

**Comment by ChillyFlake** [comment]
pasting that command directly in both 1.15.1 and 1.23.4 (the icloudpd versions) does the same thing as in the video and previous reply. replacing the username with my own made no difference, and even with the proper directory photos direction it still says 
![image](https://github.com/user-attachments/assets/44bbd82b-09fb-443b-a5e4-3bb94af02234)

^and then after saying that, it instantly closes itself. the only way i got this screenshot was by quickdraw style pressing print screen, which i failed to do a few times because of how quickly it closed. 

So, like, no error is given? and i didnt think to write down the command i used last time, i figured when i next used it i could figure it out in 10 minutes or less like i had done the first time with the in program instructions

**Comment by AndreyNikiforov** [comment]
> pasting that command directly in both 1.15.1 and 1.23.4 (the icloudpd versions) does the same thing as in the video and previous reply. replacing the username with my own made no difference, and even with the proper directory photos direction it still says `--auth-only, --directory, --list-libraries or --list-albums are required`
> 
> ![image](https://private-user-images.githubusercontent.com/133548613/376418335-44bbd82b-09fb-443b-a5e4-3bb94af02234.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjU0OTEsIm5iZiI6MTcyODk2NTE5MSwicGF0aCI6Ii8xMzM1NDg2MTMvMzc2NDE4MzM1LTQ0YmJkODJiLTA5ZmItNDQzYi1hNWU0LTNiYjk0YWYwMjIzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQwNDA2MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMTkzN2Y2YjNiNDk5NGQzZWJjOTgxNWQ0MjczZjQwMTA2NDgyM2ViNzZlOGZhOGVjNTE3ODJkZWI4YTYyZTEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.HWVjOsYN8x3j-Ow6yHWrFSayUHm-uHq7bqI8IJdv0GU)
> 
> (the above happens if i remove the `icloudpd` part as well given this example is in the pd, and i cant get any other version of 1.23.4 to let me type at all) and then after saying that, it instantly closes itself. the only way i got this screenshot was by quickdraw style pressing print screen, which i failed to do a few times because of how quickly it closed.
> 
> So, like, no error is given? and i didnt think to write down the command i used last time, i figured when i next used it i could figure it out in 10 minutes or less like i had done the first time with the in program instructions

Screenshot does not have the command you pasted. It is usually easier to understand what you are doing when you have command prompt, command you entering, and output. Copy-paste is enough (and you can replace sensitive info) - no need for screenshots or videos (btw video you uploaded on github plays for couple seconds only, so it is useless).

Given that we are discussing how to run cli on windows, I suggest:
1. get yourself comfortable with cli on windows. See if you can list content of a couple of folders with "dir" command and have results saved in text files with the help of notepad
2. proceed with `icloudpd` experiments

**Comment by ChillyFlake** [comment]
the screenshot does have the command pasted? literally directly from your last responce, `icloudpd --username your@email.address --directory photos`, which ive run both exactly as pasted, replacing the dummy email with my own, including `--password [my password` in every variable slot, replacing the last command with the other ones the program briefly suggest, and nothing else works any differently.
I also can't copy the terminal or anything it does, because as ive hopefully made clear i have maybe half a second before it closes.

I am also familiar with the command line enough, and have used it both admin or otherwise to test these exe's multiple times. Including navigating directories and syntax and all that. As i said in one of my first replies, running it in the command prompt from the directory does the same thing, but instead of closing the window, it just returns me to the directory and shuts itself as a program down.

and just for posterity, [heres the video uploaded to youtube](https://youtu.be/Og28SWn8H_k) of what happens whenever i try and use any of them.

With that all said, i feel i cant really do any more experimenting without a better understanding of the program or whatever is causing this bug, whether it be my system or not, because simply nothing i do will produce anything except a no error code no feedback shutdown of the program

**Comment by AndreyNikiforov** [comment]
Your video shows that you are starting icloudpd from UI, not from command prompt. Start command prompt, then familiarize yourself with commands there, e.g. "dir", copy-pasting command and output, etc, and then experiment with `icloudpd`.

**Comment by AndreyNikiforov** [comment]
> 
> But because you dont seem to beleive me, i've went ahead and screenshotted it for you ![image](https://private-user-images.githubusercontent.com/133548613/376661340-8735ec35-b9e7-4bab-a692-a0280dc746fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkwMTA2NDYsIm5iZiI6MTcyOTAxMDM0NiwicGF0aCI6Ii8xMzM1NDg2MTMvMzc2NjYxMzQwLTg3MzVlYzM1LWI5ZTctNGJhYi1hNjkyLWEwMjgwZGM3NDZmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxNVQxNjM5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZGRjMGMzM2Y3MzcxNDdjZGZkZTcwM2Q0NWJlYmVlZWM5MTZhMDFlYzAzNjFiMzk0MDA3OTRlMDgzZTdjYmIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.7kX5OSjQ3Jr2Xs1iE5G3SbEBHz71o_Pv4Z9wpmCh7og)

Nice. You can just copy-paste text from the command prompt - may be easier to work with.

You are running `icloudpd` without any parameters (based on screenshot). Now try to run `icloudpd --username your@email.address --directory your_path_somewhere` and post here. Should show a) what you are executing b) the output of the execution

**Comment by ChillyFlake** [comment]
I mean this with no animosity, but are you not fully reading my responses? Because it feels like you are, at most, skimming them, and not listening to what i've been saying. 
- I am having no issue with using the command prompt; i am familier with it, it is not difficult for me to use, nor is it in any way making any appreciable or notable difference in this process.
- i have run this command or some variation of it so many times, and not even once has it produced any outcome. 
  - **at no point has any command been recognized as anything, including this command you gave me to copy paste, which i have already done multiple times up to this point.**

But, just to give you the info you are asking for, here is another screenshot, as i find it more secure and telling than just copy pasting the text. 
![image](https://github.com/user-attachments/assets/f0515e5e-8661-453a-a546-2248553cbdae)

As you can see, whether i include the username, whether i include `icloudpd` at the start, whether i include a password, nothing works. It's not that it doesnt work, its that **it isnt recognizing \*anything\* i've put in. It doesn't see these as incomplete commands, it plain does not see them as commands.**

**Comment by ChillyFlake** [comment]
without including the password, it would simply ask for a password, but not let me input anything. That is, the command prompt still lets me click and highlight stuff, but it no longer recognized any inputs. 

![image](https://github.com/user-attachments/assets/9c895b67-ad9e-4854-ab72-a849b87b6b40)

With that said, if i include the password in the initial prompt, like youve shown above (which took some troubleshooting because i didnt notice some syntax, chalk that up to no ones fault since i was copy pasting) it actually works! I had to terminate it cause i wanted delete after download but it was easy enough, and its running right now.

With that said, i still maintain that something about the program is bugging out on me. I definitly did not have to go through this rigamarole of running it from command line the last time i had done it, and the help menus in program that i can see for a fraction of a second dont make any sense if the program is SUPPOSED to auto shut down. 
That, combined with the freezing when it didnt get the entire prompt at once, but it DOES prompt me to give the rest of it, and freezes before i can do so, still tell me theres an issue. While i didn't think to run the command in the same line as running the program (so hats of to you for letting me know i could), that shouldnt be the ONLY way to get this to work when theres clearly instructions for not having to do that?

Not a complaint though, clearly its my machine or download in some way. doesnt matter much either since now its working so yay
