### ISSUE TITLE
Setting file owner/group/permissions

### ISSUE THREAD

**Issue by boredazfcuk** [icloud-photos-downloader/icloud_photos_downloader#98]
Hi,
Would there be a way of setting owner/group/permissions at the same time? I'm currently running:

```
find '/home/loginname/Pictures' -type d ! -group admins -exec chgrp admins {} \;
find '/home/loginname/Pictures' -type f ! -group admins -exec chgrp admins {} \;
find '/home/loginname/Pictures' -type d ! -perm 770 -exec chmod 770 {} +
find '/home/loginname/Pictures' -type f ! -perm 660 -exec chmod 660 {} +
```
...to change the group and permissions to allow admins and prevent public from viewing files.

Additional command line options would be great, such as: 

-owner=loginname
-group=admins
-dperms=750
-fperms=640

would be great.

**Comment by ndbroadbent** [comment]
Hi @boredazfcuk, sorry I didn't respond earlier. I would definitely accept a PR to set file permissions. I don't currently have a need for that, but if you or anyone else would like to contribute this feature, please feel free to check out our [contributing guidelines](https://github.com/ndbroadbent/icloud_photos_downloader#contributing) and send a PR!
