### ISSUE TITLE
iCloud compromised

### ISSUE THREAD

**Issue by Tico03** [icloud-photos-downloader/icloud_photos_downloader#980]
I don't know anything about coding or whatever but I have for years now had issues with my iCloud and passwords I have lost multiple accounts and don't want to keep starting over can someone please help

**Comment by Cantello** [comment]
Nothing to do with icloud-photos-downloader but start using a proper password manager, use strong passwords and secure your workstation, i.e. make sure nobody has access apart from you. Multiple lost accounts sounds either like malware of the computer, sloppy passwords or senility.

**Comment by Tico03** [comment]
Thanks for the advice I'll make sure to secure it better
