### ISSUE TITLE
what

### ISSUE THREAD

**Issue by 14278358** [icloud-photos-downloader/icloud_photos_downloader#987]
pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20101",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[22616] Failed to execute script 'icloudpd' due to unhandled exception!

pyicloud_ipd.exceptions.PyiCloudFailedLoginException: ('Invalid email/password combination.', PyiCloudAPIResponseException('{\n  "serviceErrors" : [ {\n    "code" : "-20283",\n    "message" : "Enter the email or phone number and password for your Apple\xa0Account.",\n    "suppressDismissal" : false\n  } ]\n} (401)'))
[15340] Failed to execute script 'icloudpd' due to unhandled exception!

**Comment by AndreyNikiforov** [comment]
dup #975 ?
