### ISSUE TITLE
Allow domain to be pointed to an IP Address and not only a .com domain 

### ISSUE THREAD

**Issue by LawMixer** [icloud-photos-downloader/icloud_photos_downloader#990]
## Summary
I don't have a domain, and right now, I'm running it by exposing the port - working on a more permeant solution, but right now it's how it is. 

The error:
``Error: Invalid value for '--domain': 'http://193.31.31.25:2305' is not one of 'com', 'cn'.``

**Comment by AndreyNikiforov** [comment]
[domain is for resolving access from China](https://icloud-photos-downloader.github.io/icloud_photos_downloader/authentication.html#access-from-mainland-china) and not related to Web UI port

**Comment by AndreyNikiforov** [comment]
> I'm not in China, I'm from the US - I assume that doesn't make a difference?

What are you trying to achieve? How did you come to the solution with using `--domain` parameter? "I'm running it by exposing the port" suggests that you are running `icloudpd` with [WebUI](https://icloud-photos-downloader.github.io/icloud_photos_downloader/webui.html) which is served on a 8080 port.

**Comment by LawMixer** [comment]
http://<ip here>:5100 

will error out

**Comment by AndreyNikiforov** [comment]
> http://:5100
> 
> will error out

What are you trying to achieve? Tell me in English. Then show cmd line you use to get minimal working version towards your goal and that is breaking. Urls not helping me help you.

**Comment by LawMixer** [comment]
I want to change the WebUI Port from 8080 to a custom port, but I cannot do that as there is no feature for it not unless there is one and I didn't find it.

**Comment by AndreyNikiforov** [comment]
> I want to change the WebUI Port from 8080 to a custom port, but I cannot do that as there is no feature for it not unless there is one and I didn't find it.

changing port for webui is not supported. If you are using docker, then remapping ports is supported by docker itself. There may be other solutions to remap/proxy ports.

**Comment by LawMixer** [comment]
Will it be supported in the future? 8080 is the port that is taken up by another process, and I really can't move stuff around.

**Comment by LawMixer** [comment]
This is the error I get whenever I try to use the WebUI.

https://i.imgur.com/roy3Gmc.png

**Comment by AndreyNikiforov** [comment]
> Will it be supported in the future? 8080 is the port that is taken up by another process, and I really can't move stuff around.

No plans currently, but it is small feature, so it can be added. Can you explain what system you are running `icloudpd` on, so that port remapping is not available? IIUC WebUI is mostly useful on servers/NAS, where docker (with port remapping) is a popular way to manage software, so port remapping in the `icloudpd` itself is not needed.

**Comment by LawMixer** [comment]
Oh sorry, I mis-said - I meant that every time I remapped the ports, it wouldn't run because the default of the Flask is 8080 and I have other docker applications running on 8080, so it will say ``Address In Use`` which if I did a remap, it would move those same ports. 

I use [Komodo](https://github.com/mbecker20/komodo/tree/main) to manage my docker containers, and the web UI will not startup because of that error I previously shared.
https://i.imgur.com/roy3Gmc.png

**Comment by AndreyNikiforov** [comment]
> Oh sorry, I mis-said - I meant that every time I remapped the ports, it wouldn't run because the default of the Flask is 8080 and I have other docker applications running on 8080, so it will say `Address In Use` which if I did a remap, it would move those same ports.

With [docker port forwarding](https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/) you map listening port of the app inside container, e.g. 8080 for icloudpd, to the port on the host, e.g. 8081. That way you can have multiple containers, say, for icloudpd, running on the same host and all of them listening on different ports on the host, e.g. 8081, 8082, 8083, etc. Default Flask port is irrelevant.

> 
> I use [Komodo](https://github.com/mbecker20/komodo/tree/main) to manage my docker containers, and the web UI will not startup because of that error I previously shared. https://i.imgur.com/roy3Gmc.png

See [TrueNas config](https://icloud-photos-downloader.github.io/icloud_photos_downloader/nas.html#truenas) for example of port mapping, I am sure Komodo supports something similar.

**Comment by boredazfcuk** [comment]
> With docker port forwarding you map listening port of the app inside container, e.g. 8080 for icloudpd, to the port on the host, e.g. 8081. That way you can have multiple containers, say, for icloudpd, running on the same host and all of them listening on different ports on the host, e.g. 8081, 8082, 8083, etc. Default Flask port is irrelevant.

I'm not sure this is entirely accurate. I've see behaviour in the past where multiple nginx containers cannot use port internal port 80/443 because it conflicts with other containers. I think it may be if the containers are attached to the same Docker network. Not 100% sure as it's been a while since I saw it.

**Comment by LawMixer** [comment]
> > Oh sorry, I mis-said - I meant that every time I remapped the ports, it wouldn't run because the default of the Flask is 8080 and I have other docker applications running on 8080, so it will say `Address In Use` which if I did a remap, it would move those same ports.
> 
> With [docker port forwarding](https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/) you map listening port of the app inside container, e.g. 8080 for icloudpd, to the port on the host, e.g. 8081. That way you can have multiple containers, say, for icloudpd, running on the same host and all of them listening on different ports on the host, e.g. 8081, 8082, 8083, etc. Default Flask port is irrelevant.
> 
> > I use [Komodo](https://github.com/mbecker20/komodo/tree/main) to manage my docker containers, and the web UI will not startup because of that error I previously shared. https://i.imgur.com/roy3Gmc.png
> 
> See [TrueNas config](https://icloud-photos-downloader.github.io/icloud_photos_downloader/nas.html#truenas) for example of port mapping, I am sure Komodo supports something similar.


This is not working for me - I set my ports to 2303:2306 and it's still not working:

https://imgur.com/kGTIqBm
https://imgur.com/meCLouA

**Comment by AndreyNikiforov** [comment]
> > > Oh sorry, I mis-said - I meant that every time I remapped the ports, it wouldn't run because the default of the Flask is 8080 and I have other docker applications running on 8080, so it will say `Address In Use` which if I did a remap, it would move those same ports.
> > 
> > 
> > With [docker port forwarding](https://docs.docker.com/get-started/docker-concepts/running-containers/publishing-ports/) you map listening port of the app inside container, e.g. 8080 for icloudpd, to the port on the host, e.g. 8081. That way you can have multiple containers, say, for icloudpd, running on the same host and all of them listening on different ports on the host, e.g. 8081, 8082, 8083, etc. Default Flask port is irrelevant.
> > > I use [Komodo](https://github.com/mbecker20/komodo/tree/main) to manage my docker containers, and the web UI will not startup because of that error I previously shared. https://i.imgur.com/roy3Gmc.png
> > 
> > 
> > See [TrueNas config](https://icloud-photos-downloader.github.io/icloud_photos_downloader/nas.html#truenas) for example of port mapping, I am sure Komodo supports something similar.
> 
> This is not working for me - I set my ports to 2303:2306 and it's still not working:
> 
> https://imgur.com/kGTIqBm https://imgur.com/meCLouA

You need to map 8080 in icloudpd container to available port on the host. [Komodo Immich server example](https://raw.githubusercontent.com/mbecker20/komodo/main/screenshots/Light-Compose.png) maps 2283 host port to 3001 container port

**Comment by LawMixer** [comment]
> You need to map 8080 in icloudpd container to available port on the host. [Komodo Immich server example](https://raw.githubusercontent.com/mbecker20/komodo/main/screenshots/Light-Compose.png) maps 2283 host port to 3001 container port

Hahha, this works! Thank you! Amazing work you've done!
