### ISSUE TITLE
iCloud Photos Downloader Windows Version 1.24.0 being detected as MALWARE - Trojan:Win32/Wactac.B!ml

### ISSUE THREAD

**Issue by CreativePR** [icloud-photos-downloader/icloud_photos_downloader#996]
Today with Windows Version 1.24.0 of iCloud Photos Downloader it is being detected as Trojan:Win32/Wactac.B!ml

Will try a new version to see if it is different

**Comment by CreativePR** [comment]
Current Windows version 1.24.3 is not being detected as being Malware

**Comment by AndreyNikiforov** [comment]
`icloudpd` has been periodically incorrectly detected as virus/malware by some tools. Nothing can be done on our side AFAIK.
