### ISSUE TITLE
iCloud Photos Downloader Windows Version 1.24.3 being detected as MALWARE - Trojan:Win32/Wactac.B!ml 

### ISSUE THREAD

**Issue by CreativePR** [icloud-photos-downloader/icloud_photos_downloader#997]
Today with Windows 11  Security said that icloudPD windows  Version 1.24.0 of iCloud Photos Downloader it is being detected as Trojan:Win32/Wactac.B!ml

**Comment by AndreyNikiforov** [comment]
See [comment on the old post](https://github.com/icloud-photos-downloader/icloud_photos_downloader/issues/832#issuecomment-2138369206)
